// Code generated by shengen from demo/workflow-saga/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- SagaId ---
// Shen: (datatype saga-id)
type SagaId struct{ v string }

func NewSagaId(x string) (SagaId, error) {
	if !(!(x == "")) {
		return SagaId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return SagaId{v: x}, nil
}

func (t SagaId) Val() string { return t.v }


// --- StepName ---
// Shen: (datatype step-name)
type StepName struct{ v string }

func NewStepName(x string) (StepName, error) {
	if !(!(x == "")) {
		return StepName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return StepName{v: x}, nil
}

func (t StepName) Val() string { return t.v }


// --- StepIndex ---
// Shen: (datatype step-index)
type StepIndex struct{ v float64 }

func NewStepIndex(x float64) (StepIndex, error) {
	if !(x >= 0) {
		return StepIndex{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return StepIndex{v: x}, nil
}

func (t StepIndex) Val() float64 { return t.v }


// --- StepCompleted ---
// Shen: (datatype step-completed)
type StepCompleted struct {
	saga SagaId
	step StepName
	index StepIndex
	timestamp float64
}

func NewStepCompleted(saga SagaId, step StepName, index StepIndex, timestamp float64) (StepCompleted, error) {
	if !(timestamp > 0) {
		return StepCompleted{}, fmt.Errorf("timestamp must be > 0")
	}
	return StepCompleted{
		saga: saga,
		step: step,
		index: index,
		timestamp: timestamp,
	}, nil
}

func (t StepCompleted) Saga() SagaId { return t.saga }

func (t StepCompleted) Step() StepName { return t.step }

func (t StepCompleted) Index() StepIndex { return t.index }

func (t StepCompleted) Timestamp() float64 { return t.timestamp }


// --- StepCompensated ---
// Shen: (datatype step-compensated)
type StepCompensated struct {
	completed StepCompleted
	compensatedAt float64
}

func NewStepCompensated(completed StepCompleted, compensatedAt float64) (StepCompensated, error) {
	if !(compensatedAt > 0) {
		return StepCompensated{}, fmt.Errorf("compensatedAt must be > 0")
	}
	return StepCompensated{
		completed: completed,
		compensatedAt: compensatedAt,
	}, nil
}

func (t StepCompensated) Completed() StepCompleted { return t.completed }

func (t StepCompensated) CompensatedAt() float64 { return t.compensatedAt }


// --- StepOrdered ---
// Shen: (datatype step-ordered)
type StepOrdered struct {
	stepA StepCompleted
	indexB StepIndex
}

func NewStepOrdered(stepA StepCompleted, indexB StepIndex) (StepOrdered, error) {
	if !(stepA.index.Val() < indexB.Val()) {
		return StepOrdered{}, fmt.Errorf("stepA.index must be < indexB")
	}
	return StepOrdered{
		stepA: stepA,
		indexB: indexB,
	}, nil
}

func (t StepOrdered) StepA() StepCompleted { return t.stepA }

func (t StepOrdered) IndexB() StepIndex { return t.indexB }


// --- SagaCompleted ---
// Shen: (datatype saga-completed)
type SagaCompleted struct {
	saga SagaId
	stepCount float64
	completedCount float64
}

func NewSagaCompleted(saga SagaId, stepCount float64, completedCount float64) (SagaCompleted, error) {
	if !(stepCount > 0) {
		return SagaCompleted{}, fmt.Errorf("stepCount must be > 0")
	}
	if !(completedCount == stepCount) {
		return SagaCompleted{}, fmt.Errorf("completedCount must equal stepCount")
	}
	return SagaCompleted{
		saga: saga,
		stepCount: stepCount,
		completedCount: completedCount,
	}, nil
}

func (t SagaCompleted) Saga() SagaId { return t.saga }

func (t SagaCompleted) StepCount() float64 { return t.stepCount }

func (t SagaCompleted) CompletedCount() float64 { return t.completedCount }


// --- SagaFailed ---
// Shen: (datatype saga-failed)
type SagaFailed struct {
	saga SagaId
	failedStep StepName
	failedIndex StepIndex
	completedBefore float64
}

func NewSagaFailed(saga SagaId, failedStep StepName, failedIndex StepIndex, completedBefore float64) (SagaFailed, error) {
	if !(completedBefore >= 0) {
		return SagaFailed{}, fmt.Errorf("completedBefore must be >= 0")
	}
	if !(completedBefore == failedIndex.Val()) {
		return SagaFailed{}, fmt.Errorf("completedBefore must equal failedIndex")
	}
	return SagaFailed{
		saga: saga,
		failedStep: failedStep,
		failedIndex: failedIndex,
		completedBefore: completedBefore,
	}, nil
}

func (t SagaFailed) Saga() SagaId { return t.saga }

func (t SagaFailed) FailedStep() StepName { return t.failedStep }

func (t SagaFailed) FailedIndex() StepIndex { return t.failedIndex }

func (t SagaFailed) CompletedBefore() float64 { return t.completedBefore }


// --- CompensationOrdered ---
// Shen: (datatype compensation-ordered)
type CompensationOrdered struct {
	later StepCompensated
	earlier StepCompensated
}

func NewCompensationOrdered(later StepCompensated, earlier StepCompensated) (CompensationOrdered, error) {
	if !(later.completed.index.Val() > earlier.completed.index.Val()) {
		return CompensationOrdered{}, fmt.Errorf("later.completed.index must be > earlier.completed.index")
	}
	return CompensationOrdered{
		later: later,
		earlier: earlier,
	}, nil
}

func (t CompensationOrdered) Later() StepCompensated { return t.later }

func (t CompensationOrdered) Earlier() StepCompensated { return t.earlier }


// --- SagaRolledBack ---
// Shen: (datatype saga-rolled-back)
type SagaRolledBack struct {
	failed SagaFailed
	compensationCount float64
}

func NewSagaRolledBack(failed SagaFailed, compensationCount float64) (SagaRolledBack, error) {
	if !(/* TODO: (= CompensationCount (head (tail (tail (tail Failed))))) */ true) {
		return SagaRolledBack{}, fmt.Errorf("could not resolve equality")
	}
	return SagaRolledBack{
		failed: failed,
		compensationCount: compensationCount,
	}, nil
}

func (t SagaRolledBack) Failed() SagaFailed { return t.failed }

func (t SagaRolledBack) CompensationCount() float64 { return t.compensationCount }


// --- IdempotencyKey ---
// Shen: (datatype idempotency-key)
type IdempotencyKey struct{ v string }

func NewIdempotencyKey(x string) (IdempotencyKey, error) {
	if !(!(x == "")) {
		return IdempotencyKey{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return IdempotencyKey{v: x}, nil
}

func (t IdempotencyKey) Val() string { return t.v }


// --- StepIdempotent ---
// Shen: (datatype step-idempotent)
type StepIdempotent struct {
	key IdempotencyKey
	step StepName
	saga SagaId
}

func NewStepIdempotent(key IdempotencyKey, step StepName, saga SagaId) StepIdempotent {
	return StepIdempotent{
		key: key,
		step: step,
		saga: saga,
	}
}

func (t StepIdempotent) Key() IdempotencyKey { return t.key }

func (t StepIdempotent) Step() StepName { return t.step }

func (t StepIdempotent) Saga() SagaId { return t.saga }


// --- Deadline ---
// Shen: (datatype deadline)
type Deadline struct{ v float64 }

func NewDeadline(x float64) (Deadline, error) {
	if !(x > 0) {
		return Deadline{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return Deadline{v: x}, nil
}

func (t Deadline) Val() float64 { return t.v }


// --- WithinDeadline ---
// Shen: (datatype within-deadline)
type WithinDeadline struct {
	startedAt float64
	completedAt float64
	deadline Deadline
}

func NewWithinDeadline(startedAt float64, completedAt float64, deadline Deadline) (WithinDeadline, error) {
	if !(startedAt > 0) {
		return WithinDeadline{}, fmt.Errorf("startedAt must be > 0")
	}
	if !(completedAt > startedAt) {
		return WithinDeadline{}, fmt.Errorf("completedAt must be > startedAt")
	}
	if !(/* TODO: (<= (- CompletedAt StartedAt) Deadline) */ true) {
		return WithinDeadline{}, fmt.Errorf("could not resolve comparison")
	}
	return WithinDeadline{
		startedAt: startedAt,
		completedAt: completedAt,
		deadline: deadline,
	}, nil
}

func (t WithinDeadline) StartedAt() float64 { return t.startedAt }

func (t WithinDeadline) CompletedAt() float64 { return t.completedAt }

func (t WithinDeadline) Deadline() Deadline { return t.deadline }


