# Code generated by shengen-py from specs/core.shen. DO NOT EDIT.
#
# These types enforce Shen sequent-calculus invariants at the Python level.
# Factory functions are the ONLY way to create these types — bypassing them
# is a violation of the formal spec.

from __future__ import annotations

from dataclasses import dataclass


# --- CustomerId ---
# Shen: (datatype customer-id)
@dataclass(frozen=True, slots=True)
class CustomerId:
    _v: str

    def val(self) -> str:
        return self._v

def new_customer_id(x: str) -> CustomerId:
    return CustomerId(_v=x)


# --- Sku ---
# Shen: (datatype sku)
@dataclass(frozen=True, slots=True)
class Sku:
    _v: str

    def val(self) -> str:
        return self._v

def new_sku(x: str) -> Sku:
    return Sku(_v=x)


# --- CartItem ---
# Shen: (datatype cart-item)
@dataclass(frozen=True, slots=True)
class CartItem:
    _sku: Sku
    _qty: float

    def __post_init__(self) -> None:
        if not (self._qty >= 1):
            raise ValueError("qty must be >= 1")

    def sku(self) -> Sku:
        return self._sku

    def qty(self) -> float:
        return self._qty


def new_cart_item(sku: Sku, qty: float) -> CartItem:
    if not isinstance(sku, Sku):
        raise TypeError(f"sku must be Sku, got {type(sku).__name__}")
    return CartItem(_sku=sku, _qty=qty)


# --- Cart ---
# Shen: (datatype cart)
@dataclass(frozen=True, slots=True)
class Cart:
    _subtotal: float
    _customer: CustomerId
    _items: list[CartItem]

    def __post_init__(self) -> None:
        if not (self._subtotal >= 0):
            raise ValueError("subtotal must be >= 0")

    def subtotal(self) -> float:
        return self._subtotal

    def customer(self) -> CustomerId:
        return self._customer

    def items(self) -> list[CartItem]:
        return self._items


def new_cart(subtotal: float, customer: CustomerId, items: list[CartItem]) -> Cart:
    if not isinstance(customer, CustomerId):
        raise TypeError(f"customer must be CustomerId, got {type(customer).__name__}")
    return Cart(_subtotal=subtotal, _customer=customer, _items=items)


# --- DiscountEligible ---
# Shen: (datatype discount-eligible)
@dataclass(frozen=True, slots=True)
class DiscountEligible:
    _cart: Cart
    _item_count: float
    _min_subtotal: float
    _min_items: float

    def __post_init__(self) -> None:
        if not (self._cart.subtotal() >= self._min_subtotal):
            raise ValueError("cart.subtotal() must be >= min_subtotal")
        if not (self._item_count >= self._min_items):
            raise ValueError("item_count must be >= min_items")

    def cart(self) -> Cart:
        return self._cart

    def item_count(self) -> float:
        return self._item_count

    def min_subtotal(self) -> float:
        return self._min_subtotal

    def min_items(self) -> float:
        return self._min_items


def new_discount_eligible(cart: Cart, item_count: float, min_subtotal: float, min_items: float) -> DiscountEligible:
    if not isinstance(cart, Cart):
        raise TypeError(f"cart must be Cart, got {type(cart).__name__}")
    return DiscountEligible(_cart=cart, _item_count=item_count, _min_subtotal=min_subtotal, _min_items=min_items)



# --- Pure functions translated from (define …) blocks ---
#
# Only defines that recurse over a single list parameter are emitted.
# Anything richer (multi-list recursion, non-list pattern matching,
# arithmetic-heavy bodies) is flagged below and left for a future
# emitter pass — the Python emitter prefers a clear gap to a quietly
# corrupted helper.

def has_bulk_line(cart_items: list[CartItem]) -> bool:
    """Generated from Shen define has-bulk-line?."""
    for elem in cart_items:
        if elem.qty() >= 5.0:
            return True
    return False
