"""CLI for the multilang-paired demo (Python implementation).

Reads JSONL from stdin, emits JSON-per-line to stdout. Same I/O shape
as `go/main.go`, `ts/main.ts`, `rs/main.rs`. Run with:

    python3 py/main.py < fixture-inputs.jsonl

Unlike the TS CLI (which falls back to an inline helper because of a
known emitter parser bug), the Py CLI calls the generated
`has_bulk_line(…)` from `guards_gen.py` directly. The W2.2 Py emitter
correctly lowers `[[Sku Qty] | Rest] -> true where (>= Qty 5)` into
the expected for-loop body.
"""
from __future__ import annotations

import json
import sys
from typing import Any

# guards_gen.py is generated by `bin/codegen-py.sh` from specs/core.shen.
# Import from the sibling module.
import os
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import guards_gen as gg  # type: ignore[import-not-found]


def process_row(row: dict[str, Any]) -> dict[str, Any]:
    case_id = row["caseId"]
    out: dict[str, Any] = {
        "caseId": case_id,
        "ok": False,
        "outcome": "",
        "itemCount": len(row["items"]),
        "hasBulkLine": False,
    }

    # Build CartItems (verified premise: qty >= 1).
    items = []
    for it in row["items"]:
        try:
            ci = gg.new_cart_item(gg.new_sku(it["sku"]), float(it["qty"]))
        except (ValueError, TypeError):
            out["outcome"] = "rejected-item-build"
            return out
        items.append(ci)

    # Build Cart (verified premise: subtotal >= 0).
    try:
        cart = gg.new_cart(
            float(row["subtotal"]),
            gg.new_customer_id(row["customerId"]),
            items,
        )
    except (ValueError, TypeError):
        out["outcome"] = "rejected-cart-build"
        return out

    # Use the GENERATED helper — W2.2 brings the Py emitter into parity
    # on (define …) blocks with `[]` base + guarded recursive step.
    out["hasBulkLine"] = gg.has_bulk_line(items)

    # Build DiscountEligible (cross-field premises:
    #   subtotal >= min_subtotal, item_count >= min_items).
    try:
        gg.new_discount_eligible(
            cart,
            float(len(items)),
            float(row["minSubtotal"]),
            float(row["minItems"]),
        )
    except (ValueError, TypeError):
        if not (float(row["subtotal"]) >= float(row["minSubtotal"])):
            out["outcome"] = "rejected-subtotal"
        else:
            out["outcome"] = "rejected-items"
        return out

    out["ok"] = True
    out["outcome"] = "eligible"
    return out


def main() -> None:
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            sys.stderr.write(f"py: invalid input line {line!r}: {exc}\n")
            sys.exit(1)
        out = process_row(row)
        sys.stdout.write(json.dumps(out, separators=(",", ":")) + "\n")


if __name__ == "__main__":
    main()
