// Code generated by shengen from demo/defi-invariants/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- TransferAuth (sum type) ---
// Multiple Shen datatype blocks produce this type.
// Variants: owner-authorized, spender-authorized
type TransferAuth interface {
	isTransferAuth()
}

// --- Address ---
// Shen: (datatype address)
type Address struct{ v string }

func NewAddress(x string) (Address, error) {
	if !(!(x == "")) {
		return Address{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return Address{v: x}, nil
}

func (t Address) Val() string { return t.v }


// --- TokenSymbol ---
// Shen: (datatype token-symbol)
type TokenSymbol struct{ v string }

func NewTokenSymbol(x string) (TokenSymbol, error) {
	if !(!(x == "")) {
		return TokenSymbol{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return TokenSymbol{v: x}, nil
}

func (t TokenSymbol) Val() string { return t.v }


// --- TokenAmount ---
// Shen: (datatype token-amount)
type TokenAmount struct{ v float64 }

func NewTokenAmount(x float64) (TokenAmount, error) {
	if !(x >= 0) {
		return TokenAmount{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return TokenAmount{v: x}, nil
}

func (t TokenAmount) Val() float64 { return t.v }


// --- BlockNumber ---
// Shen: (datatype block-number)
type BlockNumber struct{ v float64 }

func NewBlockNumber(x float64) (BlockNumber, error) {
	if !(x > 0) {
		return BlockNumber{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return BlockNumber{v: x}, nil
}

func (t BlockNumber) Val() float64 { return t.v }


// --- Nonce ---
// Shen: (datatype nonce)
type Nonce struct{ v float64 }

func NewNonce(x float64) (Nonce, error) {
	if !(x >= 0) {
		return Nonce{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return Nonce{v: x}, nil
}

func (t Nonce) Val() float64 { return t.v }


// --- TokenBalance ---
// Shen: (datatype token-balance)
type TokenBalance struct {
	owner Address
	token TokenSymbol
	amount TokenAmount
}

func NewTokenBalance(owner Address, token TokenSymbol, amount TokenAmount) TokenBalance {
	return TokenBalance{
		owner: owner,
		token: token,
		amount: amount,
	}
}

func (t TokenBalance) Owner() Address { return t.owner }

func (t TokenBalance) Token() TokenSymbol { return t.token }

func (t TokenBalance) Amount() TokenAmount { return t.amount }


// --- TotalSupply ---
// Shen: (datatype total-supply)
type TotalSupply struct {
	token TokenSymbol
	supply TokenAmount
}

func NewTotalSupply(token TokenSymbol, supply TokenAmount) TotalSupply {
	return TotalSupply{
		token: token,
		supply: supply,
	}
}

func (t TotalSupply) Token() TokenSymbol { return t.token }

func (t TotalSupply) Supply() TokenAmount { return t.supply }


// --- TotalMinted ---
// Shen: (datatype total-minted)
type TotalMinted struct {
	token TokenSymbol
	minted TokenAmount
}

func NewTotalMinted(token TokenSymbol, minted TokenAmount) TotalMinted {
	return TotalMinted{
		token: token,
		minted: minted,
	}
}

func (t TotalMinted) Token() TokenSymbol { return t.token }

func (t TotalMinted) Minted() TokenAmount { return t.minted }


// --- TotalBurned ---
// Shen: (datatype total-burned)
type TotalBurned struct {
	token TokenSymbol
	burned TokenAmount
}

func NewTotalBurned(token TokenSymbol, burned TokenAmount) TotalBurned {
	return TotalBurned{
		token: token,
		burned: burned,
	}
}

func (t TotalBurned) Token() TokenSymbol { return t.token }

func (t TotalBurned) Burned() TokenAmount { return t.burned }


// --- SupplyConserved ---
// Shen: (datatype supply-conserved)
type SupplyConserved struct {
	supply TotalSupply
	minted TotalMinted
	burned TotalBurned
}

func NewSupplyConserved(supply TotalSupply, minted TotalMinted, burned TotalBurned) (SupplyConserved, error) {
	if !(/* TODO: (= (head (tail Supply)) (- (head (tail Minted)) (head (tail Burned)))) */ true) {
		return SupplyConserved{}, fmt.Errorf("could not resolve equality")
	}
	return SupplyConserved{
		supply: supply,
		minted: minted,
		burned: burned,
	}, nil
}

func (t SupplyConserved) Supply() TotalSupply { return t.supply }

func (t SupplyConserved) Minted() TotalMinted { return t.minted }

func (t SupplyConserved) Burned() TotalBurned { return t.burned }


// --- SufficientBalance ---
// Shen: (datatype sufficient-balance)
type SufficientBalance struct {
	balance TokenBalance
	amount TokenAmount
}

func NewSufficientBalance(balance TokenBalance, amount TokenAmount) (SufficientBalance, error) {
	if !(/* TODO: (>= (head (tail (tail Balance))) Amount) */ true) {
		return SufficientBalance{}, fmt.Errorf("could not resolve comparison")
	}
	return SufficientBalance{
		balance: balance,
		amount: amount,
	}, nil
}

func (t SufficientBalance) Balance() TokenBalance { return t.balance }

func (t SufficientBalance) Amount() TokenAmount { return t.amount }


// --- ValuePreserved ---
// Shen: (datatype value-preserved)
type ValuePreserved struct {
	senderBefore TokenAmount
	senderAfter TokenAmount
	receiverBefore TokenAmount
	receiverAfter TokenAmount
}

func NewValuePreserved(senderBefore TokenAmount, senderAfter TokenAmount, receiverBefore TokenAmount, receiverAfter TokenAmount) (ValuePreserved, error) {
	if !(/* TODO: (= (+ SenderBefore ReceiverBefore) (+ SenderAfter ReceiverAfter)) */ true) {
		return ValuePreserved{}, fmt.Errorf("could not resolve equality")
	}
	return ValuePreserved{
		senderBefore: senderBefore,
		senderAfter: senderAfter,
		receiverBefore: receiverBefore,
		receiverAfter: receiverAfter,
	}, nil
}

func (t ValuePreserved) SenderBefore() TokenAmount { return t.senderBefore }

func (t ValuePreserved) SenderAfter() TokenAmount { return t.senderAfter }

func (t ValuePreserved) ReceiverBefore() TokenAmount { return t.receiverBefore }

func (t ValuePreserved) ReceiverAfter() TokenAmount { return t.receiverAfter }


// --- ValidTransfer ---
// Shen: (datatype valid-transfer)
type ValidTransfer struct {
	from Address
	to Address
	token TokenSymbol
	amount TokenAmount
	balanceProof SufficientBalance
	valueProof ValuePreserved
}

func NewValidTransfer(from Address, to Address, token TokenSymbol, amount TokenAmount, balanceProof SufficientBalance, valueProof ValuePreserved) ValidTransfer {
	return ValidTransfer{
		from: from,
		to: to,
		token: token,
		amount: amount,
		balanceProof: balanceProof,
		valueProof: valueProof,
	}
}

func (t ValidTransfer) From() Address { return t.from }

func (t ValidTransfer) To() Address { return t.to }

func (t ValidTransfer) Token() TokenSymbol { return t.token }

func (t ValidTransfer) Amount() TokenAmount { return t.amount }

func (t ValidTransfer) BalanceProof() SufficientBalance { return t.balanceProof }

func (t ValidTransfer) ValueProof() ValuePreserved { return t.valueProof }


// --- TransferAuthorized ---
// Shen: (datatype transfer-authorized)
type TransferAuthorized struct {
	caller Address
	owner Address
}

func NewTransferAuthorized(caller Address, owner Address) (TransferAuthorized, error) {
	if !(caller == owner) {
		return TransferAuthorized{}, fmt.Errorf("caller must equal owner")
	}
	return TransferAuthorized{
		caller: caller,
		owner: owner,
	}, nil
}

func (t TransferAuthorized) Caller() Address { return t.caller }

func (t TransferAuthorized) Owner() Address { return t.owner }


// --- Allowance ---
// Shen: (datatype allowance)
type Allowance struct {
	owner Address
	spender Address
	token TokenSymbol
	limit TokenAmount
}

func NewAllowance(owner Address, spender Address, token TokenSymbol, limit TokenAmount) Allowance {
	return Allowance{
		owner: owner,
		spender: spender,
		token: token,
		limit: limit,
	}
}

func (t Allowance) Owner() Address { return t.owner }

func (t Allowance) Spender() Address { return t.spender }

func (t Allowance) Token() TokenSymbol { return t.token }

func (t Allowance) Limit() TokenAmount { return t.limit }


// --- WithinAllowance ---
// Shen: (datatype within-allowance)
type WithinAllowance struct {
	allow Allowance
	amount TokenAmount
}

func NewWithinAllowance(allow Allowance, amount TokenAmount) (WithinAllowance, error) {
	if !(/* TODO: (>= (head (tail (tail (tail Allow)))) Amount) */ true) {
		return WithinAllowance{}, fmt.Errorf("could not resolve comparison")
	}
	return WithinAllowance{
		allow: allow,
		amount: amount,
	}, nil
}

func (t WithinAllowance) Allow() Allowance { return t.allow }

func (t WithinAllowance) Amount() TokenAmount { return t.amount }


// --- OwnerAuthorized ---
// Shen: (datatype owner-authorized)
type OwnerAuthorized struct {
	auth TransferAuthorized
}

func NewOwnerAuthorized(auth TransferAuthorized) OwnerAuthorized {
	return OwnerAuthorized{
		auth: auth,
	}
}

func (t OwnerAuthorized) Auth() TransferAuthorized { return t.auth }

func (t OwnerAuthorized) isTransferAuth() {}


// --- SpenderAuthorized ---
// Shen: (datatype spender-authorized)
type SpenderAuthorized struct {
	allow WithinAllowance
}

func NewSpenderAuthorized(allow WithinAllowance) SpenderAuthorized {
	return SpenderAuthorized{
		allow: allow,
	}
}

func (t SpenderAuthorized) Allow() WithinAllowance { return t.allow }

func (t SpenderAuthorized) isTransferAuth() {}


// --- PoolId ---
// Shen: (datatype pool-id)
type PoolId struct{ v string }

func NewPoolId(x string) (PoolId, error) {
	if !(!(x == "")) {
		return PoolId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return PoolId{v: x}, nil
}

func (t PoolId) Val() string { return t.v }


// --- PoolReserve ---
// Shen: (datatype pool-reserve)
type PoolReserve struct {
	pool PoolId
	tokenA TokenSymbol
	tokenB TokenSymbol
	reserveA TokenAmount
	reserveB TokenAmount
}

func NewPoolReserve(pool PoolId, tokenA TokenSymbol, tokenB TokenSymbol, reserveA TokenAmount, reserveB TokenAmount) (PoolReserve, error) {
	if !(reserveA.Val() > 0) {
		return PoolReserve{}, fmt.Errorf("reserveA must be > 0")
	}
	if !(reserveB.Val() > 0) {
		return PoolReserve{}, fmt.Errorf("reserveB must be > 0")
	}
	return PoolReserve{
		pool: pool,
		tokenA: tokenA,
		tokenB: tokenB,
		reserveA: reserveA,
		reserveB: reserveB,
	}, nil
}

func (t PoolReserve) Pool() PoolId { return t.pool }

func (t PoolReserve) TokenA() TokenSymbol { return t.tokenA }

func (t PoolReserve) TokenB() TokenSymbol { return t.tokenB }

func (t PoolReserve) ReserveA() TokenAmount { return t.reserveA }

func (t PoolReserve) ReserveB() TokenAmount { return t.reserveB }


// --- ConstantProduct ---
// Shen: (datatype constant-product)
type ConstantProduct struct {
	reserve PoolReserve
	k float64
}

func NewConstantProduct(reserve PoolReserve, k float64) (ConstantProduct, error) {
	if !(/* TODO: (= K (* (head (tail (tail (tail Reserve)))) (head (tail (tail (tail (tail Reserve))))))) */ true) {
		return ConstantProduct{}, fmt.Errorf("could not resolve equality")
	}
	if !(k > 0) {
		return ConstantProduct{}, fmt.Errorf("k must be > 0")
	}
	return ConstantProduct{
		reserve: reserve,
		k: k,
	}, nil
}

func (t ConstantProduct) Reserve() PoolReserve { return t.reserve }

func (t ConstantProduct) K() float64 { return t.k }


// --- SwapValid ---
// Shen: (datatype swap-valid)
type SwapValid struct {
	poolBefore ConstantProduct
	poolAfter ConstantProduct
}

func NewSwapValid(poolBefore ConstantProduct, poolAfter ConstantProduct) (SwapValid, error) {
	if !(/* TODO: (>= (head (tail PoolAfter)) (head (tail PoolBefore))) */ true) {
		return SwapValid{}, fmt.Errorf("could not resolve comparison")
	}
	return SwapValid{
		poolBefore: poolBefore,
		poolAfter: poolAfter,
	}, nil
}

func (t SwapValid) PoolBefore() ConstantProduct { return t.poolBefore }

func (t SwapValid) PoolAfter() ConstantProduct { return t.poolAfter }


// --- SlippageBound ---
// Shen: (datatype slippage-bound)
type SlippageBound struct {
	minOutput TokenAmount
	actualOutput TokenAmount
}

func NewSlippageBound(minOutput TokenAmount, actualOutput TokenAmount) (SlippageBound, error) {
	if !(actualOutput.Val() >= minOutput.Val()) {
		return SlippageBound{}, fmt.Errorf("actualOutput must be >= minOutput")
	}
	return SlippageBound{
		minOutput: minOutput,
		actualOutput: actualOutput,
	}, nil
}

func (t SlippageBound) MinOutput() TokenAmount { return t.minOutput }

func (t SlippageBound) ActualOutput() TokenAmount { return t.actualOutput }


// --- SafeSwap ---
// Shen: (datatype safe-swap)
type SafeSwap struct {
	swap SwapValid
	slippage SlippageBound
	auth TransferAuth
}

func NewSafeSwap(swap SwapValid, slippage SlippageBound, auth TransferAuth) SafeSwap {
	return SafeSwap{
		swap: swap,
		slippage: slippage,
		auth: auth,
	}
}

func (t SafeSwap) Swap() SwapValid { return t.swap }

func (t SafeSwap) Slippage() SlippageBound { return t.slippage }

func (t SafeSwap) Auth() TransferAuth { return t.auth }


// --- LpTokenBalance ---
// Shen: (datatype lp-token-balance)
type LpTokenBalance struct {
	owner Address
	pool PoolId
	shares TokenAmount
}

func NewLpTokenBalance(owner Address, pool PoolId, shares TokenAmount) LpTokenBalance {
	return LpTokenBalance{
		owner: owner,
		pool: pool,
		shares: shares,
	}
}

func (t LpTokenBalance) Owner() Address { return t.owner }

func (t LpTokenBalance) Pool() PoolId { return t.pool }

func (t LpTokenBalance) Shares() TokenAmount { return t.shares }


// --- TotalLpSupply ---
// Shen: (datatype total-lp-supply)
type TotalLpSupply struct {
	pool PoolId
	totalShares TokenAmount
}

func NewTotalLpSupply(pool PoolId, totalShares TokenAmount) (TotalLpSupply, error) {
	if !(totalShares.Val() > 0) {
		return TotalLpSupply{}, fmt.Errorf("totalShares must be > 0")
	}
	return TotalLpSupply{
		pool: pool,
		totalShares: totalShares,
	}, nil
}

func (t TotalLpSupply) Pool() PoolId { return t.pool }

func (t TotalLpSupply) TotalShares() TokenAmount { return t.totalShares }


// --- ProportionalDeposit ---
// Shen: (datatype proportional-deposit)
type ProportionalDeposit struct {
	amountA TokenAmount
	amountB TokenAmount
	reserve PoolReserve
}

func NewProportionalDeposit(amountA TokenAmount, amountB TokenAmount, reserve PoolReserve) (ProportionalDeposit, error) {
	if !(amountA.Val() > 0) {
		return ProportionalDeposit{}, fmt.Errorf("amountA must be > 0")
	}
	if !(amountB.Val() > 0) {
		return ProportionalDeposit{}, fmt.Errorf("amountB must be > 0")
	}
	return ProportionalDeposit{
		amountA: amountA,
		amountB: amountB,
		reserve: reserve,
	}, nil
}

func (t ProportionalDeposit) AmountA() TokenAmount { return t.amountA }

func (t ProportionalDeposit) AmountB() TokenAmount { return t.amountB }

func (t ProportionalDeposit) Reserve() PoolReserve { return t.reserve }


// --- WithdrawalSolvent ---
// Shen: (datatype withdrawal-solvent)
type WithdrawalSolvent struct {
	shares TokenAmount
	totalShares TotalLpSupply
	reserve PoolReserve
}

func NewWithdrawalSolvent(shares TokenAmount, totalShares TotalLpSupply, reserve PoolReserve) (WithdrawalSolvent, error) {
	if !(shares.Val() > 0) {
		return WithdrawalSolvent{}, fmt.Errorf("shares must be > 0")
	}
	if !(/* TODO: (<= Shares (head (tail TotalShares))) */ true) {
		return WithdrawalSolvent{}, fmt.Errorf("could not resolve comparison")
	}
	return WithdrawalSolvent{
		shares: shares,
		totalShares: totalShares,
		reserve: reserve,
	}, nil
}

func (t WithdrawalSolvent) Shares() TokenAmount { return t.shares }

func (t WithdrawalSolvent) TotalShares() TotalLpSupply { return t.totalShares }

func (t WithdrawalSolvent) Reserve() PoolReserve { return t.reserve }


// --- SafeWithdrawal ---
// Shen: (datatype safe-withdrawal)
type SafeWithdrawal struct {
	solvency WithdrawalSolvent
	auth TransferAuth
}

func NewSafeWithdrawal(solvency WithdrawalSolvent, auth TransferAuth) SafeWithdrawal {
	return SafeWithdrawal{
		solvency: solvency,
		auth: auth,
	}
}

func (t SafeWithdrawal) Solvency() WithdrawalSolvent { return t.solvency }

func (t SafeWithdrawal) Auth() TransferAuth { return t.auth }


// --- MutexState ---
// Shen: (datatype mutex-state)
type MutexState struct{ v string }

func NewMutexState(x string) (MutexState, error) {
	if !(map[string]bool{"unlocked": true, "locked": true}[x]) {
		return MutexState{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return MutexState{v: x}, nil
}

func (t MutexState) Val() string { return t.v }


// --- MutexAvailable ---
// Shen: (datatype mutex-available)
type MutexAvailable = MutexState


// --- StateCommitted ---
// Shen: (datatype state-committed)
type StateCommitted struct {
	block BlockNumber
	nonce Nonce
}

func NewStateCommitted(block BlockNumber, nonce Nonce) StateCommitted {
	return StateCommitted{
		block: block,
		nonce: nonce,
	}
}

func (t StateCommitted) Block() BlockNumber { return t.block }

func (t StateCommitted) Nonce() Nonce { return t.nonce }


// --- SafeInteraction ---
// Shen: (datatype safe-interaction)
type SafeInteraction struct {
	mutex MutexAvailable
	committed StateCommitted
}

func NewSafeInteraction(mutex MutexAvailable, committed StateCommitted) SafeInteraction {
	return SafeInteraction{
		mutex: mutex,
		committed: committed,
	}
}

func (t SafeInteraction) Mutex() MutexAvailable { return t.mutex }

func (t SafeInteraction) Committed() StateCommitted { return t.committed }


// --- FlashLoanAmount ---
// Shen: (datatype flash-loan-amount)
type FlashLoanAmount struct {
	token TokenSymbol
	borrowed TokenAmount
	fee TokenAmount
}

func NewFlashLoanAmount(token TokenSymbol, borrowed TokenAmount, fee TokenAmount) (FlashLoanAmount, error) {
	if !(borrowed.Val() > 0) {
		return FlashLoanAmount{}, fmt.Errorf("borrowed must be > 0")
	}
	if !(fee.Val() >= 0) {
		return FlashLoanAmount{}, fmt.Errorf("fee must be >= 0")
	}
	return FlashLoanAmount{
		token: token,
		borrowed: borrowed,
		fee: fee,
	}, nil
}

func (t FlashLoanAmount) Token() TokenSymbol { return t.token }

func (t FlashLoanAmount) Borrowed() TokenAmount { return t.borrowed }

func (t FlashLoanAmount) Fee() TokenAmount { return t.fee }


// --- FlashLoanRepaid ---
// Shen: (datatype flash-loan-repaid)
type FlashLoanRepaid struct {
	loan FlashLoanAmount
	repaid TokenAmount
}

func NewFlashLoanRepaid(loan FlashLoanAmount, repaid TokenAmount) (FlashLoanRepaid, error) {
	if !(/* TODO: (>= Repaid (+ (head (tail Loan)) (head (tail (tail Loan))))) */ true) {
		return FlashLoanRepaid{}, fmt.Errorf("could not resolve comparison")
	}
	return FlashLoanRepaid{
		loan: loan,
		repaid: repaid,
	}, nil
}

func (t FlashLoanRepaid) Loan() FlashLoanAmount { return t.loan }

func (t FlashLoanRepaid) Repaid() TokenAmount { return t.repaid }


// --- FlashLoanComplete ---
// Shen: (datatype flash-loan-complete)
type FlashLoanComplete struct {
	repayment FlashLoanRepaid
	borrowBlock BlockNumber
	repayBlock BlockNumber
}

func NewFlashLoanComplete(repayment FlashLoanRepaid, borrowBlock BlockNumber, repayBlock BlockNumber) (FlashLoanComplete, error) {
	if !(borrowBlock == repayBlock) {
		return FlashLoanComplete{}, fmt.Errorf("borrowBlock must equal repayBlock")
	}
	return FlashLoanComplete{
		repayment: repayment,
		borrowBlock: borrowBlock,
		repayBlock: repayBlock,
	}, nil
}

func (t FlashLoanComplete) Repayment() FlashLoanRepaid { return t.repayment }

func (t FlashLoanComplete) BorrowBlock() BlockNumber { return t.borrowBlock }

func (t FlashLoanComplete) RepayBlock() BlockNumber { return t.repayBlock }


// --- TimelockDelay ---
// Shen: (datatype timelock-delay)
type TimelockDelay struct{ v float64 }

func NewTimelockDelay(x float64) (TimelockDelay, error) {
	if !(x > 0) {
		return TimelockDelay{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return TimelockDelay{v: x}, nil
}

func (t TimelockDelay) Val() float64 { return t.v }


// --- GovernanceProposal ---
// Shen: (datatype governance-proposal)
type GovernanceProposal struct {
	id string
	proposer Address
	action string
	proposedAt BlockNumber
}

func NewGovernanceProposal(id string, proposer Address, action string, proposedAt BlockNumber) (GovernanceProposal, error) {
	if !(!(id == "")) {
		return GovernanceProposal{}, fmt.Errorf("not: id must equal \"\"")
	}
	if !(!(action == "")) {
		return GovernanceProposal{}, fmt.Errorf("not: action must equal \"\"")
	}
	return GovernanceProposal{
		id: id,
		proposer: proposer,
		action: action,
		proposedAt: proposedAt,
	}, nil
}

func (t GovernanceProposal) Id() string { return t.id }

func (t GovernanceProposal) Proposer() Address { return t.proposer }

func (t GovernanceProposal) Action() string { return t.action }

func (t GovernanceProposal) ProposedAt() BlockNumber { return t.proposedAt }


// --- TimelockElapsed ---
// Shen: (datatype timelock-elapsed)
type TimelockElapsed struct {
	proposal GovernanceProposal
	delay TimelockDelay
	currentBlock BlockNumber
}

func NewTimelockElapsed(proposal GovernanceProposal, delay TimelockDelay, currentBlock BlockNumber) (TimelockElapsed, error) {
	if !(/* TODO: (>= CurrentBlock (+ (head (tail (tail (tail Proposal)))) Delay)) */ true) {
		return TimelockElapsed{}, fmt.Errorf("could not resolve comparison")
	}
	return TimelockElapsed{
		proposal: proposal,
		delay: delay,
		currentBlock: currentBlock,
	}, nil
}

func (t TimelockElapsed) Proposal() GovernanceProposal { return t.proposal }

func (t TimelockElapsed) Delay() TimelockDelay { return t.delay }

func (t TimelockElapsed) CurrentBlock() BlockNumber { return t.currentBlock }


// --- GovernanceExecutable ---
// Shen: (datatype governance-executable)
type GovernanceExecutable struct {
	timelock TimelockElapsed
	approvalCount float64
	requiredApprovals float64
}

func NewGovernanceExecutable(timelock TimelockElapsed, approvalCount float64, requiredApprovals float64) (GovernanceExecutable, error) {
	if !(approvalCount >= requiredApprovals) {
		return GovernanceExecutable{}, fmt.Errorf("approvalCount must be >= requiredApprovals")
	}
	if !(requiredApprovals > 0) {
		return GovernanceExecutable{}, fmt.Errorf("requiredApprovals must be > 0")
	}
	return GovernanceExecutable{
		timelock: timelock,
		approvalCount: approvalCount,
		requiredApprovals: requiredApprovals,
	}, nil
}

func (t GovernanceExecutable) Timelock() TimelockElapsed { return t.timelock }

func (t GovernanceExecutable) ApprovalCount() float64 { return t.approvalCount }

func (t GovernanceExecutable) RequiredApprovals() float64 { return t.requiredApprovals }


// --- OracleSource ---
// Shen: (datatype oracle-source)
type OracleSource struct{ v string }

func NewOracleSource(x string) (OracleSource, error) {
	if !(!(x == "")) {
		return OracleSource{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return OracleSource{v: x}, nil
}

func (t OracleSource) Val() string { return t.v }


// --- PriceValue ---
// Shen: (datatype price-value)
type PriceValue struct{ v float64 }

func NewPriceValue(x float64) (PriceValue, error) {
	if !(x > 0) {
		return PriceValue{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return PriceValue{v: x}, nil
}

func (t PriceValue) Val() float64 { return t.v }


// --- MaxStaleness ---
// Shen: (datatype max-staleness)
type MaxStaleness struct{ v float64 }

func NewMaxStaleness(x float64) (MaxStaleness, error) {
	if !(x > 0) {
		return MaxStaleness{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return MaxStaleness{v: x}, nil
}

func (t MaxStaleness) Val() float64 { return t.v }


// --- PriceFeed ---
// Shen: (datatype price-feed)
type PriceFeed struct {
	source OracleSource
	price PriceValue
	updatedAt BlockNumber
}

func NewPriceFeed(source OracleSource, price PriceValue, updatedAt BlockNumber) PriceFeed {
	return PriceFeed{
		source: source,
		price: price,
		updatedAt: updatedAt,
	}
}

func (t PriceFeed) Source() OracleSource { return t.source }

func (t PriceFeed) Price() PriceValue { return t.price }

func (t PriceFeed) UpdatedAt() BlockNumber { return t.updatedAt }


// --- PriceFresh ---
// Shen: (datatype price-fresh)
type PriceFresh struct {
	feed PriceFeed
	currentBlock BlockNumber
	maxStale MaxStaleness
}

func NewPriceFresh(feed PriceFeed, currentBlock BlockNumber, maxStale MaxStaleness) (PriceFresh, error) {
	if !(/* TODO: (<= (- CurrentBlock (head (tail (tail Feed)))) MaxStale) */ true) {
		return PriceFresh{}, fmt.Errorf("could not resolve comparison")
	}
	return PriceFresh{
		feed: feed,
		currentBlock: currentBlock,
		maxStale: maxStale,
	}, nil
}

func (t PriceFresh) Feed() PriceFeed { return t.feed }

func (t PriceFresh) CurrentBlock() BlockNumber { return t.currentBlock }

func (t PriceFresh) MaxStale() MaxStaleness { return t.maxStale }


// --- OracleAgreement ---
// Shen: (datatype oracle-agreement)
type OracleAgreement struct {
	feedA PriceFresh
	feedB PriceFresh
	maxDeviation float64
	deviation float64
}

func NewOracleAgreement(feedA PriceFresh, feedB PriceFresh, maxDeviation float64, deviation float64) (OracleAgreement, error) {
	if !(maxDeviation > 0) {
		return OracleAgreement{}, fmt.Errorf("maxDeviation must be > 0")
	}
	if !(deviation >= 0) {
		return OracleAgreement{}, fmt.Errorf("deviation must be >= 0")
	}
	if !(deviation <= maxDeviation) {
		return OracleAgreement{}, fmt.Errorf("deviation must be <= maxDeviation")
	}
	return OracleAgreement{
		feedA: feedA,
		feedB: feedB,
		maxDeviation: maxDeviation,
		deviation: deviation,
	}, nil
}

func (t OracleAgreement) FeedA() PriceFresh { return t.feedA }

func (t OracleAgreement) FeedB() PriceFresh { return t.feedB }

func (t OracleAgreement) MaxDeviation() float64 { return t.maxDeviation }

func (t OracleAgreement) Deviation() float64 { return t.deviation }


// --- ProtocolOperationSafe ---
// Shen: (datatype protocol-operation-safe)
type ProtocolOperationSafe struct {
	transfer ValidTransfer
	conservation SupplyConserved
	reentrancy SafeInteraction
}

func NewProtocolOperationSafe(transfer ValidTransfer, conservation SupplyConserved, reentrancy SafeInteraction) ProtocolOperationSafe {
	return ProtocolOperationSafe{
		transfer: transfer,
		conservation: conservation,
		reentrancy: reentrancy,
	}
}

func (t ProtocolOperationSafe) Transfer() ValidTransfer { return t.transfer }

func (t ProtocolOperationSafe) Conservation() SupplyConserved { return t.conservation }

func (t ProtocolOperationSafe) Reentrancy() SafeInteraction { return t.reentrancy }


