# Code generated by shengen-ex from cmd/shengen-ex/testdata/features.shen. DO NOT EDIT.
#
# Guard types for the Shen spec. Every struct is @opaque and only its
# new/N constructor can build it; new/N checks each premise of the Shen
# sequent rule and returns {:error, {:premise, "<shen premise>", values}}
# on violation. Compile with Feat.Shen.GuardTracer (generated
# separately) so %Guard{} literals outside this file fail to compile.

defmodule Feat.Shen do
  @moduledoc """
  Registry for the guard types generated from `cmd/shengen-ex/testdata/features.shen`.
  """

  @guards [
    Feat.Shen.AccountId,
    Feat.Shen.Amount,
    Feat.Shen.Currency,
    Feat.Shen.Money,
    Feat.Shen.Transfer,
    Feat.Shen.BalanceChecked,
    Feat.Shen.SafeTransfer,
    Feat.Shen.Settled,
    Feat.Shen.StepWait,
    Feat.Shen.StepCall,
    Feat.Shen.Workflow,
    Feat.Shen.Audited
  ]

  @doc "Every generated guard struct module."
  @spec guards() :: [module()]
  def guards, do: @guards

  @doc "The spec these guards were generated from."
  @spec spec_path() :: String.t()
  def spec_path, do: "cmd/shengen-ex/testdata/features.shen"
end

defmodule Feat.Shen.GuardError do
  @moduledoc "Raised by `new!/N` when a Shen premise does not hold."

  @type reason ::
          {:premise, String.t(), keyword()}
          | {:type, String.t(), keyword()}
          | {:unsupported_premise, String.t(), keyword()}

  defexception [:guard, :reason]

  @impl true
  def message(%{guard: guard, reason: {kind, premise, values}}) do
    "#{inspect(guard)}: #{kind} #{premise} failed for #{inspect(values)}"
  end
end

defmodule Feat.Shen.Term do
  @moduledoc """
  Shen representation of guard values: wrappers become their primitive,
  composites become lists in conclusion order.
  """

  @guards Feat.Shen.guards()

  @doc "Converts a (possibly nested) guard value to its Shen representation."
  @spec to_shen(term()) :: term()
  def to_shen(%{__struct__: module} = value) when module in @guards, do: module.__shen__(value)
  def to_shen(list) when is_list(list), do: Enum.map(list, &to_shen/1)
  def to_shen(value), do: value

  @doc false
  @spec fail_closed() :: true
  def fail_closed, do: true
end

defmodule Feat.Shen.AccountId do
  @moduledoc """
  Guard type for Shen `account-id` (wrapper).

      X : string;
      ==========
      X : account-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `account-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "account-id"
end

defmodule Feat.Shen.Amount do
  @moduledoc """
  Guard type for Shen `amount` (constrained).

      X : number;
      (>= X 0) : verified;
      ==========
      X : amount;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: number()}

  @doc "Builds a `amount` value, checking every premise of the Shen rule."
  @spec new(number()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_number(x)) ->
        {:error, {:type, "X : number", [x: x]}}

      not (x >= 0) ->
        {:error, {:premise, "(>= X 0)", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(number()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: number()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "amount"
end

defmodule Feat.Shen.Currency do
  @moduledoc """
  Guard type for Shen `currency` (constrained).

      X : symbol;
      (element? X [usd eur gbp]) : verified;
      ==========
      X : currency;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: atom()}

  @doc "Builds a `currency` value, checking every premise of the Shen rule."
  @spec new(atom()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_atom(x)) ->
        {:error, {:type, "X : symbol", [x: x]}}

      not (x in [:usd, :eur, :gbp]) ->
        {:error, {:premise, "(element? X [usd eur gbp])", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(atom()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: atom()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "currency"
end

defmodule Feat.Shen.Money do
  @moduledoc """
  Guard type for Shen `money` (composite).

      Amt : amount;
      Cur : currency;
      ==========
      [Amt Cur] : money;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:amt, :cur]
  defstruct [:amt, :cur]

  @opaque t :: %__MODULE__{amt: Feat.Shen.Amount.t(), cur: Feat.Shen.Currency.t()}

  @doc "Builds a `money` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.Amount.t(), Feat.Shen.Currency.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(amt, cur) do
    cond do
      not (is_struct(amt, Feat.Shen.Amount)) ->
        {:error, {:type, "Amt : amount", [amt: amt]}}

      not (is_struct(cur, Feat.Shen.Currency)) ->
        {:error, {:type, "Cur : currency", [cur: cur]}}

      true ->
        {:ok, %__MODULE__{amt: amt, cur: cur}}
    end
  end

  @doc "Like `new/2` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.Amount.t(), Feat.Shen.Currency.t()) :: t()
  def new!(amt, cur) do
    case new(amt, cur) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Amt` field."
  @spec amt(t()) :: Feat.Shen.Amount.t()
  def amt(%__MODULE__{amt: value}), do: value

  @doc "The `Cur` field."
  @spec cur(t()) :: Feat.Shen.Currency.t()
  def cur(%__MODULE__{cur: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Feat.Shen.Term.to_shen(guard.amt), Feat.Shen.Term.to_shen(guard.cur)]

  @doc false
  def __shen_type__, do: "money"
end

defmodule Feat.Shen.Transfer do
  @moduledoc """
  Guard type for Shen `transfer` (guarded).

      From : account-id;
      To : account-id;
      Value : money;
      (not (= From To)) : verified;
      (> (head Value) 0) : verified;
      ==========
      [From To Value] : transfer;

  Only `new/3` can build this struct; it checks every premise above.
  """

  @enforce_keys [:from, :to, :value]
  defstruct [:from, :to, :value]

  @opaque t :: %__MODULE__{from: Feat.Shen.AccountId.t(), to: Feat.Shen.AccountId.t(), value: Feat.Shen.Money.t()}

  @doc "Builds a `transfer` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.AccountId.t(), Feat.Shen.AccountId.t(), Feat.Shen.Money.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(from, to, value) do
    cond do
      not (is_struct(from, Feat.Shen.AccountId)) ->
        {:error, {:type, "From : account-id", [from: from]}}

      not (is_struct(to, Feat.Shen.AccountId)) ->
        {:error, {:type, "To : account-id", [to: to]}}

      not (is_struct(value, Feat.Shen.Money)) ->
        {:error, {:type, "Value : money", [value: value]}}

      from == to ->
        {:error, {:premise, "(not (= From To))", [from: from, to: to]}}

      not (Feat.Shen.Amount.val(Feat.Shen.Money.amt(value)) > 0) ->
        {:error, {:premise, "(> (head Value) 0)", [value: value]}}

      true ->
        {:ok, %__MODULE__{from: from, to: to, value: value}}
    end
  end

  @doc "Like `new/3` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.AccountId.t(), Feat.Shen.AccountId.t(), Feat.Shen.Money.t()) :: t()
  def new!(from, to, value) do
    case new(from, to, value) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `From` field."
  @spec from(t()) :: Feat.Shen.AccountId.t()
  def from(%__MODULE__{from: value}), do: value

  @doc "The `To` field."
  @spec to(t()) :: Feat.Shen.AccountId.t()
  def to(%__MODULE__{to: value}), do: value

  @doc "The `Value` field."
  @spec value(t()) :: Feat.Shen.Money.t()
  def value(%__MODULE__{value: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Feat.Shen.Term.to_shen(guard.from), Feat.Shen.Term.to_shen(guard.to), Feat.Shen.Term.to_shen(guard.value)]

  @doc false
  def __shen_type__, do: "transfer"
end

defmodule Feat.Shen.BalanceChecked do
  @moduledoc """
  Guard type for Shen `balance-checked` (guarded).

      Bal : number;
      Tx : transfer;
      (>= Bal (head (head (tail (tail Tx))))) : verified;
      ==========
      [Bal Tx] : balance-checked;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:bal, :tx]
  defstruct [:bal, :tx]

  @opaque t :: %__MODULE__{bal: number(), tx: Feat.Shen.Transfer.t()}

  @doc "Builds a `balance-checked` value, checking every premise of the Shen rule."
  @spec new(number(), Feat.Shen.Transfer.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(bal, tx) do
    cond do
      not (is_number(bal)) ->
        {:error, {:type, "Bal : number", [bal: bal]}}

      not (is_struct(tx, Feat.Shen.Transfer)) ->
        {:error, {:type, "Tx : transfer", [tx: tx]}}

      not (bal >= Feat.Shen.Amount.val(Feat.Shen.Money.amt(Feat.Shen.Transfer.value(tx)))) ->
        {:error, {:premise, "(>= Bal (head (head (tail (tail Tx)))))", [bal: bal, tx: tx]}}

      true ->
        {:ok, %__MODULE__{bal: bal, tx: tx}}
    end
  end

  @doc "Like `new/2` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(number(), Feat.Shen.Transfer.t()) :: t()
  def new!(bal, tx) do
    case new(bal, tx) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Bal` field."
  @spec bal(t()) :: number()
  def bal(%__MODULE__{bal: value}), do: value

  @doc "The `Tx` field."
  @spec tx(t()) :: Feat.Shen.Transfer.t()
  def tx(%__MODULE__{tx: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [guard.bal, Feat.Shen.Term.to_shen(guard.tx)]

  @doc false
  def __shen_type__, do: "balance-checked"
end

defmodule Feat.Shen.SafeTransfer do
  @moduledoc """
  Guard type for Shen `safe-transfer` (guarded).

      Tx : transfer;
      Check : balance-checked;
      (= Tx (head (tail Check))) : verified;
      ==========
      [Tx Check] : safe-transfer;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:tx, :check]
  defstruct [:tx, :check]

  @opaque t :: %__MODULE__{tx: Feat.Shen.Transfer.t(), check: Feat.Shen.BalanceChecked.t()}

  @doc "Builds a `safe-transfer` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.Transfer.t(), Feat.Shen.BalanceChecked.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(tx, check) do
    cond do
      not (is_struct(tx, Feat.Shen.Transfer)) ->
        {:error, {:type, "Tx : transfer", [tx: tx]}}

      not (is_struct(check, Feat.Shen.BalanceChecked)) ->
        {:error, {:type, "Check : balance-checked", [check: check]}}

      not (tx == Feat.Shen.BalanceChecked.tx(check)) ->
        {:error, {:premise, "(= Tx (head (tail Check)))", [tx: tx, check: check]}}

      true ->
        {:ok, %__MODULE__{tx: tx, check: check}}
    end
  end

  @doc "Like `new/2` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.Transfer.t(), Feat.Shen.BalanceChecked.t()) :: t()
  def new!(tx, check) do
    case new(tx, check) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Tx` field."
  @spec tx(t()) :: Feat.Shen.Transfer.t()
  def tx(%__MODULE__{tx: value}), do: value

  @doc "The `Check` field."
  @spec check(t()) :: Feat.Shen.BalanceChecked.t()
  def check(%__MODULE__{check: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Feat.Shen.Term.to_shen(guard.tx), Feat.Shen.Term.to_shen(guard.check)]

  @doc false
  def __shen_type__, do: "safe-transfer"
end

defmodule Feat.Shen.Settled do
  @moduledoc """
  Guard type for Shen `settled` (alias).

      T : safe-transfer;
      ==========
      T : settled;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: Feat.Shen.SafeTransfer.t()}

  @doc "Builds a `settled` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.SafeTransfer.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(t) do
    cond do
      not (is_struct(t, Feat.Shen.SafeTransfer)) ->
        {:error, {:type, "T : safe-transfer", [t: t]}}

      true ->
        {:ok, %__MODULE__{val: t}}
    end
  end

  @doc "Like `new/1` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.SafeTransfer.t()) :: t()
  def new!(t) do
    case new(t) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `T` field."
  @spec val(t()) :: Feat.Shen.SafeTransfer.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: Feat.Shen.Term.to_shen(guard.val)

  @doc false
  def __shen_type__, do: "settled"
end

defmodule Feat.Shen.StepWait do
  @moduledoc """
  Guard type for Shen `step-wait` (composite), a variant of `workflow-step`.

      Seconds : amount;
      ==========
      [wait Seconds] : workflow-step;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:seconds]
  defstruct [:seconds]

  @opaque t :: %__MODULE__{seconds: Feat.Shen.Amount.t()}

  @doc "Builds a `step-wait` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.Amount.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(seconds) do
    cond do
      not (is_struct(seconds, Feat.Shen.Amount)) ->
        {:error, {:type, "Seconds : amount", [seconds: seconds]}}

      true ->
        {:ok, %__MODULE__{seconds: seconds}}
    end
  end

  @doc "Like `new/1` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.Amount.t()) :: t()
  def new!(seconds) do
    case new(seconds) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Seconds` field."
  @spec seconds(t()) :: Feat.Shen.Amount.t()
  def seconds(%__MODULE__{seconds: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [:wait, Feat.Shen.Term.to_shen(guard.seconds)]

  @doc false
  def __shen_type__, do: "workflow-step"
end

defmodule Feat.Shen.StepCall do
  @moduledoc """
  Guard type for Shen `step-call` (guarded), a variant of `workflow-step`.

      Target : account-id;
      Retries : number;
      (<= Retries 3) : verified;
      ==========
      [call Target Retries] : workflow-step;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:target, :retries]
  defstruct [:target, :retries]

  @opaque t :: %__MODULE__{target: Feat.Shen.AccountId.t(), retries: number()}

  @doc "Builds a `step-call` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.AccountId.t(), number()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(target, retries) do
    cond do
      not (is_struct(target, Feat.Shen.AccountId)) ->
        {:error, {:type, "Target : account-id", [target: target]}}

      not (is_number(retries)) ->
        {:error, {:type, "Retries : number", [retries: retries]}}

      not (retries <= 3) ->
        {:error, {:premise, "(<= Retries 3)", [retries: retries]}}

      true ->
        {:ok, %__MODULE__{target: target, retries: retries}}
    end
  end

  @doc "Like `new/2` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.AccountId.t(), number()) :: t()
  def new!(target, retries) do
    case new(target, retries) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Target` field."
  @spec target(t()) :: Feat.Shen.AccountId.t()
  def target(%__MODULE__{target: value}), do: value

  @doc "The `Retries` field."
  @spec retries(t()) :: number()
  def retries(%__MODULE__{retries: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [:call, Feat.Shen.Term.to_shen(guard.target), guard.retries]

  @doc false
  def __shen_type__, do: "workflow-step"
end

defmodule Feat.Shen.Workflow do
  @moduledoc """
  Guard type for Shen `workflow` (guarded).

      Steps : (list workflow-step);
      Owner : account-id;
      (> (length Steps) 0) : verified;
      (allowed-owner? Owner Steps) : verified;
      ==========
      [Steps Owner] : workflow;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:steps, :owner]
  defstruct [:steps, :owner]

  @opaque t :: %__MODULE__{steps: [Feat.Shen.WorkflowStep.t()], owner: Feat.Shen.AccountId.t()}

  @doc "Builds a `workflow` value, checking every premise of the Shen rule."
  @spec new([Feat.Shen.WorkflowStep.t()], Feat.Shen.AccountId.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(steps, owner) do
    cond do
      not (is_list(steps) and Enum.all?(steps, fn e -> Feat.Shen.WorkflowStep.member?(e) end)) ->
        {:error, {:type, "Steps : (list workflow-step)", [steps: steps]}}

      not (is_struct(owner, Feat.Shen.AccountId)) ->
        {:error, {:type, "Owner : account-id", [owner: owner]}}

      not (length(Feat.Shen.Term.to_shen(steps)) > 0) ->
        {:error, {:premise, "(> (length Steps) 0)", [steps: steps]}}

      not (Feat.Shen.Defines.allowed_owner?(owner, steps)) ->
        {:error, {:premise, "(allowed-owner? Owner Steps)", [owner: owner, steps: steps]}}

      true ->
        {:ok, %__MODULE__{steps: steps, owner: owner}}
    end
  end

  @doc "Like `new/2` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!([Feat.Shen.WorkflowStep.t()], Feat.Shen.AccountId.t()) :: t()
  def new!(steps, owner) do
    case new(steps, owner) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Steps` field."
  @spec steps(t()) :: [Feat.Shen.WorkflowStep.t()]
  def steps(%__MODULE__{steps: value}), do: value

  @doc "The `Owner` field."
  @spec owner(t()) :: Feat.Shen.AccountId.t()
  def owner(%__MODULE__{owner: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Feat.Shen.Term.to_shen(guard.steps), Feat.Shen.Term.to_shen(guard.owner)]

  @doc false
  def __shen_type__, do: "workflow"
end

defmodule Feat.Shen.Audited do
  @moduledoc """
  Guard type for Shen `audited` (guarded).

      Actor : account-id;
      Note : string;
      (not (= Note "")) : verified; \\* :runtime-via auditLog *\\
      ==========
      [Actor Note] : audited;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:actor, :note]
  defstruct [:actor, :note]

  @opaque t :: %__MODULE__{actor: Feat.Shen.AccountId.t(), note: String.t()}

  @doc "Builds a `audited` value, checking every premise of the Shen rule."
  @spec new(Feat.Shen.AccountId.t(), String.t()) :: {:ok, t()} | {:error, Feat.Shen.GuardError.reason()}
  def new(actor, note) do
    cond do
      not (is_struct(actor, Feat.Shen.AccountId)) ->
        {:error, {:type, "Actor : account-id", [actor: actor]}}

      not (is_binary(note)) ->
        {:error, {:type, "Note : string", [note: note]}}

      not (Feat.Shen.Runtime.audit_log(note) == true) ->
        {:error, {:premise, "(not (= Note \"\"))", [note: note]}}

      true ->
        {:ok, %__MODULE__{actor: actor, note: note}}
    end
  end

  @doc "Like `new/2` but raises `Feat.Shen.GuardError` when a premise fails."
  @spec new!(Feat.Shen.AccountId.t(), String.t()) :: t()
  def new!(actor, note) do
    case new(actor, note) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Feat.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Actor` field."
  @spec actor(t()) :: Feat.Shen.AccountId.t()
  def actor(%__MODULE__{actor: value}), do: value

  @doc "The `Note` field."
  @spec note(t()) :: String.t()
  def note(%__MODULE__{note: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Feat.Shen.Term.to_shen(guard.actor), guard.note]

  @doc false
  def __shen_type__, do: "audited"
end

defmodule Feat.Shen.WorkflowStep do
  @moduledoc """
  Sum type `workflow-step`: a value built by any of its variant rules.
  """

  @type t :: Feat.Shen.StepWait.t() | Feat.Shen.StepCall.t()

  @variants [Feat.Shen.StepWait, Feat.Shen.StepCall]

  @doc "Variant modules of this sum type."
  @spec variants() :: [module()]
  def variants, do: @variants

  @doc "True when `value` was built by one of the variant constructors."
  @spec member?(term()) :: boolean()
  def member?(%{__struct__: module}) when module in @variants, do: true
  def member?(_), do: false
end

defmodule Feat.Shen.Defines do
  @moduledoc """
  Elixir lowering of Shen `(define ...)` blocks (those verified premises call, or all with --all-defines).

  Arguments are converted to their Shen representation first, so the
  bodies run with Shen data semantics (first-match clauses, non-linear
  patterns, `where` guards).
  """

  @doc "Shen `allowed-owner?` {account-id --> (list workflow-step) --> boolean}"
  @spec allowed_owner?(term(), term()) :: term()
  def allowed_owner?(a1, a2), do: shen__allowed_owner(Feat.Shen.Term.to_shen(a1), Feat.Shen.Term.to_shen(a2))

  defp shen__allowed_owner(_, []), do: true
  defp shen__allowed_owner(owner, [[:call, owner, _] | rest]), do: shen__allowed_owner(owner, rest)
  defp shen__allowed_owner(_, [[:call, _, _] | _]), do: false
  defp shen__allowed_owner(owner, [_ | rest]), do: shen__allowed_owner(owner, rest)
  defp shen__allowed_owner(_, _), do: raise(ArgumentError, "partial function allowed-owner?")

  @doc "Shen `total-retries` {(list workflow-step) --> number}"
  @spec total_retries(term()) :: term()
  def total_retries(a1), do: shen__total_retries(Feat.Shen.Term.to_shen(a1))

  defp shen__total_retries([]), do: 0
  defp shen__total_retries([[:call, _, n] | rest]), do: (n + shen__total_retries(rest))
  defp shen__total_retries([_ | rest]), do: shen__total_retries(rest)
  defp shen__total_retries(_), do: raise(ArgumentError, "partial function total-retries")

  @doc "Shen `classify` {number --> symbol}"
  @spec classify(term()) :: term()
  def classify(a1), do: shen__classify(Feat.Shen.Term.to_shen(a1))

  defp shen__classify(a__1), do: shen__classify__c1(a__1)
  defp shen__classify__c1(x = a__1) do
    if (x < 10), do: :small, else: shen__classify__c2(a__1)
  end
  defp shen__classify__c2(x = a__1) do
    if ((x >= 10) and (x < 100)), do: :medium, else: shen__classify__c3(a__1)
  end
  defp shen__classify__c3(_), do: :large

  @doc "Shen `same?` {string --> string --> boolean}"
  @spec same?(term(), term()) :: term()
  def same?(a1, a2), do: shen__same(Feat.Shen.Term.to_shen(a1), Feat.Shen.Term.to_shen(a2))

  defp shen__same(x, x), do: true
  defp shen__same(_, _), do: false
end
