# Code generated by shengen-ex from examples/multi-tenant-api/specs/core.shen. DO NOT EDIT.
#
# Guard types for the Shen spec. Every struct is @opaque and only its
# new/N constructor can build it; new/N checks each premise of the Shen
# sequent rule and returns {:error, {:premise, "<shen premise>", values}}
# on violation. Compile with MultiTenant.Shen.GuardTracer (generated
# separately) so %Guard{} literals outside this file fail to compile.

defmodule MultiTenant.Shen do
  @moduledoc """
  Registry for the guard types generated from `examples/multi-tenant-api/specs/core.shen`.
  """

  @guards [
    MultiTenant.Shen.UserId,
    MultiTenant.Shen.TenantId,
    MultiTenant.Shen.ResourceId,
    MultiTenant.Shen.JwtIssuer,
    MultiTenant.Shen.JwtAudience,
    MultiTenant.Shen.ParsedClaims,
    MultiTenant.Shen.VerifiedJwt,
    MultiTenant.Shen.AuthenticatedUser,
    MultiTenant.Shen.ServiceId,
    MultiTenant.Shen.ServiceCredential,
    MultiTenant.Shen.HumanPrincipal,
    MultiTenant.Shen.ServicePrincipal,
    MultiTenant.Shen.TenantAccess,
    MultiTenant.Shen.ResourceAccess
  ]

  @doc "Every generated guard struct module."
  @spec guards() :: [module()]
  def guards, do: @guards

  @doc "The spec these guards were generated from."
  @spec spec_path() :: String.t()
  def spec_path, do: "examples/multi-tenant-api/specs/core.shen"
end

defmodule MultiTenant.Shen.GuardError do
  @moduledoc "Raised by `new!/N` when a Shen premise does not hold."

  @type reason ::
          {:premise, String.t(), keyword()}
          | {:type, String.t(), keyword()}
          | {:unsupported_premise, String.t(), keyword()}

  defexception [:guard, :reason]

  @impl true
  def message(%{guard: guard, reason: {kind, premise, values}}) do
    "#{inspect(guard)}: #{kind} #{premise} failed for #{inspect(values)}"
  end
end

defmodule MultiTenant.Shen.Term do
  @moduledoc """
  Shen representation of guard values: wrappers become their primitive,
  composites become lists in conclusion order.
  """

  @guards MultiTenant.Shen.guards()

  @doc "Converts a (possibly nested) guard value to its Shen representation."
  @spec to_shen(term()) :: term()
  def to_shen(%{__struct__: module} = value) when module in @guards, do: module.__shen__(value)
  def to_shen(list) when is_list(list), do: Enum.map(list, &to_shen/1)
  def to_shen(value), do: value

  @doc false
  @spec fail_closed() :: true
  def fail_closed, do: true
end

defmodule MultiTenant.Shen.UserId do
  @moduledoc """
  Guard type for Shen `user-id` (wrapper).

      X : string;
      ==========
      X : user-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `user-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "user-id"
end

defmodule MultiTenant.Shen.TenantId do
  @moduledoc """
  Guard type for Shen `tenant-id` (wrapper).

      X : string;
      ==========
      X : tenant-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `tenant-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "tenant-id"
end

defmodule MultiTenant.Shen.ResourceId do
  @moduledoc """
  Guard type for Shen `resource-id` (wrapper).

      X : string;
      ==========
      X : resource-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `resource-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "resource-id"
end

defmodule MultiTenant.Shen.JwtIssuer do
  @moduledoc """
  Guard type for Shen `jwt-issuer` (constrained).

      X : string;
      (not (= X "")) : verified;
      ==========
      X : jwt-issuer;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `jwt-issuer` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      x == "" ->
        {:error, {:premise, "(not (= X \"\"))", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "jwt-issuer"
end

defmodule MultiTenant.Shen.JwtAudience do
  @moduledoc """
  Guard type for Shen `jwt-audience` (constrained).

      X : string;
      (not (= X "")) : verified;
      ==========
      X : jwt-audience;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `jwt-audience` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      x == "" ->
        {:error, {:premise, "(not (= X \"\"))", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "jwt-audience"
end

defmodule MultiTenant.Shen.ParsedClaims do
  @moduledoc """
  Guard type for Shen `parsed-claims` (guarded).

      Sub : user-id;
      Exp : number;
      Iss : jwt-issuer;
      Aud : jwt-audience;
      (> Exp 0) : verified;
      ==========
      [Sub Exp Iss Aud] : parsed-claims;

  Only `new/4` can build this struct; it checks every premise above.
  """

  @enforce_keys [:sub, :exp, :iss, :aud]
  defstruct [:sub, :exp, :iss, :aud]

  @opaque t :: %__MODULE__{sub: MultiTenant.Shen.UserId.t(), exp: number(), iss: MultiTenant.Shen.JwtIssuer.t(), aud: MultiTenant.Shen.JwtAudience.t()}

  @doc "Builds a `parsed-claims` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.UserId.t(), number(), MultiTenant.Shen.JwtIssuer.t(), MultiTenant.Shen.JwtAudience.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(sub, exp, iss, aud) do
    cond do
      not (is_struct(sub, MultiTenant.Shen.UserId)) ->
        {:error, {:type, "Sub : user-id", [sub: sub]}}

      not (is_number(exp)) ->
        {:error, {:type, "Exp : number", [exp: exp]}}

      not (is_struct(iss, MultiTenant.Shen.JwtIssuer)) ->
        {:error, {:type, "Iss : jwt-issuer", [iss: iss]}}

      not (is_struct(aud, MultiTenant.Shen.JwtAudience)) ->
        {:error, {:type, "Aud : jwt-audience", [aud: aud]}}

      not (exp > 0) ->
        {:error, {:premise, "(> Exp 0)", [exp: exp]}}

      true ->
        {:ok, %__MODULE__{sub: sub, exp: exp, iss: iss, aud: aud}}
    end
  end

  @doc "Like `new/4` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.UserId.t(), number(), MultiTenant.Shen.JwtIssuer.t(), MultiTenant.Shen.JwtAudience.t()) :: t()
  def new!(sub, exp, iss, aud) do
    case new(sub, exp, iss, aud) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Sub` field."
  @spec sub(t()) :: MultiTenant.Shen.UserId.t()
  def sub(%__MODULE__{sub: value}), do: value

  @doc "The `Exp` field."
  @spec exp(t()) :: number()
  def exp(%__MODULE__{exp: value}), do: value

  @doc "The `Iss` field."
  @spec iss(t()) :: MultiTenant.Shen.JwtIssuer.t()
  def iss(%__MODULE__{iss: value}), do: value

  @doc "The `Aud` field."
  @spec aud(t()) :: MultiTenant.Shen.JwtAudience.t()
  def aud(%__MODULE__{aud: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [MultiTenant.Shen.Term.to_shen(guard.sub), guard.exp, MultiTenant.Shen.Term.to_shen(guard.iss), MultiTenant.Shen.Term.to_shen(guard.aud)]

  @doc false
  def __shen_type__, do: "parsed-claims"
end

defmodule MultiTenant.Shen.VerifiedJwt do
  @moduledoc """
  Guard type for Shen `verified-jwt` (guarded).

      Claims : parsed-claims;
      Sig : string;
      (not (= Sig "")) : verified;
      ==========
      [Claims Sig] : verified-jwt;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:claims, :sig]
  defstruct [:claims, :sig]

  @opaque t :: %__MODULE__{claims: MultiTenant.Shen.ParsedClaims.t(), sig: String.t()}

  @doc "Builds a `verified-jwt` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.ParsedClaims.t(), String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(claims, sig) do
    cond do
      not (is_struct(claims, MultiTenant.Shen.ParsedClaims)) ->
        {:error, {:type, "Claims : parsed-claims", [claims: claims]}}

      not (is_binary(sig)) ->
        {:error, {:type, "Sig : string", [sig: sig]}}

      sig == "" ->
        {:error, {:premise, "(not (= Sig \"\"))", [sig: sig]}}

      true ->
        {:ok, %__MODULE__{claims: claims, sig: sig}}
    end
  end

  @doc "Like `new/2` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.ParsedClaims.t(), String.t()) :: t()
  def new!(claims, sig) do
    case new(claims, sig) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Claims` field."
  @spec claims(t()) :: MultiTenant.Shen.ParsedClaims.t()
  def claims(%__MODULE__{claims: value}), do: value

  @doc "The `Sig` field."
  @spec sig(t()) :: String.t()
  def sig(%__MODULE__{sig: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [MultiTenant.Shen.Term.to_shen(guard.claims), guard.sig]

  @doc false
  def __shen_type__, do: "verified-jwt"
end

defmodule MultiTenant.Shen.AuthenticatedUser do
  @moduledoc """
  Guard type for Shen `authenticated-user` (guarded).

      Jwt : verified-jwt;
      User : user-id;
      (= User (head (head Jwt))) : verified;
      ==========
      [Jwt User] : authenticated-user;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:jwt, :user]
  defstruct [:jwt, :user]

  @opaque t :: %__MODULE__{jwt: MultiTenant.Shen.VerifiedJwt.t(), user: MultiTenant.Shen.UserId.t()}

  @doc "Builds a `authenticated-user` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.VerifiedJwt.t(), MultiTenant.Shen.UserId.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(jwt, user) do
    cond do
      not (is_struct(jwt, MultiTenant.Shen.VerifiedJwt)) ->
        {:error, {:type, "Jwt : verified-jwt", [jwt: jwt]}}

      not (is_struct(user, MultiTenant.Shen.UserId)) ->
        {:error, {:type, "User : user-id", [user: user]}}

      not (user == MultiTenant.Shen.ParsedClaims.sub(MultiTenant.Shen.VerifiedJwt.claims(jwt))) ->
        {:error, {:premise, "(= User (head (head Jwt)))", [user: user, jwt: jwt]}}

      true ->
        {:ok, %__MODULE__{jwt: jwt, user: user}}
    end
  end

  @doc "Like `new/2` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.VerifiedJwt.t(), MultiTenant.Shen.UserId.t()) :: t()
  def new!(jwt, user) do
    case new(jwt, user) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Jwt` field."
  @spec jwt(t()) :: MultiTenant.Shen.VerifiedJwt.t()
  def jwt(%__MODULE__{jwt: value}), do: value

  @doc "The `User` field."
  @spec user(t()) :: MultiTenant.Shen.UserId.t()
  def user(%__MODULE__{user: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [MultiTenant.Shen.Term.to_shen(guard.jwt), MultiTenant.Shen.Term.to_shen(guard.user)]

  @doc false
  def __shen_type__, do: "authenticated-user"
end

defmodule MultiTenant.Shen.ServiceId do
  @moduledoc """
  Guard type for Shen `service-id` (wrapper).

      X : string;
      ==========
      X : service-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `service-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "service-id"
end

defmodule MultiTenant.Shen.ServiceCredential do
  @moduledoc """
  Guard type for Shen `service-credential` (guarded).

      Service : service-id;
      Secret : string;
      (not (= Secret "")) : verified;
      ==========
      [Service Secret] : service-credential;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:service, :secret]
  defstruct [:service, :secret]

  @opaque t :: %__MODULE__{service: MultiTenant.Shen.ServiceId.t(), secret: String.t()}

  @doc "Builds a `service-credential` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.ServiceId.t(), String.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(service, secret) do
    cond do
      not (is_struct(service, MultiTenant.Shen.ServiceId)) ->
        {:error, {:type, "Service : service-id", [service: service]}}

      not (is_binary(secret)) ->
        {:error, {:type, "Secret : string", [secret: secret]}}

      secret == "" ->
        {:error, {:premise, "(not (= Secret \"\"))", [secret: secret]}}

      true ->
        {:ok, %__MODULE__{service: service, secret: secret}}
    end
  end

  @doc "Like `new/2` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.ServiceId.t(), String.t()) :: t()
  def new!(service, secret) do
    case new(service, secret) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Service` field."
  @spec service(t()) :: MultiTenant.Shen.ServiceId.t()
  def service(%__MODULE__{service: value}), do: value

  @doc "The `Secret` field."
  @spec secret(t()) :: String.t()
  def secret(%__MODULE__{secret: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [MultiTenant.Shen.Term.to_shen(guard.service), guard.secret]

  @doc false
  def __shen_type__, do: "service-credential"
end

defmodule MultiTenant.Shen.HumanPrincipal do
  @moduledoc """
  Guard type for Shen `human-principal` (composite), a variant of `authenticated-principal`.

      Auth : authenticated-user;
      ==========
      Auth : authenticated-principal;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:auth]
  defstruct [:auth]

  @opaque t :: %__MODULE__{auth: MultiTenant.Shen.AuthenticatedUser.t()}

  @doc "Builds a `human-principal` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.AuthenticatedUser.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(auth) do
    cond do
      not (is_struct(auth, MultiTenant.Shen.AuthenticatedUser)) ->
        {:error, {:type, "Auth : authenticated-user", [auth: auth]}}

      true ->
        {:ok, %__MODULE__{auth: auth}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.AuthenticatedUser.t()) :: t()
  def new!(auth) do
    case new(auth) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Auth` field."
  @spec auth(t()) :: MultiTenant.Shen.AuthenticatedUser.t()
  def auth(%__MODULE__{auth: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: MultiTenant.Shen.Term.to_shen(guard.auth)

  @doc false
  def __shen_type__, do: "authenticated-principal"
end

defmodule MultiTenant.Shen.ServicePrincipal do
  @moduledoc """
  Guard type for Shen `service-principal` (composite), a variant of `authenticated-principal`.

      Cred : service-credential;
      ==========
      Cred : authenticated-principal;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:cred]
  defstruct [:cred]

  @opaque t :: %__MODULE__{cred: MultiTenant.Shen.ServiceCredential.t()}

  @doc "Builds a `service-principal` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.ServiceCredential.t()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(cred) do
    cond do
      not (is_struct(cred, MultiTenant.Shen.ServiceCredential)) ->
        {:error, {:type, "Cred : service-credential", [cred: cred]}}

      true ->
        {:ok, %__MODULE__{cred: cred}}
    end
  end

  @doc "Like `new/1` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.ServiceCredential.t()) :: t()
  def new!(cred) do
    case new(cred) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Cred` field."
  @spec cred(t()) :: MultiTenant.Shen.ServiceCredential.t()
  def cred(%__MODULE__{cred: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: MultiTenant.Shen.Term.to_shen(guard.cred)

  @doc false
  def __shen_type__, do: "authenticated-principal"
end

defmodule MultiTenant.Shen.TenantAccess do
  @moduledoc """
  Guard type for Shen `tenant-access` (guarded).

      Principal : authenticated-principal;
      Tenant : tenant-id;
      IsMember : boolean;
      (= IsMember true) : verified;
      ==========
      [Principal Tenant IsMember] : tenant-access;

  Only `new/3` can build this struct; it checks every premise above.
  """

  @enforce_keys [:principal, :tenant, :is_member]
  defstruct [:principal, :tenant, :is_member]

  @opaque t :: %__MODULE__{principal: MultiTenant.Shen.AuthenticatedPrincipal.t(), tenant: MultiTenant.Shen.TenantId.t(), is_member: boolean()}

  @doc "Builds a `tenant-access` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.AuthenticatedPrincipal.t(), MultiTenant.Shen.TenantId.t(), boolean()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(principal, tenant, is_member) do
    cond do
      not (MultiTenant.Shen.AuthenticatedPrincipal.member?(principal)) ->
        {:error, {:type, "Principal : authenticated-principal", [principal: principal]}}

      not (is_struct(tenant, MultiTenant.Shen.TenantId)) ->
        {:error, {:type, "Tenant : tenant-id", [tenant: tenant]}}

      not (is_boolean(is_member)) ->
        {:error, {:type, "IsMember : boolean", [is_member: is_member]}}

      not (is_member == true) ->
        {:error, {:premise, "(= IsMember true)", [is_member: is_member]}}

      true ->
        {:ok, %__MODULE__{principal: principal, tenant: tenant, is_member: is_member}}
    end
  end

  @doc "Like `new/3` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.AuthenticatedPrincipal.t(), MultiTenant.Shen.TenantId.t(), boolean()) :: t()
  def new!(principal, tenant, is_member) do
    case new(principal, tenant, is_member) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Principal` field."
  @spec principal(t()) :: MultiTenant.Shen.AuthenticatedPrincipal.t()
  def principal(%__MODULE__{principal: value}), do: value

  @doc "The `Tenant` field."
  @spec tenant(t()) :: MultiTenant.Shen.TenantId.t()
  def tenant(%__MODULE__{tenant: value}), do: value

  @doc "The `IsMember` field."
  @spec is_member(t()) :: boolean()
  def is_member(%__MODULE__{is_member: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [MultiTenant.Shen.Term.to_shen(guard.principal), MultiTenant.Shen.Term.to_shen(guard.tenant), guard.is_member]

  @doc false
  def __shen_type__, do: "tenant-access"
end

defmodule MultiTenant.Shen.ResourceAccess do
  @moduledoc """
  Guard type for Shen `resource-access` (guarded).

      Access : tenant-access;
      Resource : resource-id;
      IsOwned : boolean;
      (= IsOwned true) : verified;
      ==========
      [Access Resource IsOwned] : resource-access;

  Only `new/3` can build this struct; it checks every premise above.
  """

  @enforce_keys [:access, :resource, :is_owned]
  defstruct [:access, :resource, :is_owned]

  @opaque t :: %__MODULE__{access: MultiTenant.Shen.TenantAccess.t(), resource: MultiTenant.Shen.ResourceId.t(), is_owned: boolean()}

  @doc "Builds a `resource-access` value, checking every premise of the Shen rule."
  @spec new(MultiTenant.Shen.TenantAccess.t(), MultiTenant.Shen.ResourceId.t(), boolean()) :: {:ok, t()} | {:error, MultiTenant.Shen.GuardError.reason()}
  def new(access, resource, is_owned) do
    cond do
      not (is_struct(access, MultiTenant.Shen.TenantAccess)) ->
        {:error, {:type, "Access : tenant-access", [access: access]}}

      not (is_struct(resource, MultiTenant.Shen.ResourceId)) ->
        {:error, {:type, "Resource : resource-id", [resource: resource]}}

      not (is_boolean(is_owned)) ->
        {:error, {:type, "IsOwned : boolean", [is_owned: is_owned]}}

      not (is_owned == true) ->
        {:error, {:premise, "(= IsOwned true)", [is_owned: is_owned]}}

      true ->
        {:ok, %__MODULE__{access: access, resource: resource, is_owned: is_owned}}
    end
  end

  @doc "Like `new/3` but raises `MultiTenant.Shen.GuardError` when a premise fails."
  @spec new!(MultiTenant.Shen.TenantAccess.t(), MultiTenant.Shen.ResourceId.t(), boolean()) :: t()
  def new!(access, resource, is_owned) do
    case new(access, resource, is_owned) do
      {:ok, guard} -> guard
      {:error, reason} -> raise MultiTenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Access` field."
  @spec access(t()) :: MultiTenant.Shen.TenantAccess.t()
  def access(%__MODULE__{access: value}), do: value

  @doc "The `Resource` field."
  @spec resource(t()) :: MultiTenant.Shen.ResourceId.t()
  def resource(%__MODULE__{resource: value}), do: value

  @doc "The `IsOwned` field."
  @spec is_owned(t()) :: boolean()
  def is_owned(%__MODULE__{is_owned: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [MultiTenant.Shen.Term.to_shen(guard.access), MultiTenant.Shen.Term.to_shen(guard.resource), guard.is_owned]

  @doc false
  def __shen_type__, do: "resource-access"
end

defmodule MultiTenant.Shen.AuthenticatedPrincipal do
  @moduledoc """
  Sum type `authenticated-principal`: a value built by any of its variant rules.
  """

  @type t :: MultiTenant.Shen.HumanPrincipal.t() | MultiTenant.Shen.ServicePrincipal.t()

  @variants [MultiTenant.Shen.HumanPrincipal, MultiTenant.Shen.ServicePrincipal]

  @doc "Variant modules of this sum type."
  @spec variants() :: [module()]
  def variants, do: @variants

  @doc "True when `value` was built by one of the variant constructors."
  @spec member?(term()) :: boolean()
  def member?(%{__struct__: module}) when module in @variants, do: true
  def member?(_), do: false
end
