# Code generated by shengen-ex from examples/phoenix-ash-tenant/specs/core.shen. DO NOT EDIT.
#
# Guard types for the Shen spec. Every struct is @opaque and only its
# new/N constructor can build it; new/N checks each premise of the Shen
# sequent rule and returns {:error, {:premise, "<shen premise>", values}}
# on violation. Compile with Tenant.Shen.GuardTracer (generated
# separately) so %Guard{} literals outside this file fail to compile.

defmodule Tenant.Shen do
  @moduledoc """
  Registry for the guard types generated from `examples/phoenix-ash-tenant/specs/core.shen`.
  """

  @guards [
    Tenant.Shen.UserId,
    Tenant.Shen.TenantId,
    Tenant.Shen.ResourceId,
    Tenant.Shen.OperatorId,
    Tenant.Shen.VerifiedToken,
    Tenant.Shen.AuthenticatedUser,
    Tenant.Shen.OperatorCredential,
    Tenant.Shen.HumanPrincipal,
    Tenant.Shen.OperatorPrincipal,
    Tenant.Shen.TenantAccess,
    Tenant.Shen.ResourceAccess,
    Tenant.Shen.Role,
    Tenant.Shen.WriteAccess
  ]

  @doc "Every generated guard struct module."
  @spec guards() :: [module()]
  def guards, do: @guards

  @doc "The spec these guards were generated from."
  @spec spec_path() :: String.t()
  def spec_path, do: "examples/phoenix-ash-tenant/specs/core.shen"
end

defmodule Tenant.Shen.GuardError do
  @moduledoc "Raised by `new!/N` when a Shen premise does not hold."

  @type reason ::
          {:premise, String.t(), keyword()}
          | {:type, String.t(), keyword()}
          | {:unsupported_premise, String.t(), keyword()}

  defexception [:guard, :reason]

  @impl true
  def message(%{guard: guard, reason: {kind, premise, values}}) do
    "#{inspect(guard)}: #{kind} #{premise} failed for #{inspect(values)}"
  end
end

defmodule Tenant.Shen.Term do
  @moduledoc """
  Shen representation of guard values: wrappers become their primitive,
  composites become lists in conclusion order.
  """

  @guards Tenant.Shen.guards()

  @doc "Converts a (possibly nested) guard value to its Shen representation."
  @spec to_shen(term()) :: term()
  def to_shen(%{__struct__: module} = value) when module in @guards, do: module.__shen__(value)
  def to_shen(list) when is_list(list), do: Enum.map(list, &to_shen/1)
  def to_shen(value), do: value

  @doc false
  @spec fail_closed() :: true
  def fail_closed, do: true
end

defmodule Tenant.Shen.UserId do
  @moduledoc """
  Guard type for Shen `user-id` (wrapper).

      X : string;
      ==========
      X : user-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `user-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "user-id"
end

defmodule Tenant.Shen.TenantId do
  @moduledoc """
  Guard type for Shen `tenant-id` (wrapper).

      X : string;
      ==========
      X : tenant-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `tenant-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "tenant-id"
end

defmodule Tenant.Shen.ResourceId do
  @moduledoc """
  Guard type for Shen `resource-id` (wrapper).

      X : string;
      ==========
      X : resource-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `resource-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "resource-id"
end

defmodule Tenant.Shen.OperatorId do
  @moduledoc """
  Guard type for Shen `operator-id` (wrapper).

      X : string;
      ==========
      X : operator-id;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `operator-id` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "operator-id"
end

defmodule Tenant.Shen.VerifiedToken do
  @moduledoc """
  Guard type for Shen `verified-token` (guarded).

      Sub : user-id;
      Sig : string;
      (not (= Sig "")) : verified;
      ==========
      [Sub Sig] : verified-token;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:sub, :sig]
  defstruct [:sub, :sig]

  @opaque t :: %__MODULE__{sub: Tenant.Shen.UserId.t(), sig: String.t()}

  @doc "Builds a `verified-token` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.UserId.t(), String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(sub, sig) do
    cond do
      not (is_struct(sub, Tenant.Shen.UserId)) ->
        {:error, {:type, "Sub : user-id", [sub: sub]}}

      not (is_binary(sig)) ->
        {:error, {:type, "Sig : string", [sig: sig]}}

      sig == "" ->
        {:error, {:premise, "(not (= Sig \"\"))", [sig: sig]}}

      true ->
        {:ok, %__MODULE__{sub: sub, sig: sig}}
    end
  end

  @doc "Like `new/2` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.UserId.t(), String.t()) :: t()
  def new!(sub, sig) do
    case new(sub, sig) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Sub` field."
  @spec sub(t()) :: Tenant.Shen.UserId.t()
  def sub(%__MODULE__{sub: value}), do: value

  @doc "The `Sig` field."
  @spec sig(t()) :: String.t()
  def sig(%__MODULE__{sig: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Tenant.Shen.Term.to_shen(guard.sub), guard.sig]

  @doc false
  def __shen_type__, do: "verified-token"
end

defmodule Tenant.Shen.AuthenticatedUser do
  @moduledoc """
  Guard type for Shen `authenticated-user` (guarded).

      Token : verified-token;
      User : user-id;
      (= User (head Token)) : verified;
      ==========
      [Token User] : authenticated-user;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:token, :user]
  defstruct [:token, :user]

  @opaque t :: %__MODULE__{token: Tenant.Shen.VerifiedToken.t(), user: Tenant.Shen.UserId.t()}

  @doc "Builds a `authenticated-user` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.VerifiedToken.t(), Tenant.Shen.UserId.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(token, user) do
    cond do
      not (is_struct(token, Tenant.Shen.VerifiedToken)) ->
        {:error, {:type, "Token : verified-token", [token: token]}}

      not (is_struct(user, Tenant.Shen.UserId)) ->
        {:error, {:type, "User : user-id", [user: user]}}

      not (user == Tenant.Shen.VerifiedToken.sub(token)) ->
        {:error, {:premise, "(= User (head Token))", [user: user, token: token]}}

      true ->
        {:ok, %__MODULE__{token: token, user: user}}
    end
  end

  @doc "Like `new/2` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.VerifiedToken.t(), Tenant.Shen.UserId.t()) :: t()
  def new!(token, user) do
    case new(token, user) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Token` field."
  @spec token(t()) :: Tenant.Shen.VerifiedToken.t()
  def token(%__MODULE__{token: value}), do: value

  @doc "The `User` field."
  @spec user(t()) :: Tenant.Shen.UserId.t()
  def user(%__MODULE__{user: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Tenant.Shen.Term.to_shen(guard.token), Tenant.Shen.Term.to_shen(guard.user)]

  @doc false
  def __shen_type__, do: "authenticated-user"
end

defmodule Tenant.Shen.OperatorCredential do
  @moduledoc """
  Guard type for Shen `operator-credential` (guarded).

      Operator : operator-id;
      Secret : string;
      (not (= Secret "")) : verified;
      ==========
      [Operator Secret] : operator-credential;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:operator, :secret]
  defstruct [:operator, :secret]

  @opaque t :: %__MODULE__{operator: Tenant.Shen.OperatorId.t(), secret: String.t()}

  @doc "Builds a `operator-credential` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.OperatorId.t(), String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(operator, secret) do
    cond do
      not (is_struct(operator, Tenant.Shen.OperatorId)) ->
        {:error, {:type, "Operator : operator-id", [operator: operator]}}

      not (is_binary(secret)) ->
        {:error, {:type, "Secret : string", [secret: secret]}}

      secret == "" ->
        {:error, {:premise, "(not (= Secret \"\"))", [secret: secret]}}

      true ->
        {:ok, %__MODULE__{operator: operator, secret: secret}}
    end
  end

  @doc "Like `new/2` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.OperatorId.t(), String.t()) :: t()
  def new!(operator, secret) do
    case new(operator, secret) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Operator` field."
  @spec operator(t()) :: Tenant.Shen.OperatorId.t()
  def operator(%__MODULE__{operator: value}), do: value

  @doc "The `Secret` field."
  @spec secret(t()) :: String.t()
  def secret(%__MODULE__{secret: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Tenant.Shen.Term.to_shen(guard.operator), guard.secret]

  @doc false
  def __shen_type__, do: "operator-credential"
end

defmodule Tenant.Shen.HumanPrincipal do
  @moduledoc """
  Guard type for Shen `human-principal` (composite), a variant of `authenticated-principal`.

      Auth : authenticated-user;
      ==========
      Auth : authenticated-principal;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:auth]
  defstruct [:auth]

  @opaque t :: %__MODULE__{auth: Tenant.Shen.AuthenticatedUser.t()}

  @doc "Builds a `human-principal` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.AuthenticatedUser.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(auth) do
    cond do
      not (is_struct(auth, Tenant.Shen.AuthenticatedUser)) ->
        {:error, {:type, "Auth : authenticated-user", [auth: auth]}}

      true ->
        {:ok, %__MODULE__{auth: auth}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.AuthenticatedUser.t()) :: t()
  def new!(auth) do
    case new(auth) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Auth` field."
  @spec auth(t()) :: Tenant.Shen.AuthenticatedUser.t()
  def auth(%__MODULE__{auth: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: Tenant.Shen.Term.to_shen(guard.auth)

  @doc false
  def __shen_type__, do: "authenticated-principal"
end

defmodule Tenant.Shen.OperatorPrincipal do
  @moduledoc """
  Guard type for Shen `operator-principal` (composite), a variant of `authenticated-principal`.

      Op : operator-credential;
      ==========
      Op : authenticated-principal;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:op]
  defstruct [:op]

  @opaque t :: %__MODULE__{op: Tenant.Shen.OperatorCredential.t()}

  @doc "Builds a `operator-principal` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.OperatorCredential.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(op) do
    cond do
      not (is_struct(op, Tenant.Shen.OperatorCredential)) ->
        {:error, {:type, "Op : operator-credential", [op: op]}}

      true ->
        {:ok, %__MODULE__{op: op}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.OperatorCredential.t()) :: t()
  def new!(op) do
    case new(op) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Op` field."
  @spec op(t()) :: Tenant.Shen.OperatorCredential.t()
  def op(%__MODULE__{op: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: Tenant.Shen.Term.to_shen(guard.op)

  @doc false
  def __shen_type__, do: "authenticated-principal"
end

defmodule Tenant.Shen.TenantAccess do
  @moduledoc """
  Guard type for Shen `tenant-access` (guarded).

      Principal : authenticated-principal;
      Tenant : tenant-id;
      IsMember : boolean;
      (= IsMember true) : verified;
      ==========
      [Principal Tenant IsMember] : tenant-access;

  Only `new/3` can build this struct; it checks every premise above.
  """

  @enforce_keys [:principal, :tenant, :is_member]
  defstruct [:principal, :tenant, :is_member]

  @opaque t :: %__MODULE__{principal: Tenant.Shen.AuthenticatedPrincipal.t(), tenant: Tenant.Shen.TenantId.t(), is_member: boolean()}

  @doc "Builds a `tenant-access` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.AuthenticatedPrincipal.t(), Tenant.Shen.TenantId.t(), boolean()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(principal, tenant, is_member) do
    cond do
      not (Tenant.Shen.AuthenticatedPrincipal.member?(principal)) ->
        {:error, {:type, "Principal : authenticated-principal", [principal: principal]}}

      not (is_struct(tenant, Tenant.Shen.TenantId)) ->
        {:error, {:type, "Tenant : tenant-id", [tenant: tenant]}}

      not (is_boolean(is_member)) ->
        {:error, {:type, "IsMember : boolean", [is_member: is_member]}}

      not (is_member == true) ->
        {:error, {:premise, "(= IsMember true)", [is_member: is_member]}}

      true ->
        {:ok, %__MODULE__{principal: principal, tenant: tenant, is_member: is_member}}
    end
  end

  @doc "Like `new/3` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.AuthenticatedPrincipal.t(), Tenant.Shen.TenantId.t(), boolean()) :: t()
  def new!(principal, tenant, is_member) do
    case new(principal, tenant, is_member) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Principal` field."
  @spec principal(t()) :: Tenant.Shen.AuthenticatedPrincipal.t()
  def principal(%__MODULE__{principal: value}), do: value

  @doc "The `Tenant` field."
  @spec tenant(t()) :: Tenant.Shen.TenantId.t()
  def tenant(%__MODULE__{tenant: value}), do: value

  @doc "The `IsMember` field."
  @spec is_member(t()) :: boolean()
  def is_member(%__MODULE__{is_member: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Tenant.Shen.Term.to_shen(guard.principal), Tenant.Shen.Term.to_shen(guard.tenant), guard.is_member]

  @doc false
  def __shen_type__, do: "tenant-access"
end

defmodule Tenant.Shen.ResourceAccess do
  @moduledoc """
  Guard type for Shen `resource-access` (guarded).

      Access : tenant-access;
      Resource : resource-id;
      Owner : tenant-id;
      (= Owner (head (tail Access))) : verified;
      ==========
      [Access Resource Owner] : resource-access;

  Only `new/3` can build this struct; it checks every premise above.
  """

  @enforce_keys [:access, :resource, :owner]
  defstruct [:access, :resource, :owner]

  @opaque t :: %__MODULE__{access: Tenant.Shen.TenantAccess.t(), resource: Tenant.Shen.ResourceId.t(), owner: Tenant.Shen.TenantId.t()}

  @doc "Builds a `resource-access` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.TenantAccess.t(), Tenant.Shen.ResourceId.t(), Tenant.Shen.TenantId.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(access, resource, owner) do
    cond do
      not (is_struct(access, Tenant.Shen.TenantAccess)) ->
        {:error, {:type, "Access : tenant-access", [access: access]}}

      not (is_struct(resource, Tenant.Shen.ResourceId)) ->
        {:error, {:type, "Resource : resource-id", [resource: resource]}}

      not (is_struct(owner, Tenant.Shen.TenantId)) ->
        {:error, {:type, "Owner : tenant-id", [owner: owner]}}

      not (owner == Tenant.Shen.TenantAccess.tenant(access)) ->
        {:error, {:premise, "(= Owner (head (tail Access)))", [owner: owner, access: access]}}

      true ->
        {:ok, %__MODULE__{access: access, resource: resource, owner: owner}}
    end
  end

  @doc "Like `new/3` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.TenantAccess.t(), Tenant.Shen.ResourceId.t(), Tenant.Shen.TenantId.t()) :: t()
  def new!(access, resource, owner) do
    case new(access, resource, owner) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Access` field."
  @spec access(t()) :: Tenant.Shen.TenantAccess.t()
  def access(%__MODULE__{access: value}), do: value

  @doc "The `Resource` field."
  @spec resource(t()) :: Tenant.Shen.ResourceId.t()
  def resource(%__MODULE__{resource: value}), do: value

  @doc "The `Owner` field."
  @spec owner(t()) :: Tenant.Shen.TenantId.t()
  def owner(%__MODULE__{owner: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Tenant.Shen.Term.to_shen(guard.access), Tenant.Shen.Term.to_shen(guard.resource), Tenant.Shen.Term.to_shen(guard.owner)]

  @doc false
  def __shen_type__, do: "resource-access"
end

defmodule Tenant.Shen.Role do
  @moduledoc """
  Guard type for Shen `role` (constrained).

      X : string;
      (element? X ["viewer" "editor" "admin"]) : verified;
      ==========
      X : role;

  Only `new/1` can build this struct; it checks every premise above.
  """

  @enforce_keys [:val]
  defstruct [:val]

  @opaque t :: %__MODULE__{val: String.t()}

  @doc "Builds a `role` value, checking every premise of the Shen rule."
  @spec new(String.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(x) do
    cond do
      not (is_binary(x)) ->
        {:error, {:type, "X : string", [x: x]}}

      not (x in ["viewer", "editor", "admin"]) ->
        {:error, {:premise, "(element? X [\"viewer\" \"editor\" \"admin\"])", [x: x]}}

      true ->
        {:ok, %__MODULE__{val: x}}
    end
  end

  @doc "Like `new/1` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(String.t()) :: t()
  def new!(x) do
    case new(x) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `X` field."
  @spec val(t()) :: String.t()
  def val(%__MODULE__{val: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: guard.val

  @doc false
  def __shen_type__, do: "role"
end

defmodule Tenant.Shen.WriteAccess do
  @moduledoc """
  Guard type for Shen `write-access` (guarded).

      Access : resource-access;
      Role : role;
      (can-write? Role) : verified;
      ==========
      [Access Role] : write-access;

  Only `new/2` can build this struct; it checks every premise above.
  """

  @enforce_keys [:access, :role]
  defstruct [:access, :role]

  @opaque t :: %__MODULE__{access: Tenant.Shen.ResourceAccess.t(), role: Tenant.Shen.Role.t()}

  @doc "Builds a `write-access` value, checking every premise of the Shen rule."
  @spec new(Tenant.Shen.ResourceAccess.t(), Tenant.Shen.Role.t()) :: {:ok, t()} | {:error, Tenant.Shen.GuardError.reason()}
  def new(access, role) do
    cond do
      not (is_struct(access, Tenant.Shen.ResourceAccess)) ->
        {:error, {:type, "Access : resource-access", [access: access]}}

      not (is_struct(role, Tenant.Shen.Role)) ->
        {:error, {:type, "Role : role", [role: role]}}

      not (Tenant.Shen.Defines.can_write?(role)) ->
        {:error, {:premise, "(can-write? Role)", [role: role]}}

      true ->
        {:ok, %__MODULE__{access: access, role: role}}
    end
  end

  @doc "Like `new/2` but raises `Tenant.Shen.GuardError` when a premise fails."
  @spec new!(Tenant.Shen.ResourceAccess.t(), Tenant.Shen.Role.t()) :: t()
  def new!(access, role) do
    case new(access, role) do
      {:ok, guard} -> guard
      {:error, reason} -> raise Tenant.Shen.GuardError, guard: __MODULE__, reason: reason
    end
  end

  @doc "The `Access` field."
  @spec access(t()) :: Tenant.Shen.ResourceAccess.t()
  def access(%__MODULE__{access: value}), do: value

  @doc "The `Role` field."
  @spec role(t()) :: Tenant.Shen.Role.t()
  def role(%__MODULE__{role: value}), do: value

  @doc false
  def __shen__(%__MODULE__{} = guard), do: [Tenant.Shen.Term.to_shen(guard.access), Tenant.Shen.Term.to_shen(guard.role)]

  @doc false
  def __shen_type__, do: "write-access"
end

defmodule Tenant.Shen.AuthenticatedPrincipal do
  @moduledoc """
  Sum type `authenticated-principal`: a value built by any of its variant rules.
  """

  @type t :: Tenant.Shen.HumanPrincipal.t() | Tenant.Shen.OperatorPrincipal.t()

  @variants [Tenant.Shen.HumanPrincipal, Tenant.Shen.OperatorPrincipal]

  @doc "Variant modules of this sum type."
  @spec variants() :: [module()]
  def variants, do: @variants

  @doc "True when `value` was built by one of the variant constructors."
  @spec member?(term()) :: boolean()
  def member?(%{__struct__: module}) when module in @variants, do: true
  def member?(_), do: false
end

defmodule Tenant.Shen.Defines do
  @moduledoc """
  Elixir lowering of Shen `(define ...)` blocks (those verified premises call, or all with --all-defines).

  Arguments are converted to their Shen representation first, so the
  bodies run with Shen data semantics (first-match clauses, non-linear
  patterns, `where` guards).
  """

  @doc "Shen `can-write?` {string --> boolean}"
  @spec can_write?(term()) :: term()
  def can_write?(a1), do: shen__can_write(Tenant.Shen.Term.to_shen(a1))

  defp shen__can_write("editor"), do: true
  defp shen__can_write("admin"), do: true
  defp shen__can_write(_), do: false
end
