// Tests for the verification harness. Ported from
// shen-derive/verify/harness_test.go.

import { test } from "node:test";
import assert from "node:assert/strict";

import { parseFile } from "../specfile/parse.ts";
import { buildTypeTable } from "../specfile/typetable.ts";
import {
  buildBaseEnv,
  buildHarness,
  emit,
  evalDefine,
  type HarnessConfig,
} from "./harness.ts";
import type { Value } from "../core/eval.ts";
import { listVal, stringVal } from "../core/eval.ts";

// --- Payment spec: 1-define harness with wrapper + constrained + composite ---

const PAYMENT_SRC = `
(datatype account-id
  X : string;
  ==============
  X : account-id;)

(datatype amount
  X : number;
  (>= X 0) : verified;
  ====================
  X : amount;)

(datatype transaction
  Amount : amount;
  From : account-id;
  To : account-id;
  ===================================
  [Amount From To] : transaction;)

(define processable
  {amount --> (list transaction) --> boolean}
  B0 Txs -> (foldr (lambda X (lambda Acc (and (>= (val X) 0) Acc)))
              true
              (scanl (lambda B (lambda Tx (- (val B) (val (amount Tx))))) (val B0) Txs)))
`;

test("TestBuildHarnessPayment: builds cases, cases are booleans, emit contains key substrings", () => {
  const sf = parseFile(PAYMENT_SRC);
  assert.equal(sf.defines.length, 1);
  const tt = buildTypeTable(
    sf.datatypes,
    "./shenguard_gen.ts",
    "shenguard",
  );

  const cfg: HarnessConfig = {
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "processable",
    implModule: "./processable",
    implFunc: "Processable",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 35,
    seed: 0,
    randomDraws: 0,
  };

  const h = buildHarness(cfg);
  assert.ok(h.cases.length > 0, "expected cases");
  assert.ok(h.cases.length <= 35);

  for (const c of h.cases) {
    assert.equal(c.expected.kind, "bool", `case ${c.label} expected bool`);
  }

  const src = emit(h);
  for (
    const want of [
      `import { test } from "node:test";`,
      `import assert from "node:assert/strict";`,
      `import * as shenguard from "./shenguard_gen.ts";`,
      `import { Processable } from "./processable";`,
      `Processable(`,
      `mustAmount`,
      `mustTransaction`,
      `mustAccountId`,
      `processable: spec says`,
    ]
  ) {
    assert.ok(
      src.includes(want),
      `emitted source missing ${JSON.stringify(want)}\n--- source ---\n${src}`,
    );
  }
});

test("TestBuildHarnessPayment: header lacks seed stamp when seed=0", () => {
  const sf = parseFile(PAYMENT_SRC);
  const tt = buildTypeTable(sf.datatypes, "./shenguard_gen.ts", "shenguard");
  const h = buildHarness({
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "processable",
    implModule: "./processable",
    implFunc: "Processable",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 6,
    seed: 0,
    randomDraws: 0,
  });
  const src = emit(h);
  assert.ok(!src.includes("seed:"), "seed stamp should be absent for seed=0");
  assert.ok(src.startsWith("// Code generated by shen-derive-ts. DO NOT EDIT."));
});

// --- pair-in-list? : 4-clause define with where guards + recursion ---

const PAIR_SRC = `
(datatype drug-id
  X : string;
  ============
  X : drug-id;)

(datatype contraindication
  DrugA : drug-id;
  DrugB : drug-id;
  ========================
  [DrugA DrugB] : contraindication;)

(define pair-in-list?
  {drug-id --> drug-id --> (list contraindication) --> boolean}
  _ _ [] -> false
  A B [[X Y] | Rest] -> true  where (and (= A X) (= B Y))
  A B [[X Y] | Rest] -> true  where (and (= A Y) (= B X))
  A B [_ | Rest] -> (pair-in-list? A B Rest))
`;

test("pair-in-list?: 4 clauses, direct-match + swap + recursion work via evalDefine", () => {
  const sf = parseFile(PAIR_SRC);
  const def = sf.defines.find((d) => d.name === "pair-in-list?");
  assert.ok(def, "pair-in-list? not found");
  assert.equal(def!.clauses.length, 4);

  const tt = buildTypeTable(
    sf.datatypes,
    "./shenguard_gen.ts",
    "shenguard",
  );
  const base = buildBaseEnv(tt, sf.defines);

  const alice = stringVal("alice");
  const bob = stringVal("bob");
  const pairAB = listVal(alice, bob);
  const pairBA = listVal(bob, alice);
  const pairOther = listVal(stringVal("carol"), stringVal("dave"));

  const cases: { name: string; args: Value[]; want: boolean }[] = [
    { name: "empty", args: [alice, bob, listVal()], want: false },
    { name: "direct", args: [alice, bob, listVal(pairAB)], want: true },
    { name: "swap", args: [alice, bob, listVal(pairBA)], want: true },
    {
      name: "skip then match",
      args: [alice, bob, listVal(pairOther, pairAB)],
      want: true,
    },
    {
      name: "never",
      args: [alice, bob, listVal(pairOther, pairOther)],
      want: false,
    },
  ];

  for (const tc of cases) {
    const got = evalDefine(def!, tc.args, base);
    assert.equal(got.kind, "bool", `${tc.name}: expected bool got ${got.kind}`);
    if (got.kind === "bool") {
      assert.equal(got.val, tc.want, `${tc.name}: want ${tc.want}`);
    }
  }
});

test("pair-in-list?: buildHarness + emit succeed end-to-end", () => {
  const sf = parseFile(PAIR_SRC);
  const tt = buildTypeTable(
    sf.datatypes,
    "./shenguard_gen.ts",
    "shenguard",
  );
  const h = buildHarness({
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "pair-in-list?",
    implModule: "./pair_in_list",
    implFunc: "PairInList",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 20,
    seed: 0,
    randomDraws: 0,
  });
  assert.ok(h.cases.length > 0);
  for (const c of h.cases) {
    assert.equal(c.expected.kind, "bool");
  }
  const src = emit(h);
  for (
    const want of [
      `PairInList(`,
      `mustDrugId`,
      `mustContraindication`,
      `pair-in-list?: spec says`,
    ]
  ) {
    assert.ok(
      src.includes(want),
      `missing ${JSON.stringify(want)}`,
    );
  }
});

// --- seeded sampling determinism ---

const ADD_ONE_SRC = `
(define add-one
  {number --> number}
  X -> (+ X 1))
`;

test("seeded sampling is deterministic and reproducible", () => {
  const sf = parseFile(ADD_ONE_SRC);
  const tt = buildTypeTable(sf.datatypes, "", "");

  const mk = (seed: number) =>
    buildHarness({
      spec: sf,
      tt,
      allDefines: sf.defines,
      funcName: "add-one",
      implModule: "./add_one",
      implFunc: "AddOne",
      importPath: "./shenguard_gen.ts",
      importAlias: "shenguard",
      maxCases: 50,
      seed,
      randomDraws: 0,
    });

  const hDet = mk(0);
  // 6 boundary values → 6 cases.
  assert.equal(hDet.cases.length, 6);

  const hA = mk(42);
  const hB = mk(42);
  // 6 boundary + 8 random draws = 14 cases.
  assert.equal(hA.cases.length, 14);
  assert.equal(hB.cases.length, 14);

  for (let i = 0; i < hA.cases.length; i++) {
    assert.equal(
      hA.cases[i]!.argsTs[0],
      hB.cases[i]!.argsTs[0],
      `case ${i} diverged`,
    );
  }

  // Seed stamp lands in header.
  const src = emit(hA);
  assert.ok(src.includes("seed: 42"));
});

test("seeded run includes at least one sample outside the boundary pool", () => {
  const sf = parseFile(ADD_ONE_SRC);
  const tt = buildTypeTable(sf.datatypes, "", "");
  const h = buildHarness({
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "add-one",
    implModule: "./add_one",
    implFunc: "AddOne",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 50,
    seed: 42,
    randomDraws: 0,
  });
  const boundary = new Set(["0", "1", "-1", "5", "2.5", "100"]);
  const novel = h.cases.some((c) => !boundary.has(c.argsTs[0]!));
  assert.ok(novel, "expected at least one non-boundary sample");
});

// --- wrapper/constrained return types use .val() unwrap ---

const DOUBLE_AMOUNT_SRC = `
(datatype amount
  X : number;
  (>= X 0) : verified;
  ====================
  X : amount;)

(define double-amount
  {amount --> amount}
  A -> (* 2 (val A)))
`;

test("wrapper return type: emit uses got.val() and strictEqual", () => {
  const sf = parseFile(DOUBLE_AMOUNT_SRC);
  const tt = buildTypeTable(
    sf.datatypes,
    "./shenguard_gen.ts",
    "shenguard",
  );
  const h = buildHarness({
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "double-amount",
    implModule: "./double_amount",
    implFunc: "DoubleAmount",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 10,
    seed: 0,
    randomDraws: 0,
  });

  const src = emit(h);
  assert.ok(src.includes("got.val()"), "expected got.val() unwrap");
  assert.ok(src.includes("assert.strictEqual"), "expected strictEqual for primitive");

  // Spot-check: double-amount with arg shenguard.mustAmount(5) should expect 10.
  const case5 = h.cases.find((c) => c.argsTs[0] === "shenguard.mustAmount(5)");
  assert.ok(case5, "expected a case with mustAmount(5)");
  assert.equal(case5!.expectedTs, "10");
});

// --- int vs float output fidelity in tsLiteralFor ---

const IDENT_NUM_SRC = `
(define id-num
  {number --> number}
  X -> X)
`;

test("tsLiteralFor: int prints as integer, float with .0 suffix", () => {
  const sf = parseFile(IDENT_NUM_SRC);
  const tt = buildTypeTable(sf.datatypes, "", "");
  const h = buildHarness({
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "id-num",
    implModule: "./id_num",
    implFunc: "IdNum",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 10,
    seed: 0,
    randomDraws: 0,
  });
  // All 6 boundary samples.
  assert.equal(h.cases.length, 6);
  const expectedLiterals = h.cases.map((c) => c.expectedTs);
  // NUMBER_RAW order: 0,1,-1,5,(float 2.5),100.
  assert.deepEqual(expectedLiterals, ["0", "1", "-1", "5", "2.5", "100"]);
  // The float should remain 2.5. If evaluator had accidentally produced an
  // integer-valued float, we'd see "2" — guard against that.
  assert.ok(expectedLiterals.includes("2.5"));
});

// --- list return: deepStrictEqual ---

const TAIL_SRC = `
(define tail-or-empty
  {(list number) --> (list number)}
  [] -> []
  [_ | Rest] -> Rest)
`;

test("list return type uses deepStrictEqual and emits array literals", () => {
  const sf = parseFile(TAIL_SRC);
  const tt = buildTypeTable(sf.datatypes, "", "");
  const h = buildHarness({
    spec: sf,
    tt,
    allDefines: sf.defines,
    funcName: "tail-or-empty",
    implModule: "./tail",
    implFunc: "TailOrEmpty",
    importPath: "./shenguard_gen.ts",
    importAlias: "shenguard",
    maxCases: 20,
    seed: 0,
    randomDraws: 0,
  });
  assert.ok(h.cases.length > 0);
  for (const c of h.cases) {
    assert.equal(c.expected.kind, "list");
    assert.ok(
      c.expectedTs.startsWith("["),
      `expected array literal, got ${c.expectedTs}`,
    );
  }
  const src = emit(h);
  assert.ok(src.includes("assert.deepStrictEqual"));
});
