// Code generated by shengen from demo/feature-flags/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- FeatureName ---
// Shen: (datatype feature-name)
type FeatureName struct{ v string }

func NewFeatureName(x string) (FeatureName, error) {
	if !(!(x == "")) {
		return FeatureName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return FeatureName{v: x}, nil
}

func (t FeatureName) Val() string { return t.v }


// --- Environment ---
// Shen: (datatype environment)
type Environment struct{ v string }

func NewEnvironment(x string) (Environment, error) {
	if !(map[string]bool{"development": true, "staging": true, "production": true}[x]) {
		return Environment{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return Environment{v: x}, nil
}

func (t Environment) Val() string { return t.v }


// --- RolloutPct ---
// Shen: (datatype rollout-pct)
type RolloutPct struct{ v float64 }

func NewRolloutPct(x float64) (RolloutPct, error) {
	if !(x >= 0) {
		return RolloutPct{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	if !(x <= 100) {
		return RolloutPct{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return RolloutPct{v: x}, nil
}

func (t RolloutPct) Val() float64 { return t.v }


// --- FeatureDependency ---
// Shen: (datatype feature-dependency)
type FeatureDependency struct {
	feature FeatureName
	dependsOn FeatureName
}

func NewFeatureDependency(feature FeatureName, dependsOn FeatureName) FeatureDependency {
	return FeatureDependency{
		feature: feature,
		dependsOn: dependsOn,
	}
}

func (t FeatureDependency) Feature() FeatureName { return t.feature }

func (t FeatureDependency) DependsOn() FeatureName { return t.dependsOn }


// --- FeatureEnabled ---
// Shen: (datatype feature-enabled)
type FeatureEnabled struct {
	name FeatureName
	env Environment
	rollout RolloutPct
}

func NewFeatureEnabled(name FeatureName, env Environment, rollout RolloutPct) FeatureEnabled {
	return FeatureEnabled{
		name: name,
		env: env,
		rollout: rollout,
	}
}

func (t FeatureEnabled) Name() FeatureName { return t.name }

func (t FeatureEnabled) Env() Environment { return t.env }

func (t FeatureEnabled) Rollout() RolloutPct { return t.rollout }


// --- DependencySatisfied ---
// Shen: (datatype dependency-satisfied)
type DependencySatisfied struct {
	dep FeatureDependency
	enabled FeatureEnabled
}

func NewDependencySatisfied(dep FeatureDependency, enabled FeatureEnabled) DependencySatisfied {
	return DependencySatisfied{
		dep: dep,
		enabled: enabled,
	}
}

func (t DependencySatisfied) Dep() FeatureDependency { return t.dep }

func (t DependencySatisfied) Enabled() FeatureEnabled { return t.enabled }


// --- SafeActivation ---
// Shen: (datatype safe-activation)
type SafeActivation struct {
	feature FeatureName
	env Environment
	rollout RolloutPct
	depsSatisfied bool
}

func NewSafeActivation(feature FeatureName, env Environment, rollout RolloutPct, depsSatisfied bool) (SafeActivation, error) {
	if !(depsSatisfied == true) {
		return SafeActivation{}, fmt.Errorf("depsSatisfied must equal true")
	}
	return SafeActivation{
		feature: feature,
		env: env,
		rollout: rollout,
		depsSatisfied: depsSatisfied,
	}, nil
}

func (t SafeActivation) Feature() FeatureName { return t.feature }

func (t SafeActivation) Env() Environment { return t.env }

func (t SafeActivation) Rollout() RolloutPct { return t.rollout }

func (t SafeActivation) DepsSatisfied() bool { return t.depsSatisfied }


// --- EnvAllowed ---
// Shen: (datatype env-allowed)
type EnvAllowed struct {
	feature FeatureName
	env Environment
	isAllowed bool
}

func NewEnvAllowed(feature FeatureName, env Environment, isAllowed bool) (EnvAllowed, error) {
	if !(isAllowed == true) {
		return EnvAllowed{}, fmt.Errorf("isAllowed must equal true")
	}
	return EnvAllowed{
		feature: feature,
		env: env,
		isAllowed: isAllowed,
	}, nil
}

func (t EnvAllowed) Feature() FeatureName { return t.feature }

func (t EnvAllowed) Env() Environment { return t.env }

func (t EnvAllowed) IsAllowed() bool { return t.isAllowed }


// --- GatedActivation ---
// Shen: (datatype gated-activation)
type GatedActivation struct {
	activation SafeActivation
	envGate EnvAllowed
}

func NewGatedActivation(activation SafeActivation, envGate EnvAllowed) GatedActivation {
	return GatedActivation{
		activation: activation,
		envGate: envGate,
	}
}

func (t GatedActivation) Activation() SafeActivation { return t.activation }

func (t GatedActivation) EnvGate() EnvAllowed { return t.envGate }


// --- UserCohort ---
// Shen: (datatype user-cohort)
type UserCohort struct {
	userId string
	hashBucket float64
}

func NewUserCohort(userId string, hashBucket float64) (UserCohort, error) {
	if !(!(userId == "")) {
		return UserCohort{}, fmt.Errorf("not: userId must equal \"\"")
	}
	if !(hashBucket >= 0) {
		return UserCohort{}, fmt.Errorf("hashBucket must be >= 0")
	}
	if !(hashBucket <= 99) {
		return UserCohort{}, fmt.Errorf("hashBucket must be <= 99")
	}
	return UserCohort{
		userId: userId,
		hashBucket: hashBucket,
	}, nil
}

func (t UserCohort) UserId() string { return t.userId }

func (t UserCohort) HashBucket() float64 { return t.hashBucket }


// --- UserInRollout ---
// Shen: (datatype user-in-rollout)
type UserInRollout struct {
	cohort UserCohort
	rollout RolloutPct
}

func NewUserInRollout(cohort UserCohort, rollout RolloutPct) (UserInRollout, error) {
	if !(/* TODO: (< (head (tail Cohort)) Rollout) */ true) {
		return UserInRollout{}, fmt.Errorf("could not resolve comparison")
	}
	return UserInRollout{
		cohort: cohort,
		rollout: rollout,
	}, nil
}

func (t UserInRollout) Cohort() UserCohort { return t.cohort }

func (t UserInRollout) Rollout() RolloutPct { return t.rollout }


// --- FlagEvaluated ---
// Shen: (datatype flag-evaluated)
type FlagEvaluated struct {
	activation GatedActivation
	inRollout UserInRollout
}

func NewFlagEvaluated(activation GatedActivation, inRollout UserInRollout) FlagEvaluated {
	return FlagEvaluated{
		activation: activation,
		inRollout: inRollout,
	}
}

func (t FlagEvaluated) Activation() GatedActivation { return t.activation }

func (t FlagEvaluated) InRollout() UserInRollout { return t.inRollout }


// --- NoDependents ---
// Shen: (datatype no-dependents)
type NoDependents struct {
	feature FeatureName
	activeDependentCount float64
}

func NewNoDependents(feature FeatureName, activeDependentCount float64) (NoDependents, error) {
	if !(activeDependentCount == 0) {
		return NoDependents{}, fmt.Errorf("activeDependentCount must equal 0")
	}
	return NoDependents{
		feature: feature,
		activeDependentCount: activeDependentCount,
	}, nil
}

func (t NoDependents) Feature() FeatureName { return t.feature }

func (t NoDependents) ActiveDependentCount() float64 { return t.activeDependentCount }


// --- SafeRollback ---
// Shen: (datatype safe-rollback)
type SafeRollback struct {
	feature FeatureName
	noDeps NoDependents
}

func NewSafeRollback(feature FeatureName, noDeps NoDependents) SafeRollback {
	return SafeRollback{
		feature: feature,
		noDeps: noDeps,
	}
}

func (t SafeRollback) Feature() FeatureName { return t.feature }

func (t SafeRollback) NoDeps() NoDependents { return t.noDeps }


