// Code generated by shengen-rs from specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Rust level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

mod shenguard {
    use std::fmt;

    #[derive(Debug, Clone)]
    pub struct GuardError {
        pub message: String,
    }

    impl fmt::Display for GuardError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "GuardError: {}", self.message)
        }
    }

    impl std::error::Error for GuardError {}

    // --- CustomerId ---
    // Shen: (datatype customer-id)
    pub struct CustomerId {
        v: String,
    }

    impl CustomerId {
        pub fn new(x: String) -> Self {
            CustomerId { v: x }
        }

        pub fn val(&self) -> &str {
            &self.v
        }
    }

    // --- Sku ---
    // Shen: (datatype sku)
    pub struct Sku {
        v: String,
    }

    impl Sku {
        pub fn new(x: String) -> Self {
            Sku { v: x }
        }

        pub fn val(&self) -> &str {
            &self.v
        }
    }

    // --- CartItem ---
    // Shen: (datatype cart-item)
    pub struct CartItem {
        sku: Sku,
        qty: f64,
    }

    impl CartItem {
        pub fn new(sku: Sku, qty: f64) -> Result<Self, GuardError> {
            if !(qty >= 1.0) {
                return Err(GuardError { message: "qty must be >= 1.0".to_string() });
            }
            Ok(CartItem { sku, qty })
        }

        pub fn sku(&self) -> &Sku {
            &self.sku
        }

        pub fn qty(&self) -> f64 {
            self.qty
        }

    }

    // --- Cart ---
    // Shen: (datatype cart)
    pub struct Cart {
        subtotal: f64,
        customer: CustomerId,
        items: Vec<CartItem>,
    }

    impl Cart {
        pub fn new(subtotal: f64, customer: CustomerId, items: Vec<CartItem>) -> Result<Self, GuardError> {
            if !(subtotal >= 0.0) {
                return Err(GuardError { message: "subtotal must be >= 0.0".to_string() });
            }
            Ok(Cart { subtotal, customer, items })
        }

        pub fn subtotal(&self) -> f64 {
            self.subtotal
        }

        pub fn customer(&self) -> &CustomerId {
            &self.customer
        }

        pub fn items(&self) -> &[CartItem] {
            &self.items
        }

    }

    // --- DiscountEligible ---
    // Shen: (datatype discount-eligible)
    pub struct DiscountEligible {
        cart: Cart,
        item_count: f64,
        min_subtotal: f64,
        min_items: f64,
    }

    impl DiscountEligible {
        pub fn new(cart: Cart, item_count: f64, min_subtotal: f64, min_items: f64) -> Result<Self, GuardError> {
            if !(cart.subtotal() >= min_subtotal) {
                return Err(GuardError { message: "cart.subtotal() must be >= min_subtotal".to_string() });
            }
            if !(item_count >= min_items) {
                return Err(GuardError { message: "item_count must be >= min_items".to_string() });
            }
            Ok(DiscountEligible { cart, item_count, min_subtotal, min_items })
        }

        pub fn cart(&self) -> &Cart {
            &self.cart
        }

        pub fn item_count(&self) -> f64 {
            self.item_count
        }

        pub fn min_subtotal(&self) -> f64 {
            self.min_subtotal
        }

        pub fn min_items(&self) -> f64 {
            self.min_items
        }

    }


    // --- Pure functions translated from (define …) blocks ---
    //
    // The Rust emitter is intentionally conservative: it emits only
    // predicate-style defines that recurse over a single list
    // parameter and have a `[]` base case. Anything more complex is
    // flagged below — Rust's borrow rules make silent corruption far
    // worse than a TODO comment.

    /// Generated from Shen define has-bulk-line?.
    pub fn has_bulk_line(cart_items: &[CartItem]) -> bool {
        for elem in cart_items {
            if elem.qty() >= 5.0 {
                return true;
            }
        }
        false
    }

}
