// Code generated by shengen from demo/consensus-quorum/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- ProposalId ---
// Shen: (datatype proposal-id)
type ProposalId struct{ v string }

func NewProposalId(x string) (ProposalId, error) {
	if !(!(x == "")) {
		return ProposalId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ProposalId{v: x}, nil
}

func (t ProposalId) Val() string { return t.v }


// --- VoterId ---
// Shen: (datatype voter-id)
type VoterId struct{ v string }

func NewVoterId(x string) (VoterId, error) {
	if !(!(x == "")) {
		return VoterId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return VoterId{v: x}, nil
}

func (t VoterId) Val() string { return t.v }


// --- QuorumSize ---
// Shen: (datatype quorum-size)
type QuorumSize struct {
	total float64
	required float64
}

func NewQuorumSize(total float64, required float64) (QuorumSize, error) {
	if !(total > 0) {
		return QuorumSize{}, fmt.Errorf("total must be > 0")
	}
	if !(required > 0) {
		return QuorumSize{}, fmt.Errorf("required must be > 0")
	}
	if !(required <= total) {
		return QuorumSize{}, fmt.Errorf("required must be <= total")
	}
	return QuorumSize{
		total: total,
		required: required,
	}, nil
}

func (t QuorumSize) Total() float64 { return t.total }

func (t QuorumSize) Required() float64 { return t.required }


// --- VoteChoice ---
// Shen: (datatype vote-choice)
type VoteChoice struct{ v string }

func NewVoteChoice(x string) (VoteChoice, error) {
	if !(map[string]bool{"approve": true, "reject": true, "abstain": true}[x]) {
		return VoteChoice{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return VoteChoice{v: x}, nil
}

func (t VoteChoice) Val() string { return t.v }


// --- CastVote ---
// Shen: (datatype cast-vote)
type CastVote struct {
	proposal ProposalId
	voter VoterId
	choice VoteChoice
	timestamp float64
}

func NewCastVote(proposal ProposalId, voter VoterId, choice VoteChoice, timestamp float64) (CastVote, error) {
	if !(timestamp > 0) {
		return CastVote{}, fmt.Errorf("timestamp must be > 0")
	}
	return CastVote{
		proposal: proposal,
		voter: voter,
		choice: choice,
		timestamp: timestamp,
	}, nil
}

func (t CastVote) Proposal() ProposalId { return t.proposal }

func (t CastVote) Voter() VoterId { return t.voter }

func (t CastVote) Choice() VoteChoice { return t.choice }

func (t CastVote) Timestamp() float64 { return t.timestamp }


// --- VoterEligible ---
// Shen: (datatype voter-eligible)
type VoterEligible struct {
	voter VoterId
	proposal ProposalId
	isEligible bool
}

func NewVoterEligible(voter VoterId, proposal ProposalId, isEligible bool) (VoterEligible, error) {
	if !(isEligible == true) {
		return VoterEligible{}, fmt.Errorf("isEligible must equal true")
	}
	return VoterEligible{
		voter: voter,
		proposal: proposal,
		isEligible: isEligible,
	}, nil
}

func (t VoterEligible) Voter() VoterId { return t.voter }

func (t VoterEligible) Proposal() ProposalId { return t.proposal }

func (t VoterEligible) IsEligible() bool { return t.isEligible }


// --- VoteUnique ---
// Shen: (datatype vote-unique)
type VoteUnique struct {
	voter VoterId
	proposal ProposalId
	priorVoteCount float64
}

func NewVoteUnique(voter VoterId, proposal ProposalId, priorVoteCount float64) (VoteUnique, error) {
	if !(priorVoteCount == 0) {
		return VoteUnique{}, fmt.Errorf("priorVoteCount must equal 0")
	}
	return VoteUnique{
		voter: voter,
		proposal: proposal,
		priorVoteCount: priorVoteCount,
	}, nil
}

func (t VoteUnique) Voter() VoterId { return t.voter }

func (t VoteUnique) Proposal() ProposalId { return t.proposal }

func (t VoteUnique) PriorVoteCount() float64 { return t.priorVoteCount }


// --- ValidVote ---
// Shen: (datatype valid-vote)
type ValidVote struct {
	vote CastVote
	eligible VoterEligible
	unique VoteUnique
}

func NewValidVote(vote CastVote, eligible VoterEligible, unique VoteUnique) ValidVote {
	return ValidVote{
		vote: vote,
		eligible: eligible,
		unique: unique,
	}
}

func (t ValidVote) Vote() CastVote { return t.vote }

func (t ValidVote) Eligible() VoterEligible { return t.eligible }

func (t ValidVote) Unique() VoteUnique { return t.unique }


// --- VoteTally ---
// Shen: (datatype vote-tally)
type VoteTally struct {
	proposal ProposalId
	approvals float64
	rejections float64
	abstentions float64
}

func NewVoteTally(proposal ProposalId, approvals float64, rejections float64, abstentions float64) (VoteTally, error) {
	if !(approvals >= 0) {
		return VoteTally{}, fmt.Errorf("approvals must be >= 0")
	}
	if !(rejections >= 0) {
		return VoteTally{}, fmt.Errorf("rejections must be >= 0")
	}
	if !(abstentions >= 0) {
		return VoteTally{}, fmt.Errorf("abstentions must be >= 0")
	}
	return VoteTally{
		proposal: proposal,
		approvals: approvals,
		rejections: rejections,
		abstentions: abstentions,
	}, nil
}

func (t VoteTally) Proposal() ProposalId { return t.proposal }

func (t VoteTally) Approvals() float64 { return t.approvals }

func (t VoteTally) Rejections() float64 { return t.rejections }

func (t VoteTally) Abstentions() float64 { return t.abstentions }


// --- QuorumReached ---
// Shen: (datatype quorum-reached)
type QuorumReached struct {
	tally VoteTally
	quorum QuorumSize
	totalVotes float64
}

func NewQuorumReached(tally VoteTally, quorum QuorumSize, totalVotes float64) (QuorumReached, error) {
	if !(/* TODO: (= TotalVotes (+ (+ (head (tail Tally)) (head (tail (tail Tally)))) (head (tail (tail (tail Tally)))))) */ true) {
		return QuorumReached{}, fmt.Errorf("could not resolve equality")
	}
	if !(/* TODO: (>= TotalVotes (head (tail Quorum))) */ true) {
		return QuorumReached{}, fmt.Errorf("could not resolve comparison")
	}
	return QuorumReached{
		tally: tally,
		quorum: quorum,
		totalVotes: totalVotes,
	}, nil
}

func (t QuorumReached) Tally() VoteTally { return t.tally }

func (t QuorumReached) Quorum() QuorumSize { return t.quorum }

func (t QuorumReached) TotalVotes() float64 { return t.totalVotes }


// --- ProposalApproved ---
// Shen: (datatype proposal-approved)
type ProposalApproved = QuorumReached


// --- ProposalRejected ---
// Shen: (datatype proposal-rejected)
type ProposalRejected = QuorumReached


// --- ExecutionAuthorized ---
// Shen: (datatype execution-authorized)
type ExecutionAuthorized struct {
	approval ProposalApproved
	executedBy VoterId
	timestamp float64
}

func NewExecutionAuthorized(approval ProposalApproved, executedBy VoterId, timestamp float64) (ExecutionAuthorized, error) {
	if !(timestamp > 0) {
		return ExecutionAuthorized{}, fmt.Errorf("timestamp must be > 0")
	}
	return ExecutionAuthorized{
		approval: approval,
		executedBy: executedBy,
		timestamp: timestamp,
	}, nil
}

func (t ExecutionAuthorized) Approval() ProposalApproved { return t.approval }

func (t ExecutionAuthorized) ExecutedBy() VoterId { return t.executedBy }

func (t ExecutionAuthorized) Timestamp() float64 { return t.timestamp }


// --- VetoHolder ---
// Shen: (datatype veto-holder)
type VetoHolder struct {
	voter VoterId
	isVetoHolder bool
}

func NewVetoHolder(voter VoterId, isVetoHolder bool) (VetoHolder, error) {
	if !(isVetoHolder == true) {
		return VetoHolder{}, fmt.Errorf("isVetoHolder must equal true")
	}
	return VetoHolder{
		voter: voter,
		isVetoHolder: isVetoHolder,
	}, nil
}

func (t VetoHolder) Voter() VoterId { return t.voter }

func (t VetoHolder) IsVetoHolder() bool { return t.isVetoHolder }


// --- VetoCast ---
// Shen: (datatype veto-cast)
type VetoCast struct {
	holder VetoHolder
	proposal ProposalId
	reason string
}

func NewVetoCast(holder VetoHolder, proposal ProposalId, reason string) (VetoCast, error) {
	if !(!(reason == "")) {
		return VetoCast{}, fmt.Errorf("not: reason must equal \"\"")
	}
	return VetoCast{
		holder: holder,
		proposal: proposal,
		reason: reason,
	}, nil
}

func (t VetoCast) Holder() VetoHolder { return t.holder }

func (t VetoCast) Proposal() ProposalId { return t.proposal }

func (t VetoCast) Reason() string { return t.reason }


