# The Shen guard tracer must be loaded before the project compiles:
# it rejects %Guard{} literals and Kernel.struct/2 outside the generated
# guard modules. It is generated by shengen-ex (see Makefile `gen`).
Code.require_file("shen/guard_tracer.ex", __DIR__)

defmodule Tenant.MixProject do
  use Mix.Project

  def project do
    [
      app: :tenant,
      version: "0.1.0",
      elixir: "~> 1.17",
      start_permanent: Mix.env() == :prod,
      elixirc_options: [tracers: [Tenant.Shen.GuardTracer]],
      deps: deps(),
      dialyzer: [
        plt_add_apps: [:ex_unit],
        flags: [:error_handling]
      ]
    ]
  end

  def application do
    [extra_applications: [:logger, :crypto]]
  end

  defp deps do
    [
      {:ash, "~> 3.5"},
      # Pure-Elixir SAT solver for Ash policies (no NIF build in CI).
      {:simple_sat, "~> 0.1"},
      # Also an Ash dependency; used by the generated derive properties.
      {:stream_data, "~> 1.1"},
      {:dialyxir, "~> 1.4", only: [:dev, :test], runtime: false}
    ]
  end
end
