// Code generated by shengen-ts from specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the TypeScript level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

// --- CustomerId ---
// Shen: (datatype customer-id)
export class CustomerId {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static createOrThrow(x: string): CustomerId { return new CustomerId(x); }
  static tryCreate(x: string): CustomerId | Error {
    try { return CustomerId.createOrThrow(x); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  val(): string { return this._v; }
  toString(): string { return this._v; }
}
export function mustCustomerId(x: string): CustomerId {
  return CustomerId.createOrThrow(x);
}

// --- Sku ---
// Shen: (datatype sku)
export class Sku {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static createOrThrow(x: string): Sku { return new Sku(x); }
  static tryCreate(x: string): Sku | Error {
    try { return Sku.createOrThrow(x); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  val(): string { return this._v; }
  toString(): string { return this._v; }
}
export function mustSku(x: string): Sku {
  return Sku.createOrThrow(x);
}

// --- CartItem ---
// Shen: (datatype cart-item)
export class CartItem {
  private readonly _sku: Sku;
  private readonly _qty: number;
  private constructor(sku: Sku, qty: number) {
    this._sku = sku;
    this._qty = qty;
  }
  static createOrThrow(sku: Sku, qty: number): CartItem {
    if (!(qty >= 1)) throw new Error(`qty must be >= 1`);
    return new CartItem(sku, qty);
  }
  static tryCreate(sku: Sku, qty: number): CartItem | Error {
    try { return CartItem.createOrThrow(sku, qty); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  sku(): Sku { return this._sku; }
  qty(): number { return this._qty; }
}
export function mustCartItem(sku: Sku, qty: number): CartItem {
  return CartItem.createOrThrow(sku, qty);
}

// --- Cart ---
// Shen: (datatype cart)
export class Cart {
  private readonly _subtotal: number;
  private readonly _customer: CustomerId;
  private readonly _items: CartItem[];
  private constructor(subtotal: number, customer: CustomerId, items: CartItem[]) {
    this._subtotal = subtotal;
    this._customer = customer;
    this._items = items;
  }
  static createOrThrow(subtotal: number, customer: CustomerId, items: CartItem[]): Cart {
    if (!(subtotal >= 0)) throw new Error(`subtotal must be >= 0`);
    return new Cart(subtotal, customer, items);
  }
  static tryCreate(subtotal: number, customer: CustomerId, items: CartItem[]): Cart | Error {
    try { return Cart.createOrThrow(subtotal, customer, items); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  subtotal(): number { return this._subtotal; }
  customer(): CustomerId { return this._customer; }
  items(): CartItem[] { return this._items; }
}
export function mustCart(subtotal: number, customer: CustomerId, items: CartItem[]): Cart {
  return Cart.createOrThrow(subtotal, customer, items);
}

// --- DiscountEligible ---
// Shen: (datatype discount-eligible)
export class DiscountEligible {
  private readonly _cart: Cart;
  private readonly _itemCount: number;
  private readonly _minSubtotal: number;
  private readonly _minItems: number;
  private constructor(cart: Cart, itemCount: number, minSubtotal: number, minItems: number) {
    this._cart = cart;
    this._itemCount = itemCount;
    this._minSubtotal = minSubtotal;
    this._minItems = minItems;
  }
  static createOrThrow(cart: Cart, itemCount: number, minSubtotal: number, minItems: number): DiscountEligible {
    if (!(cart.subtotal() >= minSubtotal)) throw new Error(`cart.subtotal() must be >= minSubtotal`);
    if (!(itemCount >= minItems)) throw new Error(`itemCount must be >= minItems`);
    return new DiscountEligible(cart, itemCount, minSubtotal, minItems);
  }
  static tryCreate(cart: Cart, itemCount: number, minSubtotal: number, minItems: number): DiscountEligible | Error {
    try { return DiscountEligible.createOrThrow(cart, itemCount, minSubtotal, minItems); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  cart(): Cart { return this._cart; }
  itemCount(): number { return this._itemCount; }
  minSubtotal(): number { return this._minSubtotal; }
  minItems(): number { return this._minItems; }
}
export function mustDiscountEligible(cart: Cart, itemCount: number, minSubtotal: number, minItems: number): DiscountEligible {
  return DiscountEligible.createOrThrow(cart, itemCount, minSubtotal, minItems);
}

// --- helpers derived from (define …) blocks ---

// hasBulkLine is generated from Shen define has-bulk-line?
export function hasBulkLine(arg0: CartItem[]): boolean {
  if (arg0.length === 0) {
    return false;
  }
  if (arg0.length > 0) {
    const __p0Head = arg0[0];
    const sku = __p0Head.sku();
    const qty = __p0Head.qty();
    const rest = arg0.slice(1);
    return true;
  }
  throw new Error("shengen-ts: no clause matched in has-bulk-line?");
}

