defmodule Tenant.PolicyTest do
  @moduledoc """
  Ash policies generated by `shengen-ex --ash-out`: the actor must be the
  Shen proof struct itself, issued for the request tenant.
  """
  use ExUnit.Case, async: false

  alias Tenant.{Authn, Authz}
  alias Tenant.Docs.Document

  @secret "test-secret"

  defp ok!({:ok, value}), do: value

  defp principal(user),
    do: user |> Authn.issue_token(@secret) |> Authn.authenticate(@secret) |> ok!()

  setup do
    alice_acme = ok!(Authz.tenant_access(principal("alice"), "acme"))
    bob_globex = ok!(Authz.tenant_access(principal("bob"), "globex"))

    doc =
      Document
      |> Ash.Changeset.for_create(
        :create,
        %{id: "acme-#{System.unique_integer([:positive])}", title: "plan"},
        tenant: "acme",
        actor: alice_acme
      )
      |> Ash.create!()

    %{alice_acme: alice_acme, bob_globex: bob_globex, doc: doc}
  end

  test "reads succeed for a tenant-access proof issued for the request tenant", %{
    alice_acme: actor,
    doc: doc
  } do
    ids = Document |> Ash.read!(tenant: "acme", actor: actor) |> Enum.map(& &1.id)
    assert doc.id in ids
  end

  test "hostile: a proof for another tenant is forbidden", %{bob_globex: bob} do
    assert {:error, %Ash.Error.Forbidden{}} = Ash.read(Document, tenant: "acme", actor: bob)
  end

  test "hostile: a plain map with the same fields is not a proof", %{doc: _doc} do
    fake = %{principal: :anyone, tenant: "acme", is_member: true}
    assert {:error, %Ash.Error.Forbidden{}} = Ash.read(Document, tenant: "acme", actor: fake)
  end

  test "updates need a write-access proof naming the document", %{alice_acme: access, doc: doc} do
    write = access |> Authz.resource_access(doc) |> ok!() |> Authz.write_access() |> ok!()

    assert {:ok, updated} =
             doc
             |> Ash.Changeset.for_update(:update, %{title: "v2"}, actor: write, tenant: "acme")
             |> Ash.update()

    assert updated.title == "v2"

    # A tenant-access proof is not enough to update.
    assert {:error, %Ash.Error.Forbidden{}} =
             doc
             |> Ash.Changeset.for_update(:update, %{title: "v3"}, actor: access, tenant: "acme")
             |> Ash.update()
  end

  test "hostile: a write proof for one document does not unlock another", %{
    alice_acme: access,
    doc: doc
  } do
    other =
      Document
      |> Ash.Changeset.for_create(
        :create,
        %{id: "acme-other-#{System.unique_integer([:positive])}", title: "x"},
        tenant: "acme",
        actor: access
      )
      |> Ash.create!()

    write = access |> Authz.resource_access(doc) |> ok!() |> Authz.write_access() |> ok!()

    assert {:error, %Ash.Error.Forbidden{}} =
             other
             |> Ash.Changeset.for_update(:update, %{title: "pwned"}, actor: write, tenant: "acme")
             |> Ash.update()
  end
end
