// Code generated by shengen from specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package multilang_paired

import (
	"fmt"
)

// --- CustomerId ---
// Shen: (datatype customer-id)
type CustomerId struct{ v string }

func NewCustomerId(x string) CustomerId { return CustomerId{v: x} }

func (t CustomerId) Val() string { return t.v }

func (t CustomerId) String() string { return t.v }


// --- Sku ---
// Shen: (datatype sku)
type Sku struct{ v string }

func NewSku(x string) Sku { return Sku{v: x} }

func (t Sku) Val() string { return t.v }

func (t Sku) String() string { return t.v }


// --- CartItem ---
// Shen: (datatype cart-item)
type CartItem struct {
	sku Sku
	qty float64
}

func NewCartItem(sku Sku, qty float64) (CartItem, error) {
	if !(qty >= 1) {
		return CartItem{}, fmt.Errorf("qty must be >= 1")
	}
	return CartItem{
		sku: sku,
		qty: qty,
	}, nil
}

func (t CartItem) Sku() Sku { return t.sku }

func (t CartItem) Qty() float64 { return t.qty }


// --- Cart ---
// Shen: (datatype cart)
type Cart struct {
	subtotal float64
	customer CustomerId
	items []CartItem
}

func NewCart(subtotal float64, customer CustomerId, items []CartItem) (Cart, error) {
	if !(subtotal >= 0) {
		return Cart{}, fmt.Errorf("subtotal must be >= 0")
	}
	return Cart{
		subtotal: subtotal,
		customer: customer,
		items: items,
	}, nil
}

func (t Cart) Subtotal() float64 { return t.subtotal }

func (t Cart) Customer() CustomerId { return t.customer }

func (t Cart) Items() []CartItem { return t.items }


// --- DiscountEligible ---
// Shen: (datatype discount-eligible)
type DiscountEligible struct {
	cart Cart
	itemCount float64
	minSubtotal float64
	minItems float64
}

func NewDiscountEligible(cart Cart, itemCount float64, minSubtotal float64, minItems float64) (DiscountEligible, error) {
	if !(cart.subtotal >= minSubtotal) {
		return DiscountEligible{}, fmt.Errorf("cart.subtotal must be >= minSubtotal")
	}
	if !(itemCount >= minItems) {
		return DiscountEligible{}, fmt.Errorf("itemCount must be >= minItems")
	}
	return DiscountEligible{
		cart: cart,
		itemCount: itemCount,
		minSubtotal: minSubtotal,
		minItems: minItems,
	}, nil
}

func (t DiscountEligible) Cart() Cart { return t.cart }

func (t DiscountEligible) ItemCount() float64 { return t.itemCount }

func (t DiscountEligible) MinSubtotal() float64 { return t.minSubtotal }

func (t DiscountEligible) MinItems() float64 { return t.minItems }


