// Package codegen lowers shen-derive AST terms to Go source code.
// The lowering is a catamorphism over the AST: each node becomes a Go
// expression or statement. List combinators (map, foldr, foldl, scanl,
// filter) become for-loops; lambdas become closures; primitives map to
// Go operators or small helpers.
package codegen

import (
	"fmt"
	"strings"

	"github.com/pyrex41/Shen-Backpressure/shen-derive/core"
)

// LowerToGo produces a complete Go source file containing one function
// derived from the given term. The term must have a fully monomorphic type.
func LowerToGo(term core.Term, ty core.Type, funcName, pkg string) (string, error) {
	cg := &codegen{counter: 0}

	funcCode, err := cg.genFunc(term, ty, funcName)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	fmt.Fprintf(&buf, "// Code generated by shen-derive. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n", pkg)
	buf.WriteString(funcCode)
	buf.WriteString("\n")

	return buf.String(), nil
}

// LowerExprToGo produces just a Go expression string (no package wrapper).
func LowerExprToGo(term core.Term) string {
	cg := &codegen{}
	return cg.expr(term)
}

type codegen struct {
	counter int
}

func (cg *codegen) fresh(prefix string) string {
	cg.counter++
	return fmt.Sprintf("_%s%d", prefix, cg.counter)
}

// --- Go type rendering ---

// GoType converts a core.Type to a Go type string.
func GoType(t core.Type) string {
	if t == nil {
		return "interface{}"
	}
	switch t := t.(type) {
	case *core.TInt:
		return "int"
	case *core.TBool:
		return "bool"
	case *core.TString:
		return "string"
	case *core.TList:
		return "[]" + GoType(t.Elem)
	case *core.TTuple:
		return fmt.Sprintf("struct{ Fst %s; Snd %s }", GoType(t.Fst), GoType(t.Snd))
	case *core.TFun:
		return fmt.Sprintf("func(%s) %s", GoType(t.Param), GoType(t.Result))
	case *core.TVar:
		return "interface{}"
	}
	return "interface{}"
}

// --- Function generation ---

func (cg *codegen) genFunc(term core.Term, ty core.Type, name string) (string, error) {
	// Collect function parameters by peeling off function types.
	// If the term has matching lambdas, use their param names.
	// Otherwise, generate parameter names for partial applications.
	type param struct {
		name string
		ty   string
	}

	var params []param
	curTerm := term
	curTy := ty

	for {
		ft, ok := curTy.(*core.TFun)
		if !ok {
			break
		}
		if lam, ok := curTerm.(*core.Lam); ok {
			params = append(params, param{name: goIdent(lam.Param), ty: GoType(ft.Param)})
			curTerm = lam.Body
		} else {
			// Partially applied combinator: synthesize a parameter
			pname := cg.fresh("arg")
			params = append(params, param{name: pname, ty: GoType(ft.Param)})
			curTerm = &core.App{Func: curTerm, Arg: &core.Var{Name: pname}}
		}
		curTy = ft.Result
	}

	retTy := GoType(curTy)

	// Generate body
	body := cg.body(curTerm, curTy)

	// Assemble function
	var buf strings.Builder
	fmt.Fprintf(&buf, "\n// %s is derived by shen-derive.\n", name)

	pstrs := make([]string, len(params))
	for i, p := range params {
		pstrs[i] = p.name + " " + p.ty
	}
	fmt.Fprintf(&buf, "func %s(%s) %s {\n", name, strings.Join(pstrs, ", "), retTy)
	buf.WriteString(body)
	buf.WriteString("}\n")

	return buf.String(), nil
}

// body generates the statements inside a function body.
// It tries to recognize combinator patterns and emit efficient loops.
func (cg *codegen) body(term core.Term, retTy core.Type) string {
	// Try combinators that produce clean loop code
	if s, ok := cg.bodyFoldr(term, retTy); ok {
		return s
	}
	if s, ok := cg.bodyFoldl(term, retTy); ok {
		return s
	}
	if s, ok := cg.bodyMap(term, retTy); ok {
		return s
	}
	if s, ok := cg.bodyFilter(term, retTy); ok {
		return s
	}
	if s, ok := cg.bodyScanl(term, retTy); ok {
		return s
	}
	// If-then-else at top level
	if ifE, ok := term.(*core.IfExpr); ok {
		return cg.bodyIf(ifE, retTy)
	}
	// Let binding
	if letE, ok := term.(*core.Let); ok {
		return cg.bodyLet(letE, retTy)
	}
	// Default: return expression
	return "\treturn " + cg.expr(term) + "\n"
}

// --- Combinator body generators ---

// matchApp3 matches App(App(App(f, a), b), c)
func matchApp3(t core.Term) (core.Term, core.Term, core.Term, core.Term, bool) {
	app1, ok := t.(*core.App)
	if !ok {
		return nil, nil, nil, nil, false
	}
	app2, ok := app1.Func.(*core.App)
	if !ok {
		return nil, nil, nil, nil, false
	}
	app3, ok := app2.Func.(*core.App)
	if !ok {
		return nil, nil, nil, nil, false
	}
	return app3.Func, app3.Arg, app2.Arg, app1.Arg, true
}

// matchApp2 matches App(App(f, a), b)
func matchApp2(t core.Term) (core.Term, core.Term, core.Term, bool) {
	app1, ok := t.(*core.App)
	if !ok {
		return nil, nil, nil, false
	}
	app2, ok := app1.Func.(*core.App)
	if !ok {
		return nil, nil, nil, false
	}
	return app2.Func, app2.Arg, app1.Arg, true
}

func isPrim(t core.Term, op core.PrimOp) bool {
	p, ok := t.(*core.Prim)
	return ok && p.Op == op
}

func (cg *codegen) bodyFoldr(term core.Term, retTy core.Type) (string, bool) {
	head, stepFn, initVal, list, ok := matchApp3(term)
	if !ok || !isPrim(head, core.PrimFoldr) {
		return "", false
	}

	xs := cg.fresh("xs")
	acc := cg.fresh("acc")
	idx := cg.fresh("i")

	var buf strings.Builder
	fmt.Fprintf(&buf, "\t%s := %s\n", xs, cg.expr(list))
	fmt.Fprintf(&buf, "\t%s := %s\n", acc, cg.expr(initVal))
	fmt.Fprintf(&buf, "\tfor %s := len(%s) - 1; %s >= 0; %s-- {\n", idx, xs, idx, idx)

	// Try to inline the step function
	if body, elemVar, accVar, ok := uncurryLam2(stepFn); ok {
		fmt.Fprintf(&buf, "\t\t%s := %s[%s]\n", goIdent(elemVar), xs, idx)
		cg.genAssign(&buf, acc, body, goIdent(accVar), acc, goIdent(elemVar), goIdent(elemVar))
	} else if p, ok := stepFn.(*core.Prim); ok && goBinOp(p.Op) != "" {
		elem := cg.fresh("x")
		fmt.Fprintf(&buf, "\t\t%s := %s[%s]\n", elem, xs, idx)
		fmt.Fprintf(&buf, "\t\t%s = (%s %s %s)\n", acc, elem, goBinOp(p.Op), acc)
	} else {
		elem := cg.fresh("x")
		fmt.Fprintf(&buf, "\t\t%s := %s[%s]\n", elem, xs, idx)
		fmt.Fprintf(&buf, "\t\t%s = %s(%s)(%s)\n", acc, cg.expr(stepFn), elem, acc)
	}

	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn %s\n", acc)
	return buf.String(), true
}

func (cg *codegen) bodyFoldl(term core.Term, retTy core.Type) (string, bool) {
	head, stepFn, initVal, list, ok := matchApp3(term)
	if !ok || !isPrim(head, core.PrimFoldl) {
		return "", false
	}

	xs := cg.fresh("xs")
	acc := cg.fresh("acc")
	elem := cg.fresh("x")

	var buf strings.Builder
	fmt.Fprintf(&buf, "\t%s := %s\n", xs, cg.expr(list))
	fmt.Fprintf(&buf, "\t%s := %s\n", acc, cg.expr(initVal))
	fmt.Fprintf(&buf, "\tfor _, %s := range %s {\n", elem, xs)

	if body, accVar, elemVar, ok := uncurryLam2(stepFn); ok {
		cg.genAssign(&buf, acc, body, goIdent(accVar), acc, goIdent(elemVar), elem)
	} else if p, ok := stepFn.(*core.Prim); ok && goBinOp(p.Op) != "" {
		fmt.Fprintf(&buf, "\t\t%s = (%s %s %s)\n", acc, acc, goBinOp(p.Op), elem)
	} else {
		fmt.Fprintf(&buf, "\t\t%s = %s(%s)(%s)\n", acc, cg.expr(stepFn), acc, elem)
	}

	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn %s\n", acc)
	return buf.String(), true
}

func (cg *codegen) bodyMap(term core.Term, retTy core.Type) (string, bool) {
	head, fn, list, ok := matchApp2(term)
	if !ok || !isPrim(head, core.PrimMap) {
		return "", false
	}

	xs := cg.fresh("xs")
	result := cg.fresh("result")
	idx := cg.fresh("i")
	elem := cg.fresh("x")

	sliceTy := GoType(retTy)
	if sliceTy == "interface{}" {
		sliceTy = "[]int"
	}

	var buf strings.Builder
	fmt.Fprintf(&buf, "\t%s := %s\n", xs, cg.expr(list))
	fmt.Fprintf(&buf, "\t%s := make(%s, len(%s))\n", result, sliceTy, xs)
	fmt.Fprintf(&buf, "\tfor %s, %s := range %s {\n", idx, elem, xs)

	if body, paramVar, ok := uncurryLam1(fn); ok {
		fmt.Fprintf(&buf, "\t\t%s[%s] = %s\n", result, idx,
			cg.exprSubst(body, map[string]string{goIdent(paramVar): elem}))
	} else {
		fmt.Fprintf(&buf, "\t\t%s[%s] = %s(%s)\n", result, idx, cg.expr(fn), elem)
	}

	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn %s\n", result)
	return buf.String(), true
}

func (cg *codegen) bodyFilter(term core.Term, retTy core.Type) (string, bool) {
	head, pred, list, ok := matchApp2(term)
	if !ok || !isPrim(head, core.PrimFilter) {
		return "", false
	}

	xs := cg.fresh("xs")
	result := cg.fresh("result")
	elem := cg.fresh("x")

	sliceTy := GoType(retTy)
	if sliceTy == "interface{}" {
		sliceTy = "[]int"
	}

	var buf strings.Builder
	fmt.Fprintf(&buf, "\t%s := %s\n", xs, cg.expr(list))
	fmt.Fprintf(&buf, "\tvar %s %s\n", result, sliceTy)
	fmt.Fprintf(&buf, "\tfor _, %s := range %s {\n", elem, xs)

	if body, paramVar, ok := uncurryLam1(pred); ok {
		fmt.Fprintf(&buf, "\t\tif %s {\n",
			cg.exprSubst(body, map[string]string{goIdent(paramVar): elem}))
	} else {
		fmt.Fprintf(&buf, "\t\tif %s(%s) {\n", cg.expr(pred), elem)
	}

	fmt.Fprintf(&buf, "\t\t\t%s = append(%s, %s)\n", result, result, elem)
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn %s\n", result)
	return buf.String(), true
}

func (cg *codegen) bodyScanl(term core.Term, retTy core.Type) (string, bool) {
	head, stepFn, initVal, list, ok := matchApp3(term)
	if !ok || !isPrim(head, core.PrimScanl) {
		return "", false
	}

	xs := cg.fresh("xs")
	acc := cg.fresh("acc")
	result := cg.fresh("result")
	elem := cg.fresh("x")

	sliceTy := GoType(retTy)
	if sliceTy == "interface{}" {
		sliceTy = "[]int"
	}

	var buf strings.Builder
	fmt.Fprintf(&buf, "\t%s := %s\n", xs, cg.expr(list))
	fmt.Fprintf(&buf, "\t%s := %s\n", acc, cg.expr(initVal))
	fmt.Fprintf(&buf, "\t%s := make(%s, 0, len(%s)+1)\n", result, sliceTy, xs)
	fmt.Fprintf(&buf, "\t%s = append(%s, %s)\n", result, result, acc)
	fmt.Fprintf(&buf, "\tfor _, %s := range %s {\n", elem, xs)

	if body, accVar, elemVar, ok := uncurryLam2(stepFn); ok {
		cg.genAssign(&buf, acc, body, goIdent(accVar), acc, goIdent(elemVar), elem)
	} else if p, ok := stepFn.(*core.Prim); ok && goBinOp(p.Op) != "" {
		fmt.Fprintf(&buf, "\t\t%s = (%s %s %s)\n", acc, acc, goBinOp(p.Op), elem)
	} else {
		fmt.Fprintf(&buf, "\t\t%s = %s(%s)(%s)\n", acc, cg.expr(stepFn), acc, elem)
	}

	fmt.Fprintf(&buf, "\t\t%s = append(%s, %s)\n", result, result, acc)
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn %s\n", result)
	return buf.String(), true
}

func (cg *codegen) bodyIf(ifE *core.IfExpr, retTy core.Type) string {
	var buf strings.Builder
	fmt.Fprintf(&buf, "\tif %s {\n", cg.expr(ifE.Cond))
	buf.WriteString(cg.body(ifE.Then, retTy))
	fmt.Fprintf(&buf, "\t} else {\n")
	buf.WriteString(cg.body(ifE.Else, retTy))
	fmt.Fprintf(&buf, "\t}\n")
	return buf.String()
}

func (cg *codegen) bodyLet(letE *core.Let, retTy core.Type) string {
	var buf strings.Builder
	fmt.Fprintf(&buf, "\t%s := %s\n", goIdent(letE.Name), cg.expr(letE.Bound))
	buf.WriteString(cg.body(letE.Body, retTy))
	return buf.String()
}

// --- Expression generation ---

func (cg *codegen) expr(t core.Term) string {
	return cg.exprSubst(t, nil)
}

func (cg *codegen) exprSubst(t core.Term, subst map[string]string) string {
	switch t := t.(type) {
	case *core.Lit:
		switch t.Kind {
		case core.LitInt:
			return fmt.Sprintf("%d", t.IntVal)
		case core.LitBool:
			if t.BoolVal {
				return "true"
			}
			return "false"
		case core.LitString:
			return fmt.Sprintf("%q", t.StrVal)
		}

	case *core.Var:
		name := goIdent(t.Name)
		if subst != nil {
			if s, ok := subst[name]; ok {
				return s
			}
		}
		return name

	case *core.Prim:
		return cg.exprPrim(t.Op)

	case *core.App:
		// Check for infix binary ops: App(App(Prim(op), lhs), rhs)
		if inner, ok := t.Func.(*core.App); ok {
			if p, ok := inner.Func.(*core.Prim); ok {
				if goOp := goBinOp(p.Op); goOp != "" {
					lhs := cg.exprSubst(inner.Arg, subst)
					rhs := cg.exprSubst(t.Arg, subst)
					return fmt.Sprintf("(%s %s %s)", lhs, goOp, rhs)
				}
				// cons x xs → append([]T{x}, xs...)
				if p.Op == core.PrimCons {
					elem := cg.exprSubst(inner.Arg, subst)
					list := cg.exprSubst(t.Arg, subst)
					elemTy := cg.guessExprType(inner.Arg)
					return fmt.Sprintf("append([]%s{%s}, %s...)", elemTy, elem, list)
				}
			}
		}
		// Compose: App(App(Prim(compose), f), g) applied to x → f(g(x))
		// Detect 3-arg compose: App(App(App(Prim(compose), f), g), x)
		if head, f, g, x, ok := matchApp3(t); ok && isPrim(head, core.PrimCompose) {
			gx := cg.exprSubst(&core.App{Func: g, Arg: x}, subst)
			fExpr := cg.exprSubst(f, subst)
			return fmt.Sprintf("%s(%s)", fExpr, gx)
		}
		// Unary ops
		if p, ok := t.Func.(*core.Prim); ok {
			arg := cg.exprSubst(t.Arg, subst)
			switch p.Op {
			case core.PrimNeg:
				return fmt.Sprintf("(-%s)", arg)
			case core.PrimNot:
				return fmt.Sprintf("(!%s)", arg)
			case core.PrimFst:
				return fmt.Sprintf("%s.Fst", arg)
			case core.PrimSnd:
				return fmt.Sprintf("%s.Snd", arg)
			}
		}
		// Generic application
		fn := cg.exprSubst(t.Func, subst)
		arg := cg.exprSubst(t.Arg, subst)
		return fmt.Sprintf("%s(%s)", fn, arg)

	case *core.Lam:
		// Generate a Go closure
		param := goIdent(t.Param)
		paramTy := "interface{}"
		if t.ParamType != nil {
			paramTy = GoType(t.ParamType)
		}
		body := cg.exprSubst(t.Body, subst)
		// Try to infer return type
		retTy := "interface{}"
		if _, ok := t.Body.(*core.Lam); ok {
			retTy = cg.closureType(t.Body)
		} else {
			retTy = cg.guessExprType(t.Body)
		}
		return fmt.Sprintf("func(%s %s) %s { return %s }", param, paramTy, retTy, body)

	case *core.Let:
		// Wrap in IIFE
		val := cg.exprSubst(t.Bound, subst)
		newSubst := copySubst(subst)
		v := cg.fresh("v")
		newSubst[goIdent(t.Name)] = v
		body := cg.exprSubst(t.Body, newSubst)
		return fmt.Sprintf("func() interface{} { %s := %s; return %s }()", v, val, body)

	case *core.IfExpr:
		cond := cg.exprSubst(t.Cond, subst)
		then := cg.exprSubst(t.Then, subst)
		els := cg.exprSubst(t.Else, subst)
		retTy := cg.guessExprType(t.Then)
		return fmt.Sprintf("func() %s { if %s { return %s }; return %s }()", retTy, cond, then, els)

	case *core.ListLit:
		elems := make([]string, len(t.Elems))
		for i, e := range t.Elems {
			elems[i] = cg.exprSubst(e, subst)
		}
		elemTy := cg.guessExprType(t)
		return "[]" + elemTy + "{" + strings.Join(elems, ", ") + "}"

	case *core.TupleLit:
		fst := cg.exprSubst(t.Fst, subst)
		snd := cg.exprSubst(t.Snd, subst)
		fstTy := cg.guessExprType(t.Fst)
		sndTy := cg.guessExprType(t.Snd)
		return fmt.Sprintf("struct{ Fst %s; Snd %s }{%s, %s}", fstTy, sndTy, fst, snd)
	}

	return fmt.Sprintf("/* TODO: %T */", t)
}

// genAssign generates an assignment statement for acc inside a loop body.
// If the lambda body is an if-then-else, generates clean if/else.
// bodyTerm is the lambda body, and we substitute accOld→accVar, elemOld→elemVar.
func (cg *codegen) genAssign(buf *strings.Builder, accVar string, bodyTerm core.Term, accOld, accNew, elemOld, elemNew string) {
	subst := map[string]string{accOld: accNew, elemOld: elemNew}

	if ifE, ok := bodyTerm.(*core.IfExpr); ok {
		cond := cg.exprSubst(ifE.Cond, subst)
		thenExpr := cg.exprSubst(ifE.Then, subst)
		elseExpr := cg.exprSubst(ifE.Else, subst)

		// Optimize: if then-branch is just the accumulator, only emit the else
		if thenExpr == accNew {
			fmt.Fprintf(buf, "\t\tif !(%s) {\n", cond)
			fmt.Fprintf(buf, "\t\t\t%s = %s\n", accVar, elseExpr)
			fmt.Fprintf(buf, "\t\t}\n")
			return
		}
		if elseExpr == accNew {
			fmt.Fprintf(buf, "\t\tif %s {\n", cond)
			fmt.Fprintf(buf, "\t\t\t%s = %s\n", accVar, thenExpr)
			fmt.Fprintf(buf, "\t\t}\n")
			return
		}

		fmt.Fprintf(buf, "\t\tif %s {\n", cond)
		fmt.Fprintf(buf, "\t\t\t%s = %s\n", accVar, thenExpr)
		fmt.Fprintf(buf, "\t\t} else {\n")
		fmt.Fprintf(buf, "\t\t\t%s = %s\n", accVar, elseExpr)
		fmt.Fprintf(buf, "\t\t}\n")
		return
	}

	fmt.Fprintf(buf, "\t\t%s = %s\n", accVar, cg.exprSubst(bodyTerm, subst))
}

// --- Helpers ---

func uncurryLam2(t core.Term) (body core.Term, param1, param2 string, ok bool) {
	lam1, ok1 := t.(*core.Lam)
	if !ok1 {
		return nil, "", "", false
	}
	lam2, ok2 := lam1.Body.(*core.Lam)
	if !ok2 {
		return nil, "", "", false
	}
	return lam2.Body, lam1.Param, lam2.Param, true
}

func uncurryLam1(t core.Term) (body core.Term, param string, ok bool) {
	lam, ok1 := t.(*core.Lam)
	if !ok1 {
		return nil, "", false
	}
	return lam.Body, lam.Param, true
}

func (cg *codegen) exprPrim(op core.PrimOp) string {
	switch op {
	case core.PrimAdd:
		return "func(a, b int) int { return a + b }"
	case core.PrimSub:
		return "func(a, b int) int { return a - b }"
	case core.PrimMul:
		return "func(a, b int) int { return a * b }"
	case core.PrimNil:
		return "[]int{}"
	default:
		return fmt.Sprintf("/* prim:%s */", op)
	}
}

func goBinOp(op core.PrimOp) string {
	switch op {
	case core.PrimAdd:
		return "+"
	case core.PrimSub:
		return "-"
	case core.PrimMul:
		return "*"
	case core.PrimDiv:
		return "/"
	case core.PrimMod:
		return "%"
	case core.PrimEq:
		return "=="
	case core.PrimNeq:
		return "!="
	case core.PrimLt:
		return "<"
	case core.PrimLe:
		return "<="
	case core.PrimGt:
		return ">"
	case core.PrimGe:
		return ">="
	case core.PrimAnd:
		return "&&"
	case core.PrimOr:
		return "||"
	}
	return ""
}

func goIdent(name string) string {
	if len(name) == 0 {
		return name
	}
	// Convert to valid Go identifier
	name = strings.ReplaceAll(name, "'", "_p")
	name = strings.ReplaceAll(name, "-", "_")
	return name
}

func (cg *codegen) closureType(t core.Term) string {
	lam, ok := t.(*core.Lam)
	if !ok {
		return cg.guessExprType(t)
	}
	paramTy := "int"
	if lam.ParamType != nil {
		paramTy = GoType(lam.ParamType)
	}
	retTy := cg.closureType(lam.Body)
	return fmt.Sprintf("func(%s) %s", paramTy, retTy)
}

func (cg *codegen) guessExprType(t core.Term) string {
	switch t := t.(type) {
	case *core.Lit:
		switch t.Kind {
		case core.LitInt:
			return "int"
		case core.LitBool:
			return "bool"
		case core.LitString:
			return "string"
		}
	case *core.Var:
		return "int" // default assumption for variables in arithmetic contexts
	case *core.App:
		if inner, ok := t.Func.(*core.App); ok {
			if p, ok := inner.Func.(*core.Prim); ok {
				switch p.Op {
				case core.PrimAdd, core.PrimSub, core.PrimMul, core.PrimDiv, core.PrimMod:
					return "int"
				case core.PrimEq, core.PrimNeq, core.PrimLt, core.PrimLe, core.PrimGt, core.PrimGe,
					core.PrimAnd, core.PrimOr:
					return "bool"
				}
			}
		}
		if p, ok := t.Func.(*core.Prim); ok {
			switch p.Op {
			case core.PrimNeg:
				return "int"
			case core.PrimNot:
				return "bool"
			}
		}
	case *core.IfExpr:
		return cg.guessExprType(t.Then)
	case *core.Lam:
		return cg.closureType(t)
	case *core.ListLit:
		if len(t.Elems) > 0 {
			return cg.guessExprType(t.Elems[0])
		}
		return "int"
	}
	return "int"
}

func copySubst(s map[string]string) map[string]string {
	out := make(map[string]string)
	if s != nil {
		for k, v := range s {
			out[k] = v
		}
	}
	return out
}
