// shen-rego — Generate Rego (OPA) modules from Shen sequent specs.
//
// This is the middle-tier foreign terminating runtime policy emitter,
// parallel to shen-cedar. Rego is Datalog-derived (Horn-like), more expressive
// than Cedar (aggregation, joins, walk, graph.reachable, document validation)
// while remaining terminating. Excellent for access + infra/CI gating.
//
// Maps almost homomorphically from Shen sequent rules:
//   premise; premise; ... conclusion;   →   conclusion if { premise; premise; ... }
//   Always pair with default conclusion := false (three-valued → explicit default-deny).
//
// Text form (.rego) is primary (for `opa eval`, `conftest`, etc.).
// Input vs data: request-scoped free vars go to `input`; world-scoped to `data`.
// Weaker statics than Cedar → rely on Shen types for well-formedness.
//
// Usage mirrors shen-cedar exactly for parallelism in sb policy / gates.
//
// Future: richer lowering (head/tail for lists, aggregation helpers), input/data
// partition hints via annotations in the .shen, multiple output modules.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	ps "github.com/pyrex41/Shen-Backpressure/policyspec"
)

// Shared Shen-spec parsing + target selection live in the policyspec module
// (one copy for both emitters); these aliases keep local call sites natural.
type (
	SExpr           = ps.SExpr
	VerifiedPremise = ps.VerifiedPremise
	Rule            = ps.Rule
	Datatype        = ps.Datatype
	ruleInfo        = ps.RuleInfo
)

var (
	parseSExpr                = ps.ParseSExpr
	parseDatatypes            = ps.ParseDatatypes
	buildRuleMap              = ps.BuildRuleMap
	buildRuleVariants         = ps.BuildRuleVariants
	collectClauses            = ps.CollectClauses
	collectTransitiveVerified = ps.CollectTransitiveVerified
	collectConclusions        = ps.CollectConclusions
	selectRegoTargets         = ps.SelectTargets
	dirOf                     = ps.DirOf
	isNumericLiteral          = ps.IsNumericLiteral
)

func main() {
	fs := flag.NewFlagSet("shen-rego", flag.ExitOnError)
	spec := fs.String("spec", "specs/core.shen", "path to the .shen spec")
	outRego := fs.String("out-rego", "policies/rego/authz.rego", "output path for primary Rego text module (text is the canonical form for OPA)")
	targetsFlag := fs.String("targets", "", "comma-separated list of target conclusion/block names (e.g. tenant-access,resource-access); empty = infer")
	pkg := fs.String("package", "policy", "Rego package name for the emitted module (e.g. multi_tenant_authz)")
	verbose := fs.Bool("verbose", false, "print parsed targets and symbol summary")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, `shen-rego — Emit Rego (OPA) modules from Shen specs (terminating runtime tier)

Usage:
  shen-rego --spec specs/core.shen --out-rego policies/rego/authz.rego

The emitter lowers the Rego-shaped fragment (snapshot access predicates + aggregations
that fit Datalog). Non-fitting rules cause a clear failure so the Shen spec remains the gate.

Text .rego is primary output (opa eval / conftest friendly). JSON output is secondary if needed.

Flags:
`)
		fs.PrintDefaults()
	}
	_ = fs.Parse(os.Args[1:])

	if *spec == "" {
		fmt.Fprintln(os.Stderr, "shen-rego: --spec is required")
		os.Exit(1)
	}

	content, err := os.ReadFile(*spec)
	if err != nil {
		fmt.Fprintf(os.Stderr, "shen-rego: reading spec: %v\n", err)
		os.Exit(1)
	}

	allConclusions := collectConclusions(string(content))
	requested := selectRegoTargets(*targetsFlag, allConclusions)

	if len(requested) == 0 {
		fmt.Fprintln(os.Stderr, "shen-rego: no Rego targets found (use --targets or add *-access / permit-* rules + /* @policy-target: rego ... */ )")
		// Still succeed with empty (or minimal default-deny module) so gates can be wired.
	}

	if *verbose {
		fmt.Fprintf(os.Stderr, "shen-rego: spec=%s targets=%v (inferred or explicit)\n", *spec, requested)
	}

	// Parse full rules for verified premise lowering (reuses same SExpr + buildRule).
	// Variants index ALL rules per conclusion so sum types lower to a disjunction.
	fullDTs := parseDatatypes(string(content))
	variants := buildRuleVariants(fullDTs)

	module := buildRegoModule(*pkg, requested, variants)

	if err := os.MkdirAll(dirOf(*outRego), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "shen-rego: mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outRego, []byte(module), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "shen-rego: write rego: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated %s from %s (targets: %v)\n",
		*outRego, *spec, requested)
}

// --- Rego emission (text primary) ---

func buildRegoModule(pkgName string, targets []string, variants map[string][]ruleInfo) string {
	var b strings.Builder

	b.WriteString("# Generated by shen-rego from Shen sequent spec.\n")
	b.WriteString("# This is the primary text form for OPA (opa eval, conftest, etc.).\n")
	b.WriteString("# Lattice position: Cedar (SMT) ⊂ Rego (terminating runtime) ⊂ Decidable-Shen-fragment ⊂ full-TC pure-Shen.\n")
	b.WriteString("# Always defaults to false (explicit deny for three-valued logic).\n\n")

	if pkgName == "" {
		pkgName = "policy"
	}
	b.WriteString("package " + pkgName + "\n\n")
	b.WriteString("import rego.v1\n\n")

	if len(targets) == 0 {
		// Emit a safe no-op default module.
		b.WriteString("default allow := false\n\n")
		return b.String()
	}

	for _, t := range targets {
		ruleName := ps.ToSnakeIdent(t)
		b.WriteString(fmt.Sprintf("default %s := false\n", ruleName))

		// One rule body per DNF clause of the (transitive) verified premises.
		// Multiple bodies for the same rule are OR-ed by Rego, which realizes a
		// sum-typed dependency (e.g. authenticated-principal = human ∨ service)
		// as a disjunction instead of dropping a variant.
		clauses := collectClauses(t, variants, map[string]bool{})
		for _, clause := range clauses {
			var bodyLines []string
			for _, v := range clause {
				if line := regoConditionFromVerified(v); line != "" {
					bodyLines = append(bodyLines, "\t"+line)
				}
			}
			if len(bodyLines) == 0 {
				// Fallback: at least a comment; still default-deny.
				bodyLines = append(bodyLines, "\t# no verified premises lowered; default false applies")
			}
			b.WriteString(fmt.Sprintf("%s if {\n", ruleName))
			for _, ln := range bodyLines {
				b.WriteString(ln + "\n")
			}
			b.WriteString("}\n\n")
		}
	}

	return b.String()
}

// regoConditionFromVerified turns e.g. (= IsMember true) into Rego body line:
//
//	input.isMember == true
//
// Uses the same SExpr parser as shen-cedar for fidelity.
func regoConditionFromVerified(v VerifiedPremise) string {
	expr := parseSExpr(v.Raw)
	if !expr.IsCall() {
		return ""
	}
	switch expr.Op() {
	case "=":
		if len(expr.Children) != 3 {
			return ""
		}
		lhs := expr.Children[1]
		rhs := expr.Children[2]
		left := regoExpr(lhs)
		right := regoExpr(rhs)
		if left == "" || right == "" {
			return ""
		}
		return left + " == " + right
	case "not":
		// (not (= A B)) -> A != B. Keeps non-emptiness premises like
		// (not (= Token "")) enforced rather than silently dropped.
		if len(expr.Children) != 2 {
			return ""
		}
		inner := expr.Children[1]
		if !inner.IsCall() || inner.Op() != "=" || len(inner.Children) != 3 {
			return ""
		}
		left := regoExpr(inner.Children[1])
		right := regoExpr(inner.Children[2])
		if left == "" || right == "" {
			return ""
		}
		return left + " != " + right
	case "element?":
		// (element? Elem Coll) -> Elem in Coll (Rego membership), matching the
		// Cedar `Coll.contains(Elem)` lowering. Inline set literals [A B …] are
		// not yet parsed and fall through to "".
		if len(expr.Children) != 3 {
			return ""
		}
		el := regoExpr(expr.Children[1])
		coll := regoExpr(expr.Children[2])
		if el == "" || coll == "" {
			return ""
		}
		return el + " in " + coll
	case ">=", "<=", ">", "<":
		if len(expr.Children) != 3 {
			return ""
		}
		l := regoExpr(expr.Children[1])
		r := regoExpr(expr.Children[2])
		if l == "" || r == "" {
			return ""
		}
		return l + " " + expr.Op() + " " + r
	}
	return ""
}

func regoExpr(s *SExpr) string {
	if s == nil {
		return ""
	}
	if s.IsCall() {
		// v1: direct atoms only for conditions we support.
		return ""
	}
	atom := s.Atom
	if atom == "" {
		return ""
	}
	switch atom {
	case "true":
		return "true"
	case "false":
		return "false"
	}
	if isNumericLiteral(atom) {
		return atom
	}
	if len(atom) >= 2 && strings.HasPrefix(atom, `"`) && strings.HasSuffix(atom, `"`) {
		return atom // already a quoted Rego string literal (e.g. "")
	}
	// Treat as request-scoped input attr (common for verified booleans/flags).
	// IsMember → input.isMember (camel-case, matching the differential harness).
	attr := ps.ToCamelCase(atom)
	return "input." + attr
}
