// Code generated by shengen from demo/shenplane/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- ResourceId ---
// Shen: (datatype resource-id)
type ResourceId struct{ v string }

func NewResourceId(x string) (ResourceId, error) {
	if !(!(x == "")) {
		return ResourceId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ResourceId{v: x}, nil
}

func (t ResourceId) Val() string { return t.v }


// --- ResourceKind ---
// Shen: (datatype resource-kind)
type ResourceKind struct{ v string }

func NewResourceKind(x string) (ResourceKind, error) {
	if !(!(x == "")) {
		return ResourceKind{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ResourceKind{v: x}, nil
}

func (t ResourceKind) Val() string { return t.v }


// --- OwnerRef ---
// Shen: (datatype owner-ref)
type OwnerRef struct{ v string }

func NewOwnerRef(x string) (OwnerRef, error) {
	if !(!(x == "")) {
		return OwnerRef{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return OwnerRef{v: x}, nil
}

func (t OwnerRef) Val() string { return t.v }


// --- Generation ---
// Shen: (datatype generation)
type Generation struct{ v float64 }

func NewGeneration(x float64) (Generation, error) {
	if !(x > 0) {
		return Generation{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return Generation{v: x}, nil
}

func (t Generation) Val() float64 { return t.v }


// --- LifecycleState ---
// Shen: (datatype lifecycle-state)
type LifecycleState struct{ v string }

func NewLifecycleState(x string) (LifecycleState, error) {
	if !(map[string]bool{"pending": true, "creating": true, "ready": true, "updating": true, "deleting": true, "failed": true}[x]) {
		return LifecycleState{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return LifecycleState{v: x}, nil
}

func (t LifecycleState) Val() string { return t.v }


// --- ResourceHandle ---
// Shen: (datatype resource-handle)
type ResourceHandle struct {
	id ResourceId
	kind ResourceKind
	owner OwnerRef
	gen Generation
	state LifecycleState
}

func NewResourceHandle(id ResourceId, kind ResourceKind, owner OwnerRef, gen Generation, state LifecycleState) ResourceHandle {
	return ResourceHandle{
		id: id,
		kind: kind,
		owner: owner,
		gen: gen,
		state: state,
	}
}

func (t ResourceHandle) Id() ResourceId { return t.id }

func (t ResourceHandle) Kind() ResourceKind { return t.kind }

func (t ResourceHandle) Owner() OwnerRef { return t.owner }

func (t ResourceHandle) Gen() Generation { return t.gen }

func (t ResourceHandle) State() LifecycleState { return t.state }


// --- CloudRegion ---
// Shen: (datatype cloud-region)
type CloudRegion struct{ v string }

func NewCloudRegion(x string) (CloudRegion, error) {
	if !(/* TODO: ap-northeast-1 us-east-2 us-west-1 eu-west-2 eu-north-1]) */ true) {
		return CloudRegion{}, fmt.Errorf("unhandled premise: %v", x)
	}
	return CloudRegion{v: x}, nil
}

func (t CloudRegion) Val() string { return t.v }


// --- Environment ---
// Shen: (datatype environment)
type Environment struct{ v string }

func NewEnvironment(x string) (Environment, error) {
	if !(map[string]bool{"development": true, "staging": true, "production": true}[x]) {
		return Environment{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return Environment{v: x}, nil
}

func (t Environment) Val() string { return t.v }


// --- SizeTier ---
// Shen: (datatype size-tier)
type SizeTier struct{ v string }

func NewSizeTier(x string) (SizeTier, error) {
	if !(map[string]bool{"small": true, "medium": true, "large": true, "xlarge": true}[x]) {
		return SizeTier{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return SizeTier{v: x}, nil
}

func (t SizeTier) Val() string { return t.v }


// --- TeamName ---
// Shen: (datatype team-name)
type TeamName struct{ v string }

func NewTeamName(x string) (TeamName, error) {
	if !(!(x == "")) {
		return TeamName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return TeamName{v: x}, nil
}

func (t TeamName) Val() string { return t.v }


// --- CostCenter ---
// Shen: (datatype cost-center)
type CostCenter struct{ v string }

func NewCostCenter(x string) (CostCenter, error) {
	if !(!(x == "")) {
		return CostCenter{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return CostCenter{v: x}, nil
}

func (t CostCenter) Val() string { return t.v }


// --- OrgTags ---
// Shen: (datatype org-tags)
type OrgTags struct {
	team TeamName
	costCenter CostCenter
	env Environment
}

func NewOrgTags(team TeamName, costCenter CostCenter, env Environment) OrgTags {
	return OrgTags{
		team: team,
		costCenter: costCenter,
		env: env,
	}
}

func (t OrgTags) Team() TeamName { return t.team }

func (t OrgTags) CostCenter() CostCenter { return t.costCenter }

func (t OrgTags) Env() Environment { return t.env }


// --- EncryptionAlgo ---
// Shen: (datatype encryption-algo)
type EncryptionAlgo struct{ v string }

func NewEncryptionAlgo(x string) (EncryptionAlgo, error) {
	if !(map[string]bool{"aes-256": true, "aes-128": true, "aws-kms": true, "gcp-cmek": true, "azure-keyvault": true}[x]) {
		return EncryptionAlgo{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return EncryptionAlgo{v: x}, nil
}

func (t EncryptionAlgo) Val() string { return t.v }


// --- EncryptionProof ---
// Shen: (datatype encryption-proof)
type EncryptionProof struct {
	algo EncryptionAlgo
	atRest bool
	inTransit bool
}

func NewEncryptionProof(algo EncryptionAlgo, atRest bool, inTransit bool) (EncryptionProof, error) {
	if !(atRest == true) {
		return EncryptionProof{}, fmt.Errorf("atRest must equal true")
	}
	if !(inTransit == true) {
		return EncryptionProof{}, fmt.Errorf("inTransit must equal true")
	}
	return EncryptionProof{
		algo: algo,
		atRest: atRest,
		inTransit: inTransit,
	}, nil
}

func (t EncryptionProof) Algo() EncryptionAlgo { return t.algo }

func (t EncryptionProof) AtRest() bool { return t.atRest }

func (t EncryptionProof) InTransit() bool { return t.inTransit }


// --- NetworkMode ---
// Shen: (datatype network-mode)
type NetworkMode struct{ v string }

func NewNetworkMode(x string) (NetworkMode, error) {
	if !(map[string]bool{"private": true, "private-with-nat": true, "isolated": true}[x]) {
		return NetworkMode{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return NetworkMode{v: x}, nil
}

func (t NetworkMode) Val() string { return t.v }


// --- NetworkProof ---
// Shen: (datatype network-proof)
type NetworkProof struct {
	mode NetworkMode
	publicEndpoint bool
}

func NewNetworkProof(mode NetworkMode, publicEndpoint bool) (NetworkProof, error) {
	if !(publicEndpoint == false) {
		return NetworkProof{}, fmt.Errorf("publicEndpoint must equal false")
	}
	return NetworkProof{
		mode: mode,
		publicEndpoint: publicEndpoint,
	}, nil
}

func (t NetworkProof) Mode() NetworkMode { return t.mode }

func (t NetworkProof) PublicEndpoint() bool { return t.publicEndpoint }


// --- IamScope ---
// Shen: (datatype iam-scope)
type IamScope struct{ v string }

func NewIamScope(x string) (IamScope, error) {
	if !(map[string]bool{"least-privilege": true, "scoped-to-resource": true, "scoped-to-namespace": true}[x]) {
		return IamScope{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return IamScope{v: x}, nil
}

func (t IamScope) Val() string { return t.v }


// --- IamProof ---
// Shen: (datatype iam-proof)
type IamProof struct {
	scope IamScope
	wildcardActions bool
}

func NewIamProof(scope IamScope, wildcardActions bool) (IamProof, error) {
	if !(wildcardActions == false) {
		return IamProof{}, fmt.Errorf("wildcardActions must equal false")
	}
	return IamProof{
		scope: scope,
		wildcardActions: wildcardActions,
	}, nil
}

func (t IamProof) Scope() IamScope { return t.scope }

func (t IamProof) WildcardActions() bool { return t.wildcardActions }


// --- SecurityProof ---
// Shen: (datatype security-proof)
type SecurityProof struct {
	encryption EncryptionProof
	network NetworkProof
	iam IamProof
}

func NewSecurityProof(encryption EncryptionProof, network NetworkProof, iam IamProof) SecurityProof {
	return SecurityProof{
		encryption: encryption,
		network: network,
		iam: iam,
	}
}

func (t SecurityProof) Encryption() EncryptionProof { return t.encryption }

func (t SecurityProof) Network() NetworkProof { return t.network }

func (t SecurityProof) Iam() IamProof { return t.iam }


// --- DbEngine ---
// Shen: (datatype db-engine)
type DbEngine struct{ v string }

func NewDbEngine(x string) (DbEngine, error) {
	if !(map[string]bool{"postgres": true, "mysql": true, "mariadb": true}[x]) {
		return DbEngine{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return DbEngine{v: x}, nil
}

func (t DbEngine) Val() string { return t.v }


// --- StorageGb ---
// Shen: (datatype storage-gb)
type StorageGb struct{ v float64 }

func NewStorageGb(x float64) (StorageGb, error) {
	if !(x >= 10) {
		return StorageGb{}, fmt.Errorf("x must be >= 10: %v", x)
	}
	if !(x <= 10000) {
		return StorageGb{}, fmt.Errorf("x must be <= 10000: %v", x)
	}
	return StorageGb{v: x}, nil
}

func (t StorageGb) Val() float64 { return t.v }


// --- DbClaim ---
// Shen: (datatype db-claim)
type DbClaim struct {
	id ResourceId
	engine DbEngine
	size SizeTier
	storage StorageGb
	region CloudRegion
	tags OrgTags
}

func NewDbClaim(id ResourceId, engine DbEngine, size SizeTier, storage StorageGb, region CloudRegion, tags OrgTags) DbClaim {
	return DbClaim{
		id: id,
		engine: engine,
		size: size,
		storage: storage,
		region: region,
		tags: tags,
	}
}

func (t DbClaim) Id() ResourceId { return t.id }

func (t DbClaim) Engine() DbEngine { return t.engine }

func (t DbClaim) Size() SizeTier { return t.size }

func (t DbClaim) Storage() StorageGb { return t.storage }

func (t DbClaim) Region() CloudRegion { return t.region }

func (t DbClaim) Tags() OrgTags { return t.tags }


// --- SecureDb ---
// Shen: (datatype secure-db)
type SecureDb struct {
	claim DbClaim
	security SecurityProof
}

func NewSecureDb(claim DbClaim, security SecurityProof) SecureDb {
	return SecureDb{
		claim: claim,
		security: security,
	}
}

func (t SecureDb) Claim() DbClaim { return t.claim }

func (t SecureDb) Security() SecurityProof { return t.security }


// --- CacheEngine ---
// Shen: (datatype cache-engine)
type CacheEngine struct{ v string }

func NewCacheEngine(x string) (CacheEngine, error) {
	if !(map[string]bool{"redis": true, "memcached": true, "valkey": true}[x]) {
		return CacheEngine{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return CacheEngine{v: x}, nil
}

func (t CacheEngine) Val() string { return t.v }


// --- CacheClaim ---
// Shen: (datatype cache-claim)
type CacheClaim struct {
	id ResourceId
	engine CacheEngine
	size SizeTier
	region CloudRegion
	tags OrgTags
}

func NewCacheClaim(id ResourceId, engine CacheEngine, size SizeTier, region CloudRegion, tags OrgTags) CacheClaim {
	return CacheClaim{
		id: id,
		engine: engine,
		size: size,
		region: region,
		tags: tags,
	}
}

func (t CacheClaim) Id() ResourceId { return t.id }

func (t CacheClaim) Engine() CacheEngine { return t.engine }

func (t CacheClaim) Size() SizeTier { return t.size }

func (t CacheClaim) Region() CloudRegion { return t.region }

func (t CacheClaim) Tags() OrgTags { return t.tags }


// --- SecureCache ---
// Shen: (datatype secure-cache)
type SecureCache struct {
	claim CacheClaim
	security SecurityProof
}

func NewSecureCache(claim CacheClaim, security SecurityProof) SecureCache {
	return SecureCache{
		claim: claim,
		security: security,
	}
}

func (t SecureCache) Claim() CacheClaim { return t.claim }

func (t SecureCache) Security() SecurityProof { return t.security }


// --- BucketAccess ---
// Shen: (datatype bucket-access)
type BucketAccess struct{ v string }

func NewBucketAccess(x string) (BucketAccess, error) {
	if !(map[string]bool{"private": true, "authenticated-read": true}[x]) {
		return BucketAccess{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return BucketAccess{v: x}, nil
}

func (t BucketAccess) Val() string { return t.v }


// --- BucketClaim ---
// Shen: (datatype bucket-claim)
type BucketClaim struct {
	id ResourceId
	access BucketAccess
	region CloudRegion
	tags OrgTags
}

func NewBucketClaim(id ResourceId, access BucketAccess, region CloudRegion, tags OrgTags) BucketClaim {
	return BucketClaim{
		id: id,
		access: access,
		region: region,
		tags: tags,
	}
}

func (t BucketClaim) Id() ResourceId { return t.id }

func (t BucketClaim) Access() BucketAccess { return t.access }

func (t BucketClaim) Region() CloudRegion { return t.region }

func (t BucketClaim) Tags() OrgTags { return t.tags }


// --- SecureBucket ---
// Shen: (datatype secure-bucket)
type SecureBucket struct {
	claim BucketClaim
	security SecurityProof
}

func NewSecureBucket(claim BucketClaim, security SecurityProof) SecureBucket {
	return SecureBucket{
		claim: claim,
		security: security,
	}
}

func (t SecureBucket) Claim() BucketClaim { return t.claim }

func (t SecureBucket) Security() SecurityProof { return t.security }


// --- CidrBlock ---
// Shen: (datatype cidr-block)
type CidrBlock struct{ v string }

func NewCidrBlock(x string) (CidrBlock, error) {
	if !(!(x == "")) {
		return CidrBlock{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return CidrBlock{v: x}, nil
}

func (t CidrBlock) Val() string { return t.v }


// --- AvailabilityZones ---
// Shen: (datatype availability-zones)
type AvailabilityZones struct{ v float64 }

func NewAvailabilityZones(x float64) (AvailabilityZones, error) {
	if !(count >= 2) {
		return AvailabilityZones{}, fmt.Errorf("count must be >= 2: %v", x)
	}
	return AvailabilityZones{v: x}, nil
}

func (t AvailabilityZones) Val() float64 { return t.v }


// --- NetworkClaim ---
// Shen: (datatype network-claim)
type NetworkClaim struct {
	id ResourceId
	cidr CidrBlock
	aZs AvailabilityZones
	region CloudRegion
	tags OrgTags
}

func NewNetworkClaim(id ResourceId, cidr CidrBlock, aZs AvailabilityZones, region CloudRegion, tags OrgTags) NetworkClaim {
	return NetworkClaim{
		id: id,
		cidr: cidr,
		aZs: aZs,
		region: region,
		tags: tags,
	}
}

func (t NetworkClaim) Id() ResourceId { return t.id }

func (t NetworkClaim) Cidr() CidrBlock { return t.cidr }

func (t NetworkClaim) AZs() AvailabilityZones { return t.aZs }

func (t NetworkClaim) Region() CloudRegion { return t.region }

func (t NetworkClaim) Tags() OrgTags { return t.tags }


// --- CloudResource ---
// Shen: (datatype cloud-resource)
type CloudResource struct {
	handle ResourceHandle
	region CloudRegion
	tags OrgTags
}

func NewCloudResource(handle ResourceHandle, region CloudRegion, tags OrgTags) CloudResource {
	return CloudResource{
		handle: handle,
		region: region,
		tags: tags,
	}
}

func (t CloudResource) Handle() ResourceHandle { return t.handle }

func (t CloudResource) Region() CloudRegion { return t.region }

func (t CloudResource) Tags() OrgTags { return t.tags }


// --- DerivedFrom ---
// Shen: (datatype derived-from)
type DerivedFrom struct {
	resource CloudResource
	claimId ResourceId
}

func NewDerivedFrom(resource CloudResource, claimId ResourceId) DerivedFrom {
	return DerivedFrom{
		resource: resource,
		claimId: claimId,
	}
}

func (t DerivedFrom) Resource() CloudResource { return t.resource }

func (t DerivedFrom) ClaimId() ResourceId { return t.claimId }


// --- SameRegion ---
// Shen: (datatype same-region)
type SameRegion struct {
	a CloudResource
	b CloudResource
}

func NewSameRegion(a CloudResource, b CloudResource) SameRegion {
	return SameRegion{
		a: a,
		b: b,
	}
}

func (t SameRegion) A() CloudResource { return t.a }

func (t SameRegion) B() CloudResource { return t.b }


// --- InNetwork ---
// Shen: (datatype in-network)
type InNetwork struct {
	resource CloudResource
	network NetworkClaim
}

func NewInNetwork(resource CloudResource, network NetworkClaim) InNetwork {
	return InNetwork{
		resource: resource,
		network: network,
	}
}

func (t InNetwork) Resource() CloudResource { return t.resource }

func (t InNetwork) Network() NetworkClaim { return t.network }


// --- DbExpansion ---
// Shen: (datatype db-expansion)
type DbExpansion struct {
	db SecureDb
	instance CloudResource
	subnetGroup CloudResource
	securityGroup CloudResource
	iamRole CloudResource
	regionConsistent SameRegion
	networkBound InNetwork
}

func NewDbExpansion(db SecureDb, instance CloudResource, subnetGroup CloudResource, securityGroup CloudResource, iamRole CloudResource, regionConsistent SameRegion, networkBound InNetwork) DbExpansion {
	return DbExpansion{
		db: db,
		instance: instance,
		subnetGroup: subnetGroup,
		securityGroup: securityGroup,
		iamRole: iamRole,
		regionConsistent: regionConsistent,
		networkBound: networkBound,
	}
}

func (t DbExpansion) Db() SecureDb { return t.db }

func (t DbExpansion) Instance() CloudResource { return t.instance }

func (t DbExpansion) SubnetGroup() CloudResource { return t.subnetGroup }

func (t DbExpansion) SecurityGroup() CloudResource { return t.securityGroup }

func (t DbExpansion) IamRole() CloudResource { return t.iamRole }

func (t DbExpansion) RegionConsistent() SameRegion { return t.regionConsistent }

func (t DbExpansion) NetworkBound() InNetwork { return t.networkBound }


// --- DesiredState ---
// Shen: (datatype desired-state)
type DesiredState struct {
	handle ResourceHandle
	desiredGen Generation
}

func NewDesiredState(handle ResourceHandle, desiredGen Generation) DesiredState {
	return DesiredState{
		handle: handle,
		desiredGen: desiredGen,
	}
}

func (t DesiredState) Handle() ResourceHandle { return t.handle }

func (t DesiredState) DesiredGen() Generation { return t.desiredGen }


// --- ObservedState ---
// Shen: (datatype observed-state)
type ObservedState struct {
	handle ResourceHandle
	observedGen Generation
	ready bool
}

func NewObservedState(handle ResourceHandle, observedGen Generation, ready bool) ObservedState {
	return ObservedState{
		handle: handle,
		observedGen: observedGen,
		ready: ready,
	}
}

func (t ObservedState) Handle() ResourceHandle { return t.handle }

func (t ObservedState) ObservedGen() Generation { return t.observedGen }

func (t ObservedState) Ready() bool { return t.ready }


// --- DriftDetected ---
// Shen: (datatype drift-detected)
type DriftDetected struct {
	desired DesiredState
	observed ObservedState
}

func NewDriftDetected(desired DesiredState, observed ObservedState) DriftDetected {
	return DriftDetected{
		desired: desired,
		observed: observed,
	}
}

func (t DriftDetected) Desired() DesiredState { return t.desired }

func (t DriftDetected) Observed() ObservedState { return t.observed }


// --- ReconcileAction ---
// Shen: (datatype reconcile-action)
type ReconcileAction struct{ v string }

func NewReconcileAction(x string) (ReconcileAction, error) {
	if !(map[string]bool{"create": true, "update": true, "delete": true, "noop": true}[x]) {
		return ReconcileAction{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return ReconcileAction{v: x}, nil
}

func (t ReconcileAction) Val() string { return t.v }


// --- ReconcilePlan ---
// Shen: (datatype reconcile-plan)
type ReconcilePlan struct {
	handle ResourceHandle
	action ReconcileAction
	provenance DerivedFrom
}

func NewReconcilePlan(handle ResourceHandle, action ReconcileAction, provenance DerivedFrom) ReconcilePlan {
	return ReconcilePlan{
		handle: handle,
		action: action,
		provenance: provenance,
	}
}

func (t ReconcilePlan) Handle() ResourceHandle { return t.handle }

func (t ReconcilePlan) Action() ReconcileAction { return t.action }

func (t ReconcilePlan) Provenance() DerivedFrom { return t.provenance }


// --- ReconcileOrder ---
// Shen: (datatype reconcile-order)
type ReconcileOrder struct {
	first ReconcilePlan
	then ReconcilePlan
}

func NewReconcileOrder(first ReconcilePlan, then ReconcilePlan) ReconcileOrder {
	return ReconcileOrder{
		first: first,
		then: then,
	}
}

func (t ReconcileOrder) First() ReconcilePlan { return t.first }

func (t ReconcileOrder) Then() ReconcilePlan { return t.then }


// --- ProviderType ---
// Shen: (datatype provider-type)
type ProviderType struct{ v string }

func NewProviderType(x string) (ProviderType, error) {
	if !(map[string]bool{"aws": true, "gcp": true, "azure": true}[x]) {
		return ProviderType{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return ProviderType{v: x}, nil
}

func (t ProviderType) Val() string { return t.v }


// --- CredentialRef ---
// Shen: (datatype credential-ref)
type CredentialRef struct{ v string }

func NewCredentialRef(x string) (CredentialRef, error) {
	if !(!(x == "")) {
		return CredentialRef{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return CredentialRef{v: x}, nil
}

func (t CredentialRef) Val() string { return t.v }


// --- CredentialExpiry ---
// Shen: (datatype credential-expiry)
type CredentialExpiry struct {
	expiresAt float64
	now float64
}

func NewCredentialExpiry(expiresAt float64, now float64) (CredentialExpiry, error) {
	if !(expiresAt > now) {
		return CredentialExpiry{}, fmt.Errorf("expiresAt must be > now")
	}
	return CredentialExpiry{
		expiresAt: expiresAt,
		now: now,
	}, nil
}

func (t CredentialExpiry) ExpiresAt() float64 { return t.expiresAt }

func (t CredentialExpiry) Now() float64 { return t.now }


// --- ProviderReady ---
// Shen: (datatype provider-ready)
type ProviderReady struct {
	provider ProviderType
	cred CredentialRef
	expiry CredentialExpiry
	healthy bool
}

func NewProviderReady(provider ProviderType, cred CredentialRef, expiry CredentialExpiry, healthy bool) (ProviderReady, error) {
	if !(healthy == true) {
		return ProviderReady{}, fmt.Errorf("healthy must equal true")
	}
	return ProviderReady{
		provider: provider,
		cred: cred,
		expiry: expiry,
		healthy: healthy,
	}, nil
}

func (t ProviderReady) Provider() ProviderType { return t.provider }

func (t ProviderReady) Cred() CredentialRef { return t.cred }

func (t ProviderReady) Expiry() CredentialExpiry { return t.expiry }

func (t ProviderReady) Healthy() bool { return t.healthy }


// --- DeploymentSafe ---
// Shen: (datatype deployment-safe)
type DeploymentSafe struct {
	plan ReconcilePlan
	security SecurityProof
	provider ProviderReady
}

func NewDeploymentSafe(plan ReconcilePlan, security SecurityProof, provider ProviderReady) DeploymentSafe {
	return DeploymentSafe{
		plan: plan,
		security: security,
		provider: provider,
	}
}

func (t DeploymentSafe) Plan() ReconcilePlan { return t.plan }

func (t DeploymentSafe) Security() SecurityProof { return t.security }

func (t DeploymentSafe) Provider() ProviderReady { return t.provider }


