// Code generated by shengen-ts from specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the TypeScript level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

// --- QueryText ---
// Shen: (datatype query-text)
export class QueryText {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static create(x: string): QueryText {
    if (!(x.length > 0)) throw new Error(`x.length must be > 0: ${x}`);
    return new QueryText(x);
  }
  val(): string { return this._v; }
}

// --- Url ---
// Shen: (datatype url)
export class Url {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static create(x: string): Url {
    if (!(x.length > 8)) throw new Error(`x.length must be > 8: ${x}`);
    return new Url(x);
  }
  val(): string { return this._v; }
}

// --- Snippet ---
// Shen: (datatype snippet)
export class Snippet {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static create(x: string): Snippet { return new Snippet(x); }
  val(): string { return this._v; }
  toString(): string { return this._v; }
}

// --- Timestamp ---
// Shen: (datatype timestamp)
export class Timestamp {
  private readonly _v: number;
  private constructor(v: number) { this._v = v; }
  static create(x: number): Timestamp {
    if (!(x > 0)) throw new Error(`x must be > 0: ${x}`);
    return new Timestamp(x);
  }
  val(): number { return this._v; }
}

// --- SearchQuery ---
// Shen: (datatype search-query)
export class SearchQuery {
  private readonly _text: QueryText;
  private readonly _maxResults: number;
  private constructor(text: QueryText, maxResults: number) {
    this._text = text;
    this._maxResults = maxResults;
  }
  static create(text: QueryText, maxResults: number): SearchQuery {
    if (!(maxResults >= 1)) throw new Error(`maxResults must be >= 1`);
    if (!(maxResults <= 20)) throw new Error(`maxResults must be <= 20`);
    return new SearchQuery(text, maxResults);
  }
  text(): QueryText { return this._text; }
  maxResults(): number { return this._maxResults; }
}

// --- SearchHit ---
// Shen: (datatype search-hit)
export class SearchHit {
  private readonly _title: string;
  private readonly _url: Url;
  private readonly _snippet: Snippet;
  private constructor(title: string, url: Url, snippet: Snippet) {
    this._title = title;
    this._url = url;
    this._snippet = snippet;
  }
  static create(title: string, url: Url, snippet: Snippet): SearchHit {
    return new SearchHit(title, url, snippet);
  }
  title(): string { return this._title; }
  url(): Url { return this._url; }
  snippet(): Snippet { return this._snippet; }
}

// --- SearchResult ---
// Shen: (datatype search-result)
export class SearchResult {
  private readonly _query: SearchQuery;
  private readonly _hits: SearchHit[];
  private readonly _ts: Timestamp;
  private constructor(query: SearchQuery, hits: SearchHit[], ts: Timestamp) {
    this._query = query;
    this._hits = hits;
    this._ts = ts;
  }
  static create(query: SearchQuery, hits: SearchHit[], ts: Timestamp): SearchResult {
    return new SearchResult(query, hits, ts);
  }
  query(): SearchQuery { return this._query; }
  hits(): SearchHit[] { return this._hits; }
  ts(): Timestamp { return this._ts; }
}

// --- FetchRequest ---
// Shen: (datatype fetch-request)
export type FetchRequest = Url;

// --- FetchedPage ---
// Shen: (datatype fetched-page)
export class FetchedPage {
  private readonly _url: Url;
  private readonly _content: string;
  private readonly _ts: Timestamp;
  private constructor(url: Url, content: string, ts: Timestamp) {
    this._url = url;
    this._content = content;
    this._ts = ts;
  }
  static create(url: Url, content: string, ts: Timestamp): FetchedPage {
    return new FetchedPage(url, content, ts);
  }
  url(): Url { return this._url; }
  content(): string { return this._content; }
  ts(): Timestamp { return this._ts; }
}

// --- AiPrompt ---
// Shen: (datatype ai-prompt)
export class AiPrompt {
  private readonly _system: string;
  private readonly _user: string;
  private constructor(system: string, user: string) {
    this._system = system;
    this._user = user;
  }
  static create(system: string, user: string): AiPrompt {
    if (!(system.length > 0)) throw new Error(`system.length must be > 0`);
    if (!(user.length > 0)) throw new Error(`user.length must be > 0`);
    return new AiPrompt(system, user);
  }
  system(): string { return this._system; }
  user(): string { return this._user; }
}

// --- AiResponse ---
// Shen: (datatype ai-response)
export class AiResponse {
  private readonly _prompt: AiPrompt;
  private readonly _text: string;
  private readonly _ts: Timestamp;
  private constructor(prompt: AiPrompt, text: string, ts: Timestamp) {
    this._prompt = prompt;
    this._text = text;
    this._ts = ts;
  }
  static create(prompt: AiPrompt, text: string, ts: Timestamp): AiResponse {
    return new AiResponse(prompt, text, ts);
  }
  prompt(): AiPrompt { return this._prompt; }
  text(): string { return this._text; }
  ts(): Timestamp { return this._ts; }
}

// --- GroundedSource ---
// Shen: (datatype grounded-source)
export class GroundedSource {
  private readonly _page: FetchedPage;
  private readonly _hit: SearchHit;
  private constructor(page: FetchedPage, hit: SearchHit) {
    this._page = page;
    this._hit = hit;
  }
  static create(page: FetchedPage, hit: SearchHit): GroundedSource {
    if (!(page.url() === hit.url())) throw new Error(`page.url() must equal hit.url()`);
    return new GroundedSource(page, hit);
  }
  page(): FetchedPage { return this._page; }
  hit(): SearchHit { return this._hit; }
}

// --- ResearchSummary ---
// Shen: (datatype research-summary)
export class ResearchSummary {
  private readonly _query: SearchQuery;
  private readonly _sources: GroundedSource[];
  private readonly _response: AiResponse;
  private constructor(query: SearchQuery, sources: GroundedSource[], response: AiResponse) {
    this._query = query;
    this._sources = sources;
    this._response = response;
  }
  static create(query: SearchQuery, sources: GroundedSource[], response: AiResponse): ResearchSummary {
    return new ResearchSummary(query, sources, response);
  }
  query(): SearchQuery { return this._query; }
  sources(): GroundedSource[] { return this._sources; }
  response(): AiResponse { return this._response; }
}

// --- UiComponentType ---
// Shen: (datatype ui-component-type)
export class UiComponentType {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static create(x: string): UiComponentType { return new UiComponentType(x); }
  val(): string { return this._v; }
  toString(): string { return this._v; }
}

// --- UiTextBlock ---
// Shen: (datatype ui-text-block)
export class UiTextBlock {
  private readonly _content: string;
  private readonly _cssClass: string;
  private constructor(content: string, cssClass: string) {
    this._content = content;
    this._cssClass = cssClass;
  }
  static create(content: string, cssClass: string): UiTextBlock {
    return new UiTextBlock(content, cssClass);
  }
  content(): string { return this._content; }
  cssClass(): string { return this._cssClass; }
}

// --- UiSourceCard ---
// Shen: (datatype ui-source-card)
export class UiSourceCard {
  private readonly _title: string;
  private readonly _url: Url;
  private readonly _snippet: Snippet;
  private readonly _relevance: number;
  private constructor(title: string, url: Url, snippet: Snippet, relevance: number) {
    this._title = title;
    this._url = url;
    this._snippet = snippet;
    this._relevance = relevance;
  }
  static create(title: string, url: Url, snippet: Snippet, relevance: number): UiSourceCard {
    if (!(relevance >= 0)) throw new Error(`relevance must be >= 0`);
    if (!(relevance <= 1)) throw new Error(`relevance must be <= 1`);
    return new UiSourceCard(title, url, snippet, relevance);
  }
  title(): string { return this._title; }
  url(): Url { return this._url; }
  snippet(): Snippet { return this._snippet; }
  relevance(): number { return this._relevance; }
}

// --- UiSearchBar ---
// Shen: (datatype ui-search-bar)
export class UiSearchBar {
  private readonly _placeholder: string;
  private readonly _value: string;
  private constructor(placeholder: string, value: string) {
    this._placeholder = placeholder;
    this._value = value;
  }
  static create(placeholder: string, value: string): UiSearchBar {
    return new UiSearchBar(placeholder, value);
  }
  placeholder(): string { return this._placeholder; }
  value(): string { return this._value; }
}

// --- UiPanel ---
// Shen: (datatype ui-panel)
export class UiPanel {
  private readonly _id: string;
  private readonly _kind: UiComponentType;
  private readonly _children: string[];
  private constructor(id: string, kind: UiComponentType, children: string[]) {
    this._id = id;
    this._kind = kind;
    this._children = children;
  }
  static create(id: string, kind: UiComponentType, children: string[]): UiPanel {
    return new UiPanel(id, kind, children);
  }
  id(): string { return this._id; }
  kind(): UiComponentType { return this._kind; }
  children(): string[] { return this._children; }
}

// --- SafeRender ---
// Shen: (datatype safe-render)
export class SafeRender {
  private readonly _summary: ResearchSummary;
  private readonly _panel: UiPanel;
  private constructor(summary: ResearchSummary, panel: UiPanel) {
    this._summary = summary;
    this._panel = panel;
  }
  static create(summary: ResearchSummary, panel: UiPanel): SafeRender {
    return new SafeRender(summary, panel);
  }
  summary(): ResearchSummary { return this._summary; }
  panel(): UiPanel { return this._panel; }
}

// --- PipelineIdle ---
// Shen: (datatype pipeline-idle)
export class PipelineIdle {
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static create(x: string): PipelineIdle {
    if (!(x === "idle")) throw new Error(`x must equal "idle": ${x}`);
    return new PipelineIdle(x);
  }
  val(): string { return this._v; }
}

// --- PipelineSearching ---
// Shen: (datatype pipeline-searching)
export type PipelineSearching = SearchQuery;

// --- PipelineFetching ---
// Shen: (datatype pipeline-fetching)
export type PipelineFetching = SearchResult;

// --- PipelineGenerating ---
// Shen: (datatype pipeline-generating)
export class PipelineGenerating {
  private readonly _sources: GroundedSource[];
  private readonly _query: SearchQuery;
  private constructor(sources: GroundedSource[], query: SearchQuery) {
    this._sources = sources;
    this._query = query;
  }
  static create(sources: GroundedSource[], query: SearchQuery): PipelineGenerating {
    return new PipelineGenerating(sources, query);
  }
  sources(): GroundedSource[] { return this._sources; }
  query(): SearchQuery { return this._query; }
}

// --- PipelineComplete ---
// Shen: (datatype pipeline-complete)
export type PipelineComplete = SafeRender;

