// Code generated by shen-derive-ts. DO NOT EDIT.
//
// This file checks that SumNonneg matches the Shen spec
// by evaluating the spec on sampled inputs and comparing outputs.

import { test } from "node:test";
import assert from "node:assert/strict";
import * as shenguard from "./guards_gen.js";
import { SumNonneg } from "./sum_nonneg.js";

test("case_00", () => {
  const got = SumNonneg([] as number[]);
  const want = 0;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_01", () => {
  const got = SumNonneg([0]);
  const want = 0;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_02", () => {
  const got = SumNonneg([1]);
  const want = 1;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_03", () => {
  const got = SumNonneg([-1]);
  const want = 0;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_04", () => {
  const got = SumNonneg([5]);
  const want = 5;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_05", () => {
  const got = SumNonneg([2.5]);
  const want = 2.5;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_06", () => {
  const got = SumNonneg([100]);
  const want = 100;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
test("case_07", () => {
  const got = SumNonneg([0, 1, -1]);
  const want = 1;
  assert.strictEqual(got, want, `sum-nonneg: spec says ${JSON.stringify(want)}, impl returned ${JSON.stringify(got)}`);
});
