// Code generated by shen-derive. DO NOT EDIT.
//
// Derived from: processable b0 txs = all (>= 0) (scanl apply b0 txs)
// Via: scanl-fold fusion (Bird, Algebra of Programming, §3.1)
// Side conditions discharged by Shen tc+ and empirical testing.

package payment_derived

// Processable checks whether all running balances remain non-negative
// when applying a sequence of transaction amounts to an initial balance.
//
// Derived from the naive specification:
//   processable b0 txs = all (>= 0) (scanl (\b tx -> b - tx) b0 txs)
//
// Fused into a single-pass fold with O(1) space:
//   processable b0 txs = snd (foldl step (b0, True) txs)
//   where step (bal, ok) tx = let bal' = bal - tx in (bal', ok && bal' >= 0)
func Processable(b0 int, txs []int) bool {
	bal := b0
	ok := true
	for _, tx := range txs {
		bal = bal - tx
		ok = ok && bal >= 0
	}
	return ok
}
