package main

import (
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite golden files in testdata/golden")

func repoRoot(t *testing.T) string {
	t.Helper()
	_, here, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(here), "..", ".."))
}

type goldenCase struct {
	name      string
	spec      string // relative to repo root
	ns        string
	allDefs   bool
	ash       bool
	ashTarget string
}

var goldenCases = []goldenCase{
	{name: "features", spec: "cmd/shengen-ex/testdata/features.shen", ns: "Feat.Shen", allDefs: true},
	{name: "tenant", spec: "examples/phoenix-ash-tenant/specs/core.shen", ns: "Tenant.Shen", ash: true,
		ashTarget: "tenant-access,resource-access,write-access"},
	{name: "multi_tenant_api", spec: "examples/multi-tenant-api/specs/core.shen", ns: "MultiTenant.Shen", ash: true},
	{name: "payment", spec: "examples/payment/specs/core.shen", ns: "Payment.Shen"},
}

// generateAll renders every output for a golden case, keyed by suffix.
func generateAll(t *testing.T, c goldenCase) map[string]string {
	t.Helper()
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, c.spec))
	if err != nil {
		t.Fatal(err)
	}
	types, defines, err := parseSpecContent(string(raw))
	if err != nil {
		t.Fatal(err)
	}
	st := newSymbolTable(c.ns)
	st.Build(types)
	for i := range defines {
		st.Defines[defines[i].Name] = &defines[i]
	}
	opt := genOptions{SpecPath: c.spec, Namespace: c.ns, AllDefines: c.allDefs}
	res, err := generateElixir(types, defines, st, opt)
	if err != nil {
		t.Fatalf("%s: %v", c.name, err)
	}
	if len(res.Warnings) > 0 {
		t.Fatalf("%s: unexpected warnings: %v", c.name, res.Warnings)
	}
	out := map[string]string{
		".guards.ex": res.Code,
		".tracer.ex": generateTracer(res, opt, "lib/guards_gen.ex", "shen/guard_tracer.ex"),
	}
	if c.ash {
		code, _, err := generateAsh(string(raw), st, opt, ashOptions{Targets: c.ashTarget, TenantType: "tenant-id", ResourceType: "resource-id"})
		if err != nil {
			t.Fatalf("%s ash: %v", c.name, err)
		}
		out[".ash.ex"] = code
	}
	return out
}

func checkGolden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", "golden", name)
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing golden %s (run go test -run Golden -update): %v", path, err)
	}
	if string(want) != got {
		t.Errorf("%s differs from golden output; run `go test -run Golden -update` and review the diff", path)
	}
}

func TestGolden(t *testing.T) {
	for _, c := range goldenCases {
		t.Run(c.name, func(t *testing.T) {
			for suffix, code := range generateAll(t, c) {
				checkGolden(t, c.name+suffix, code)
			}
		})
	}
}

func TestGoldenDerive(t *testing.T) {
	root := repoRoot(t)
	cases := []struct {
		name string
		spec string
		o    deriveOptions
	}{
		{"derive_member_of", "examples/phoenix-ash-tenant/specs/core.shen", deriveOptions{
			Func: "member-of?", Namespace: "Tenant.Shen", ImplModule: "Tenant.Authz", ImplFunc: "member_of?", StreamData: true}},
		{"derive_classify", "cmd/shengen-ex/testdata/features.shen", deriveOptions{
			Func: "classify", Namespace: "Feat.Shen", ImplModule: "Feat.Impl", ImplFunc: "classify"}},
		{"derive_allowed_owner", "cmd/shengen-ex/testdata/features.shen", deriveOptions{
			Func: "allowed-owner?", Namespace: "Feat.Shen", ImplModule: "Feat.Impl", ImplFunc: "allowed_owner?", StreamData: true}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(root, c.spec))
			if err != nil {
				t.Fatal(err)
			}
			c.o.SpecPath = c.spec
			c.o.MaxCases, c.o.MaxRuns = 500, 100
			c.o.TestModule = c.o.ImplModule + "." + toPascalCase(strings.TrimRight(fnName(c.o.Func), "?!")) + "SpecTest"
			code, err := generateDeriveTest(string(raw), c.o)
			if err != nil {
				t.Fatal(err)
			}
			checkGolden(t, c.name+".exs", code)
		})
	}
}

func TestDeterministic(t *testing.T) {
	for _, c := range goldenCases {
		a, b := generateAll(t, c), generateAll(t, c)
		for k := range a {
			if a[k] != b[k] {
				t.Errorf("%s%s: two runs produced different output", c.name, k)
			}
		}
	}
}

func TestHeaders(t *testing.T) {
	for _, c := range goldenCases {
		for suffix, code := range generateAll(t, c) {
			if !strings.HasPrefix(code, "# Code generated by shengen-ex from "+c.spec+". DO NOT EDIT.\n") {
				t.Errorf("%s%s: missing DO NOT EDIT header", c.name, suffix)
			}
		}
	}
}

func TestNaming(t *testing.T) {
	for in, want := range map[string]string{
		"IsMember": "is_member", "X": "x", "ResourceTenant": "resource_tenant", "Tx": "tx",
		"JWTToken": "jwt_token", "end": "end_", "Sub2": "sub2",
	} {
		if got := toSnake(in); got != want {
			t.Errorf("toSnake(%q) = %q, want %q", in, got, want)
		}
	}
	for in, want := range map[string]string{
		"member-of?": "member_of?", "string->n": "string_to_n", "auditLog": "audit_log",
		"can-write?": "can_write?", "shen.mod": "shen_mod",
	} {
		if got := fnName(in); got != want {
			t.Errorf("fnName(%q) = %q, want %q", in, got, want)
		}
	}
	if got := elixirAtom("usd"); got != ":usd" {
		t.Errorf("elixirAtom(usd) = %s", got)
	}
	if got := elixirAtom("step-wait"); got != `:"step-wait"` {
		t.Errorf("elixirAtom(step-wait) = %s", got)
	}
}

func TestNegate(t *testing.T) {
	for in, want := range map[string]string{
		`not (x == "")`:           `x == ""`,
		`a == b`:                  `not (a == b)`,
		`not (a) and not (b)`:     `not (not (a) and not (b))`,
		`not (f(x) and (y or z))`: `f(x) and (y or z)`,
	} {
		if got := negate(in); got != want {
			t.Errorf("negate(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseDefine(t *testing.T) {
	_, defs, err := parseSpecContent(`(define classify
  {number --> symbol}
  X -> small where (< X 10)
  [A | B] -> "list"
  _ -> large)`)
	if err != nil {
		t.Fatal(err)
	}
	if len(defs) != 1 || len(defs[0].Clauses) != 3 {
		t.Fatalf("got %+v", defs)
	}
	d := defs[0]
	if d.RetType != "symbol" || len(d.ParamType) != 1 || d.ParamType[0] != "number" {
		t.Errorf("signature: %v --> %s", d.ParamType, d.RetType)
	}
	if d.Clauses[0].Guard == nil || d.Clauses[0].Guard.String() != "(< X 10)" {
		t.Errorf("guard not parsed: %+v", d.Clauses[0])
	}
	if d.Clauses[1].Patterns[0].String() != "[A | B]" || d.Clauses[1].Result.Kind != NStr {
		t.Errorf("clause 2: %s -> %s", d.Clauses[1].Patterns[0], d.Clauses[1].Result)
	}
	if _, _, err := parseSpecContent("(define f\n  X <- (fail))"); err == nil {
		t.Error("backtracking clauses should be rejected")
	}
}

func TestUnsupportedPremiseFailsClosed(t *testing.T) {
	spec := `(datatype odd
  X : number;
  (frobnicate X) : verified;
  ==========================
  X : odd;)`
	types, defines, _ := parseSpecContent(spec)
	st := newSymbolTable("T")
	st.Build(types)
	res, err := generateElixir(types, defines, st, genOptions{SpecPath: "x.shen", Namespace: "T"})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Warnings) != 1 || !strings.Contains(res.Code, "T.Term.fail_closed() ->") ||
		!strings.Contains(res.Code, `{:unsupported_premise, "(frobnicate X)", []}`) {
		t.Fatalf("expected a fail-closed branch, got warnings %v", res.Warnings)
	}
	if _, err := generateElixir(types, defines, st, genOptions{SpecPath: "x.shen", Namespace: "T", Strict: true}); err == nil {
		t.Fatal("--strict should reject unsupported premises")
	}
}

// TestElixirCompileAndSmoke compiles the golden features output with
// elixirc --warnings-as-errors and runs testdata/features_smoke.exs
// against it. Skipped when Elixir is not installed or under -short.
func TestElixirCompileAndSmoke(t *testing.T) {
	if testing.Short() {
		t.Skip("-short")
	}
	if _, err := exec.LookPath("elixirc"); err != nil {
		t.Skip("elixirc not installed")
	}
	dir := t.TempDir()
	out := generateAll(t, goldenCases[0])
	files := map[string]string{
		"guards.ex":  out[".guards.ex"],
		"tracer.ex":  out[".tracer.ex"],
		"runtime.ex": "defmodule Feat.Shen.Runtime do\n  def audit_log(note), do: note != \"\"\nend\n",
	}
	for name, code := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(code), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	ebin := filepath.Join(dir, "ebin")
	os.MkdirAll(ebin, 0o755)
	cmd := exec.Command("elixirc", "--warnings-as-errors", "-o", ebin, "tracer.ex", "runtime.ex", "guards.ex")
	cmd.Dir = dir
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("elixirc failed: %v\n%s", err, b)
	}
	smoke, _ := filepath.Abs(filepath.Join("testdata", "features_smoke.exs"))
	cmd = exec.Command("elixir", "-pa", ebin, smoke)
	b, err := cmd.CombinedOutput()
	if err != nil || !strings.Contains(string(b), "features smoke: ok") {
		t.Fatalf("smoke failed: %v\n%s", err, b)
	}
}
