# Generated by shen-rego from Shen sequent spec.
# This is the primary text form for OPA (opa eval, conftest, etc.).
# Lattice position: Cedar (SMT) ⊂ Rego (terminating runtime) ⊂ Decidable-Shen-fragment ⊂ full-TC pure-Shen.
# Always defaults to false (explicit deny for three-valued logic).

package multi_tenant_authz

import rego.v1

default tenant_access := false
tenant_access if {
	input.isMember == true
	input.sig != ""
	input.exp > 0
	input.x != ""
	input.x != ""
}

tenant_access if {
	input.isMember == true
	input.secret != ""
}

default resource_access := false
resource_access if {
	input.isOwned == true
	input.isMember == true
	input.sig != ""
	input.exp > 0
	input.x != ""
	input.x != ""
}

resource_access if {
	input.isOwned == true
	input.isMember == true
	input.secret != ""
}

