// Code generated by shen-derive. DO NOT EDIT.

package derived

// BalanceFinal is derived by shen-derive.
func BalanceFinal(b0 int, txs []int) int {
	_xs1 := txs
	_acc2 := struct{ Fst int; Snd bool }{b0, (b0 >= 0)}
	for _, _x3 := range _xs1 {
		_acc2 = func() struct{ Fst int; Snd bool } { _v4 := (_acc2.Fst - _x3); return struct{ Fst int; Snd bool }{_v4, (_acc2.Snd && (_v4 >= 0))} }()
	}
	return _acc2.Fst
}
