// Code generated by shen-derive. DO NOT EDIT.

package derived

// CountNonNegative is derived by shen-derive.
func CountNonNegative(_arg1 []int) int {
	_xs2 := _arg1
	_acc3 := 0
	for _, _x4 := range _xs2 {
		if (_x4 >= 0) {
			_acc3 = (_acc3 + 1)
		}
	}
	return _acc3
}
