// Code generated by shen-derive. DO NOT EDIT.

package derived

// FilterPositive is derived by shen-derive.
func FilterPositive(_arg1 []int) []int {
	_xs2 := _arg1
	var _result3 []int
	for _, _x4 := range _xs2 {
		if (_x4 > 0) {
			_result3 = append(_result3, _x4)
		}
	}
	return _result3
}
