// Code generated by shen-derive. DO NOT EDIT.

package derived

// Product is derived by shen-derive.
func Product(_arg1 []int) int {
	_xs2 := _arg1
	_acc3 := 1
	for _, _x4 := range _xs2 {
		_acc3 = (_acc3 * _x4)
	}
	return _acc3
}
