// Code generated by shen-derive. DO NOT EDIT.

package derived

// Sum is derived by shen-derive.
func Sum(_arg1 []int) int {
	_xs2 := _arg1
	_acc3 := 0
	for _, _x4 := range _xs2 {
		_acc3 = (_acc3 + _x4)
	}
	return _acc3
}
