// Code generated by shengen from specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- EmailAddr ---
// Shen: (datatype email-addr)
type EmailAddr struct{ v string }

func NewEmailAddr(x string) EmailAddr { return EmailAddr{v: x} }

func (t EmailAddr) Val() string { return t.v }

func (t EmailAddr) String() string { return t.v }


// --- UserId ---
// Shen: (datatype user-id)
type UserId struct{ v string }

func NewUserId(x string) UserId { return UserId{v: x} }

func (t UserId) Val() string { return t.v }

func (t UserId) String() string { return t.v }


// --- AgeDecade ---
// Shen: (datatype age-decade)
type AgeDecade struct{ v float64 }

func NewAgeDecade(x float64) (AgeDecade, error) {
	if !(x >= 10) {
		return AgeDecade{}, fmt.Errorf("x must be >= 10: %v", x)
	}
	if !(x <= 100) {
		return AgeDecade{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	if !(0 == int(x) % 10) {
		return AgeDecade{}, fmt.Errorf("0 must equal int(x) %% 10: %v", x)
	}
	return AgeDecade{v: x}, nil
}

func (t AgeDecade) Val() float64 { return t.v }


// --- UsState ---
// Shen: (datatype us-state)
type UsState struct{ v string }

func NewUsState(x string) (UsState, error) {
	if !(2 == len(x)) {
		return UsState{}, fmt.Errorf("2 must equal len(x): %v", x)
	}
	return UsState{v: x}, nil
}

func (t UsState) Val() string { return t.v }


// --- Demographics ---
// Shen: (datatype demographics)
type Demographics struct {
	Age AgeDecade
	State UsState
}

func NewDemographics(age AgeDecade, state UsState) Demographics {
	return Demographics{
		Age: age,
		State: state,
	}
}


// --- KnownProfile ---
// Shen: (datatype known-profile)
type KnownProfile struct {
	Id UserId
	Email EmailAddr
	Demo Demographics
}

func NewKnownProfile(id UserId, email EmailAddr, demo Demographics) KnownProfile {
	return KnownProfile{
		Id: id,
		Email: email,
		Demo: demo,
	}
}


// --- UnknownProfile ---
// Shen: (datatype unknown-profile)
type UnknownProfile struct {
	Id UserId
	Email EmailAddr
}

func NewUnknownProfile(id UserId, email EmailAddr) UnknownProfile {
	return UnknownProfile{
		Id: id,
		Email: email,
	}
}


// --- CopyContent ---
// Shen: (datatype copy-content)
type CopyContent struct {
	Body string
	Demo Demographics
}

func NewCopyContent(body string, demo Demographics) CopyContent {
	return CopyContent{
		Body: body,
		Demo: demo,
	}
}


// --- EmailId ---
// Shen: (datatype email-id)
type EmailId struct{ v string }

func NewEmailId(x string) EmailId { return EmailId{v: x} }

func (t EmailId) Val() string { return t.v }

func (t EmailId) String() string { return t.v }


// --- CampaignEmail ---
// Shen: (datatype campaign-email)
type CampaignEmail struct {
	Id EmailId
	Recipient EmailAddr
	Subject string
	CtaUrl string
}

func NewCampaignEmail(id EmailId, recipient EmailAddr, subject string, ctaUrl string) CampaignEmail {
	return CampaignEmail{
		Id: id,
		Recipient: recipient,
		Subject: subject,
		CtaUrl: ctaUrl,
	}
}


// --- CopyDelivery ---
// Shen: (datatype copy-delivery)
type CopyDelivery struct {
	Profile KnownProfile
	Copy CopyContent
}

func NewCopyDelivery(profile KnownProfile, copy CopyContent) (CopyDelivery, error) {
	if !(profile.Demo == copy.Demo) {
		return CopyDelivery{}, fmt.Errorf("profile.Demo must equal copy.Demo")
	}
	return CopyDelivery{
		Profile: profile,
		Copy: copy,
	}, nil
}


// --- PromptRequired ---
// Shen: (datatype prompt-required)
type PromptRequired = UnknownProfile


// --- ProfileUpgrade ---
// Shen: (datatype profile-upgrade)
type ProfileUpgrade struct {
	Old UnknownProfile
	Demo Demographics
}

func NewProfileUpgrade(old UnknownProfile, demo Demographics) ProfileUpgrade {
	return ProfileUpgrade{
		Old: old,
		Demo: demo,
	}
}


// --- SafeCopyView ---
// Shen: (datatype safe-copy-view)
type SafeCopyView = CopyDelivery


// --- SafeCopyViewFromPrompt ---
// Shen: (datatype safe-copy-view-from-prompt)
type SafeCopyViewFromPrompt struct {
	Upgrade ProfileUpgrade
	Copy CopyContent
}

func NewSafeCopyViewFromPrompt(upgrade ProfileUpgrade, copy CopyContent) SafeCopyViewFromPrompt {
	return SafeCopyViewFromPrompt{
		Upgrade: upgrade,
		Copy: copy,
	}
}


