# Code generated by shengen-py from demo/payment/specs/core.shen. DO NOT EDIT.
#
# These types enforce Shen sequent-calculus invariants at the Python level.
# Factory functions are the ONLY way to create these types — bypassing them
# is a violation of the formal spec.

from __future__ import annotations

from dataclasses import dataclass


# --- AccountId ---
# Shen: (datatype account-id)
@dataclass(frozen=True, slots=True)
class AccountId:
    _v: str

    def val(self) -> str:
        return self._v

    def __str__(self) -> str:
        return self._v


def new_account_id(x: str) -> AccountId:
    return AccountId(_v=x)


# --- Amount ---
# Shen: (datatype amount)
@dataclass(frozen=True, slots=True)
class Amount:
    _v: float

    def __post_init__(self) -> None:
        if not (self._v >= 0):
            raise ValueError(f"x must be >= 0: {self._v}")

    def val(self) -> float:
        return self._v


def new_amount(x: float) -> Amount:
    return Amount(_v=x)


# --- Transaction ---
# Shen: (datatype transaction)
@dataclass(frozen=True, slots=True)
class Transaction:
    _amount: Amount
    _from: AccountId
    _to: AccountId

    def amount(self) -> Amount:
        return self._amount

    def from_(self) -> AccountId:
        return self._from

    def to(self) -> AccountId:
        return self._to


def new_transaction(amount: Amount, from_: AccountId, to: AccountId) -> Transaction:
    if not isinstance(amount, Amount):
        raise TypeError(f"amount must be Amount, got {type(amount).__name__}")
    if not isinstance(from_, AccountId):
        raise TypeError(f"from_ must be AccountId, got {type(from_).__name__}")
    if not isinstance(to, AccountId):
        raise TypeError(f"to must be AccountId, got {type(to).__name__}")
    return Transaction(_amount=amount, _from=from_, _to=to)


# --- BalanceChecked ---
# Shen: (datatype balance-invariant)
@dataclass(frozen=True, slots=True)
class BalanceChecked:
    _bal: float
    _tx: Transaction

    def __post_init__(self) -> None:
        if not (self._bal >= self._tx.amount().val()):
            raise ValueError("bal must be >= tx.amount")

    def bal(self) -> float:
        return self._bal

    def tx(self) -> Transaction:
        return self._tx


def new_balance_checked(bal: float, tx: Transaction) -> BalanceChecked:
    if not isinstance(tx, Transaction):
        raise TypeError(f"tx must be Transaction, got {type(tx).__name__}")
    return BalanceChecked(_bal=bal, _tx=tx)


# --- AccountState ---
# Shen: (datatype account-state)
@dataclass(frozen=True, slots=True)
class AccountState:
    _id: AccountId
    _balance: Amount

    def id(self) -> AccountId:
        return self._id

    def balance(self) -> Amount:
        return self._balance


def new_account_state(id: AccountId, balance: Amount) -> AccountState:
    if not isinstance(id, AccountId):
        raise TypeError(f"id must be AccountId, got {type(id).__name__}")
    if not isinstance(balance, Amount):
        raise TypeError(f"balance must be Amount, got {type(balance).__name__}")
    return AccountState(_id=id, _balance=balance)


# --- SafeTransfer ---
# Shen: (datatype safe-transfer)
@dataclass(frozen=True, slots=True)
class SafeTransfer:
    _tx: Transaction
    _check: BalanceChecked

    def tx(self) -> Transaction:
        return self._tx

    def check(self) -> BalanceChecked:
        return self._check


def new_safe_transfer(tx: Transaction, check: BalanceChecked) -> SafeTransfer:
    if not isinstance(tx, Transaction):
        raise TypeError(f"tx must be Transaction, got {type(tx).__name__}")
    if not isinstance(check, BalanceChecked):
        raise TypeError(f"check must be BalanceChecked, got {type(check).__name__}")
    return SafeTransfer(_tx=tx, _check=check)
