# Code generated by shengen-ex derive from specs/core.shen (define visible-titles). DO NOT EDIT.
#
# Spec-equivalence test: Tenant.Authz.visible_titles/2 must agree with the Shen
# definition of visible-titles evaluated in-process by shen-erl (the Shen kernel
# on the BEAM) on a deterministic boundary pool plus StreamData draws.
#
# Oracle location: $SHEN_ERL_EBIN, else $SHEN_ERL_ROOT/ebin, else a
# sibling shen-erl checkout. Signature: {string --> (list (list string)) --> (list string)}
defmodule Tenant.Authz.VisibleTitlesSpecTest do
  use ExUnit.Case, async: false
  use ExUnitProperties

  # shen-erl is put on the code path at runtime (see shen_erl_ebin!/0).
  @compile {:no_warn_undefined, [:shen_erl_global_stores, :shen_erl_kl_primitives, :shen_erl_kl_compiler, :kl_sys, :kl_load]}

  @moduletag :shen_derive
  @spec_path "specs/core.shen"
  @shen_fun :"visible-titles"
  @max_cases 500

  setup_all do
    {:ok, oracle: start_oracle!()}
  end

  test "visible-titles agrees with Tenant.Authz.visible_titles/2 on the boundary pool", %{oracle: oracle} do
    cases = cases()
    assert cases != [], "empty sample pool"

    failures =
      cases
      |> Enum.with_index()
      |> Enum.flat_map(fn {[a1, a2] = args, index} ->
        spec = oracle_call(oracle, args)
        impl = Tenant.Shen.Term.to_shen(Tenant.Authz.visible_titles(a1, a2))
        if spec == impl, do: [], else: [%{case: index, input: args, spec: spec, impl: impl}]
      end)

    assert failures == [],
           "#{length(failures)} of #{length(cases)} cases disagree with the spec:\n" <>
             inspect(Enum.take(failures, 5), pretty: true)
  end

  property "visible-titles agrees with Tenant.Authz.visible_titles/2 on StreamData draws", %{oracle: oracle} do
    check all a1 <- gen_string(), a2 <- gen_list_of_list_of_string(), max_runs: 100 do
      assert oracle_call(oracle, [a1, a2]) == Tenant.Shen.Term.to_shen(Tenant.Authz.visible_titles(a1, a2))
    end
  end

  defp cases do
    product = cartesian([pool_string(), pool_list_of_list_of_string()])
    stride = max(div(length(product), @max_cases), 1)
    product |> Enum.take_every(stride) |> Enum.take(@max_cases)
  end

  defp sample(xs, k) when length(xs) <= k, do: xs
  defp sample(xs, k), do: xs |> Enum.take_every(div(length(xs), k)) |> Enum.take(k)

  defp cartesian([]), do: [[]]
  defp cartesian([pool | rest]), do: for(x <- pool, tail <- cartesian(rest), do: [x | tail])

  # Boundary pools, one per Shen type in the signature (guard types are
  # built through their constructors, so every sample satisfies its premises).
  defp pool_string do
    ["", "a", "b", "tenant-1", "tenant-2", "Tenant-1", " ", "ünïcødé", "admin", "editor", "viewer"]
  end

  defp pool_list_of_string do
    xs = pool_string()
    picks = sample(xs, 8)

    Enum.uniq(
      [[] | Enum.map(picks, &[&1])] ++
        for(x <- sample(xs, 4), y <- sample(xs, 4), do: [x, y]) ++
        Enum.zip_with(xs, Enum.drop(xs, 1), &[&1, &2]) ++ [picks]
    )
  end

  defp pool_list_of_list_of_string do
    xs = pool_list_of_string()
    picks = sample(xs, 8)

    Enum.uniq(
      [[] | Enum.map(picks, &[&1])] ++
        for(x <- sample(xs, 4), y <- sample(xs, 4), do: [x, y]) ++
        Enum.zip_with(xs, Enum.drop(xs, 1), &[&1, &2]) ++ [picks]
    )
  end

  defp gen_string do
    StreamData.one_of([StreamData.member_of(pool_string()), StreamData.string(:printable, max_length: 8)])
  end

  defp gen_list_of_string do
    StreamData.list_of(gen_string(), max_length: 5)
  end

  defp gen_list_of_list_of_string do
    StreamData.list_of(gen_list_of_string(), max_length: 5)
  end

  # --- shen-erl oracle -------------------------------------------------

  defp oracle_call(oracle, args) do
    ref = make_ref()
    send(oracle, {:call, self(), ref, @shen_fun, args})

    receive do
      {^ref, {:ok, value}} -> value
      {^ref, {:error, reason}} -> {:shen_error, reason}
    after
      30_000 -> flunk("shen-erl oracle timed out on #{inspect(args)}")
    end
  end

  defp start_oracle! do
    pid =
      case Process.whereis(:shen_derive_oracle) do
        nil -> spawn_oracle!()
        pid -> pid
      end

    ref = make_ref()
    send(pid, {:load, self(), ref, @spec_path})

    receive do
      {^ref, :ok} -> pid
      {^ref, {:error, reason}} -> flunk("shen-erl could not load #{@spec_path}: #{inspect(reason)}")
    after
      120_000 -> flunk("shen-erl timed out loading #{@spec_path}")
    end
  end

  defp spawn_oracle! do
    Code.prepend_path(shen_erl_ebin!())
    parent = self()

    pid =
      spawn(fn ->
        Process.register(self(), :shen_derive_oracle)
        :shen_erl_global_stores.init()
        {:ok, sink} = StringIO.open("")
        :shen_erl_kl_primitives.set(:"*stoutput*", sink)
        :shen_erl_kl_primitives.set(:"*stinput*", :standard_io)
        :shen_erl_kl_compiler.boot()
        home = String.to_charlist(File.cwd!()) ++ ~c"/"
        :shen_erl_kl_primitives.set(:"*home-directory*", {:string, home})
        send(parent, {:shen_oracle_booted, self()})
        oracle_loop(MapSet.new())
      end)

    receive do
      {:shen_oracle_booted, ^pid} -> pid
    after
      120_000 -> flunk("shen-erl failed to boot")
    end
  end

  defp oracle_loop(loaded) do
    receive do
      {:load, from, ref, path} ->
        if MapSet.member?(loaded, path) do
          send(from, {ref, :ok})
          oracle_loop(loaded)
        else
          result =
            try do
              :kl_sys.tc(:-)
              :kl_load.load({:string, String.to_charlist(path)})
              :ok
            catch
              kind, reason -> {:error, {kind, reason}}
            end

          send(from, {ref, result})
          oracle_loop(if(result == :ok, do: MapSet.put(loaded, path), else: loaded))
        end

      {:call, from, ref, fun, args} ->
        reply =
          try do
            {:ok, {mod, name, _arity}} = :shen_erl_global_stores.get_mfa(fun)
            {:ok, from_kl(apply(mod, name, Enum.map(args, &to_kl/1)))}
          catch
            kind, reason -> {:error, {kind, reason}}
          end

        send(from, {ref, reply})
        oracle_loop(loaded)
    end
  end

  defp to_kl(value) when is_binary(value), do: {:string, String.to_charlist(value)}
  defp to_kl(value) when is_list(value), do: Enum.map(value, &to_kl/1)
  defp to_kl(value), do: value

  defp from_kl({:string, chars}), do: List.to_string(chars)
  defp from_kl(value) when is_list(value), do: Enum.map(value, &from_kl/1)
  defp from_kl(value), do: value

  defp shen_erl_ebin! do
    candidates =
      [
        System.get_env("SHEN_ERL_EBIN"),
        System.get_env("SHEN_ERL_ROOT") && Path.join(System.get_env("SHEN_ERL_ROOT"), "ebin"),
        Path.expand("../shen-erl/ebin"),
        Path.expand("../../../shen-erl/ebin")
      ]
      |> Enum.reject(&is_nil/1)

    Enum.find(candidates, &File.exists?(Path.join(&1, "shen_erl_kl_compiler.beam"))) ||
      flunk("shen-erl not found; set SHEN_ERL_EBIN (tried #{inspect(candidates)})")
  end
end
