// Code generated by shengen from demo/crispr-pipeline/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- GeneName ---
// Shen: (datatype gene-name)
type GeneName struct{ v string }

func NewGeneName(x string) (GeneName, error) {
	if !(!(x == "")) {
		return GeneName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return GeneName{v: x}, nil
}

func (t GeneName) Val() string { return t.v }


// --- Chromosome ---
// Shen: (datatype chromosome)
type Chromosome struct{ v string }

func NewChromosome(x string) (Chromosome, error) {
	if !(!(x == "")) {
		return Chromosome{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return Chromosome{v: x}, nil
}

func (t Chromosome) Val() string { return t.v }


// --- GenomePosition ---
// Shen: (datatype genome-position)
type GenomePosition struct {
	chrom Chromosome
	start float64
	end float64
}

func NewGenomePosition(chrom Chromosome, start float64, end float64) (GenomePosition, error) {
	if !(start >= 0) {
		return GenomePosition{}, fmt.Errorf("start must be >= 0")
	}
	if !(end > start) {
		return GenomePosition{}, fmt.Errorf("end must be > start")
	}
	return GenomePosition{
		chrom: chrom,
		start: start,
		end: end,
	}, nil
}

func (t GenomePosition) Chrom() Chromosome { return t.chrom }

func (t GenomePosition) Start() float64 { return t.start }

func (t GenomePosition) End() float64 { return t.end }


// --- Strand ---
// Shen: (datatype strand)
type Strand struct{ v string }

func NewStrand(x string) (Strand, error) {
	if !(map[string]bool{"sense": true, "antisense": true}[x]) {
		return Strand{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return Strand{v: x}, nil
}

func (t Strand) Val() string { return t.v }


// --- DnaSequence ---
// Shen: (datatype dna-sequence)
type DnaSequence struct{ v string }

func NewDnaSequence(x string) (DnaSequence, error) {
	if !(!(x == "")) {
		return DnaSequence{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return DnaSequence{v: x}, nil
}

func (t DnaSequence) Val() string { return t.v }


// --- GuideLength ---
// Shen: (datatype guide-length)
type GuideLength struct{ v float64 }

func NewGuideLength(x float64) (GuideLength, error) {
	if !(x >= 17) {
		return GuideLength{}, fmt.Errorf("x must be >= 17: %v", x)
	}
	if !(x <= 24) {
		return GuideLength{}, fmt.Errorf("x must be <= 24: %v", x)
	}
	return GuideLength{v: x}, nil
}

func (t GuideLength) Val() float64 { return t.v }


// --- CasVariant ---
// Shen: (datatype cas-variant)
type CasVariant struct{ v string }

func NewCasVariant(x string) (CasVariant, error) {
	if !(map[string]bool{"spCas9": true, "saCas9": true, "cas12a": true, "cas13": true}[x]) {
		return CasVariant{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return CasVariant{v: x}, nil
}

func (t CasVariant) Val() string { return t.v }


// --- PamSequence ---
// Shen: (datatype pam-sequence)
type PamSequence struct{ v string }

func NewPamSequence(x string) (PamSequence, error) {
	if !(!(x == "")) {
		return PamSequence{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return PamSequence{v: x}, nil
}

func (t PamSequence) Val() string { return t.v }


// --- PamValid ---
// Shen: (datatype pam-valid)
type PamValid struct {
	cas CasVariant
	pam PamSequence
	isCorrect bool
}

func NewPamValid(cas CasVariant, pam PamSequence, isCorrect bool) (PamValid, error) {
	if !(isCorrect == true) {
		return PamValid{}, fmt.Errorf("isCorrect must equal true")
	}
	return PamValid{
		cas: cas,
		pam: pam,
		isCorrect: isCorrect,
	}, nil
}

func (t PamValid) Cas() CasVariant { return t.cas }

func (t PamValid) Pam() PamSequence { return t.pam }

func (t PamValid) IsCorrect() bool { return t.isCorrect }


// --- GcContent ---
// Shen: (datatype gc-content)
type GcContent struct{ v float64 }

func NewGcContent(x float64) (GcContent, error) {
	if !(x >= 0) {
		return GcContent{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	if !(x <= 100) {
		return GcContent{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return GcContent{v: x}, nil
}

func (t GcContent) Val() float64 { return t.v }


// --- GcInRange ---
// Shen: (datatype gc-in-range)
type GcInRange = GcContent


// --- FoldingEnergy ---
// Shen: (datatype folding-energy)
type FoldingEnergy struct{ v float64 }

func NewFoldingEnergy(x float64) FoldingEnergy { return FoldingEnergy{v: x} }

func (t FoldingEnergy) Val() float64 { return t.v }


// --- NoSecondaryStructure ---
// Shen: (datatype no-secondary-structure)
type NoSecondaryStructure struct {
	energy FoldingEnergy
	threshold FoldingEnergy
}

func NewNoSecondaryStructure(energy FoldingEnergy, threshold FoldingEnergy) (NoSecondaryStructure, error) {
	if !(energy.Val() >= threshold.Val()) {
		return NoSecondaryStructure{}, fmt.Errorf("energy must be >= threshold")
	}
	return NoSecondaryStructure{
		energy: energy,
		threshold: threshold,
	}, nil
}

func (t NoSecondaryStructure) Energy() FoldingEnergy { return t.energy }

func (t NoSecondaryStructure) Threshold() FoldingEnergy { return t.threshold }


// --- GuideRna ---
// Shen: (datatype guide-rna)
type GuideRna struct {
	sequence DnaSequence
	target GenomePosition
	strand Strand
	length GuideLength
	cas CasVariant
	pamProof PamValid
	gcProof GcInRange
	foldProof NoSecondaryStructure
}

func NewGuideRna(sequence DnaSequence, target GenomePosition, strand Strand, length GuideLength, cas CasVariant, pamProof PamValid, gcProof GcInRange, foldProof NoSecondaryStructure) GuideRna {
	return GuideRna{
		sequence: sequence,
		target: target,
		strand: strand,
		length: length,
		cas: cas,
		pamProof: pamProof,
		gcProof: gcProof,
		foldProof: foldProof,
	}
}

func (t GuideRna) Sequence() DnaSequence { return t.sequence }

func (t GuideRna) Target() GenomePosition { return t.target }

func (t GuideRna) Strand() Strand { return t.strand }

func (t GuideRna) Length() GuideLength { return t.length }

func (t GuideRna) Cas() CasVariant { return t.cas }

func (t GuideRna) PamProof() PamValid { return t.pamProof }

func (t GuideRna) GcProof() GcInRange { return t.gcProof }

func (t GuideRna) FoldProof() NoSecondaryStructure { return t.foldProof }


// --- OffTargetSite ---
// Shen: (datatype off-target-site)
type OffTargetSite struct {
	position GenomePosition
	mismatches float64
	gene string
}

func NewOffTargetSite(position GenomePosition, mismatches float64, gene string) (OffTargetSite, error) {
	if !(mismatches >= 0) {
		return OffTargetSite{}, fmt.Errorf("mismatches must be >= 0")
	}
	return OffTargetSite{
		position: position,
		mismatches: mismatches,
		gene: gene,
	}, nil
}

func (t OffTargetSite) Position() GenomePosition { return t.position }

func (t OffTargetSite) Mismatches() float64 { return t.mismatches }

func (t OffTargetSite) Gene() string { return t.gene }


// --- SpecificityScore ---
// Shen: (datatype specificity-score)
type SpecificityScore struct{ v float64 }

func NewSpecificityScore(x float64) (SpecificityScore, error) {
	if !(x >= 0) {
		return SpecificityScore{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	if !(x <= 100) {
		return SpecificityScore{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return SpecificityScore{v: x}, nil
}

func (t SpecificityScore) Val() float64 { return t.v }


// --- SpecificityThreshold ---
// Shen: (datatype specificity-threshold)
type SpecificityThreshold struct{ v float64 }

func NewSpecificityThreshold(x float64) (SpecificityThreshold, error) {
	if !(x > 0) {
		return SpecificityThreshold{}, fmt.Errorf("x must be > 0: %v", x)
	}
	if !(x <= 100) {
		return SpecificityThreshold{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return SpecificityThreshold{v: x}, nil
}

func (t SpecificityThreshold) Val() float64 { return t.v }


// --- SpecificitySufficient ---
// Shen: (datatype specificity-sufficient)
type SpecificitySufficient struct {
	score SpecificityScore
	threshold SpecificityThreshold
}

func NewSpecificitySufficient(score SpecificityScore, threshold SpecificityThreshold) (SpecificitySufficient, error) {
	if !(score.Val() >= threshold.Val()) {
		return SpecificitySufficient{}, fmt.Errorf("score must be >= threshold")
	}
	return SpecificitySufficient{
		score: score,
		threshold: threshold,
	}, nil
}

func (t SpecificitySufficient) Score() SpecificityScore { return t.score }

func (t SpecificitySufficient) Threshold() SpecificityThreshold { return t.threshold }


// --- EssentialGene ---
// Shen: (datatype essential-gene)
type EssentialGene struct {
	name GeneName
	isEssential bool
}

func NewEssentialGene(name GeneName, isEssential bool) (EssentialGene, error) {
	if !(isEssential == true) {
		return EssentialGene{}, fmt.Errorf("isEssential must equal true")
	}
	return EssentialGene{
		name: name,
		isEssential: isEssential,
	}, nil
}

func (t EssentialGene) Name() GeneName { return t.name }

func (t EssentialGene) IsEssential() bool { return t.isEssential }


// --- EssentialGenesClear ---
// Shen: (datatype essential-genes-clear)
type EssentialGenesClear struct {
	guide GuideRna
	offTargetCount float64
	essentialHits float64
}

func NewEssentialGenesClear(guide GuideRna, offTargetCount float64, essentialHits float64) (EssentialGenesClear, error) {
	if !(offTargetCount >= 0) {
		return EssentialGenesClear{}, fmt.Errorf("offTargetCount must be >= 0")
	}
	if !(essentialHits == 0) {
		return EssentialGenesClear{}, fmt.Errorf("essentialHits must equal 0")
	}
	return EssentialGenesClear{
		guide: guide,
		offTargetCount: offTargetCount,
		essentialHits: essentialHits,
	}, nil
}

func (t EssentialGenesClear) Guide() GuideRna { return t.guide }

func (t EssentialGenesClear) OffTargetCount() float64 { return t.offTargetCount }

func (t EssentialGenesClear) EssentialHits() float64 { return t.essentialHits }


// --- OffTargetSafe ---
// Shen: (datatype off-target-safe)
type OffTargetSafe struct {
	specificity SpecificitySufficient
	essentialClear EssentialGenesClear
}

func NewOffTargetSafe(specificity SpecificitySufficient, essentialClear EssentialGenesClear) OffTargetSafe {
	return OffTargetSafe{
		specificity: specificity,
		essentialClear: essentialClear,
	}
}

func (t OffTargetSafe) Specificity() SpecificitySufficient { return t.specificity }

func (t OffTargetSafe) EssentialClear() EssentialGenesClear { return t.essentialClear }


// --- EditType ---
// Shen: (datatype edit-type)
type EditType struct{ v string }

func NewEditType(x string) (EditType, error) {
	if !(/* TODO: prime-edit epigenetic-mod]) */ true) {
		return EditType{}, fmt.Errorf("unhandled premise: %v", x)
	}
	return EditType{v: x}, nil
}

func (t EditType) Val() string { return t.v }


// --- DonorTemplate ---
// Shen: (datatype donor-template)
type DonorTemplate struct {
	sequence DnaSequence
	homologyArmLeft float64
	homologyArmRight float64
}

func NewDonorTemplate(sequence DnaSequence, homologyArmLeft float64, homologyArmRight float64) (DonorTemplate, error) {
	if !(homologyArmLeft > 0) {
		return DonorTemplate{}, fmt.Errorf("homologyArmLeft must be > 0")
	}
	if !(homologyArmRight > 0) {
		return DonorTemplate{}, fmt.Errorf("homologyArmRight must be > 0")
	}
	return DonorTemplate{
		sequence: sequence,
		homologyArmLeft: homologyArmLeft,
		homologyArmRight: homologyArmRight,
	}, nil
}

func (t DonorTemplate) Sequence() DnaSequence { return t.sequence }

func (t DonorTemplate) HomologyArmLeft() float64 { return t.homologyArmLeft }

func (t DonorTemplate) HomologyArmRight() float64 { return t.homologyArmRight }


// --- BaseChange ---
// Shen: (datatype base-change)
type BaseChange struct {
	from string
	to string
	position float64
}

func NewBaseChange(from string, to string, position float64) (BaseChange, error) {
	if !(map[string]bool{"A": true, "C": true, "G": true, "T": true}[from]) {
		return BaseChange{}, fmt.Errorf("from must be in the valid set")
	}
	if !(map[string]bool{"A": true, "C": true, "G": true, "T": true}[to]) {
		return BaseChange{}, fmt.Errorf("to must be in the valid set")
	}
	if !(!(from == to)) {
		return BaseChange{}, fmt.Errorf("not: from must equal to")
	}
	if !(position >= 0) {
		return BaseChange{}, fmt.Errorf("position must be >= 0")
	}
	return BaseChange{
		from: from,
		to: to,
		position: position,
	}, nil
}

func (t BaseChange) From() string { return t.from }

func (t BaseChange) To() string { return t.to }

func (t BaseChange) Position() float64 { return t.position }


// --- EditSpec ---
// Shen: (datatype edit-spec)
type EditSpec struct {
	guide GuideRna
	type_ EditType
	offTargetSafety OffTargetSafe
}

func NewEditSpec(guide GuideRna, type_ EditType, offTargetSafety OffTargetSafe) EditSpec {
	return EditSpec{
		guide: guide,
		type_: type_,
		offTargetSafety: offTargetSafety,
	}
}

func (t EditSpec) Guide() GuideRna { return t.guide }

func (t EditSpec) Type() EditType { return t.type_ }

func (t EditSpec) OffTargetSafety() OffTargetSafe { return t.offTargetSafety }


// --- ExperimentId ---
// Shen: (datatype experiment-id)
type ExperimentId struct{ v string }

func NewExperimentId(x string) (ExperimentId, error) {
	if !(!(x == "")) {
		return ExperimentId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ExperimentId{v: x}, nil
}

func (t ExperimentId) Val() string { return t.v }


// --- Timestamp ---
// Shen: (datatype timestamp)
type Timestamp struct{ v float64 }

func NewTimestamp(x float64) (Timestamp, error) {
	if !(x > 0) {
		return Timestamp{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return Timestamp{v: x}, nil
}

func (t Timestamp) Val() float64 { return t.v }


// --- OperatorId ---
// Shen: (datatype operator-id)
type OperatorId struct{ v string }

func NewOperatorId(x string) (OperatorId, error) {
	if !(!(x == "")) {
		return OperatorId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return OperatorId{v: x}, nil
}

func (t OperatorId) Val() string { return t.v }


// --- DesignApproved ---
// Shen: (datatype design-approved)
type DesignApproved struct {
	experiment ExperimentId
	spec EditSpec
	approvedBy OperatorId
	approvedAt Timestamp
}

func NewDesignApproved(experiment ExperimentId, spec EditSpec, approvedBy OperatorId, approvedAt Timestamp) DesignApproved {
	return DesignApproved{
		experiment: experiment,
		spec: spec,
		approvedBy: approvedBy,
		approvedAt: approvedAt,
	}
}

func (t DesignApproved) Experiment() ExperimentId { return t.experiment }

func (t DesignApproved) Spec() EditSpec { return t.spec }

func (t DesignApproved) ApprovedBy() OperatorId { return t.approvedBy }

func (t DesignApproved) ApprovedAt() Timestamp { return t.approvedAt }


// --- GuideSynthesized ---
// Shen: (datatype guide-synthesized)
type GuideSynthesized struct {
	design DesignApproved
	synthesizedAt Timestamp
	purity float64
}

func NewGuideSynthesized(design DesignApproved, synthesizedAt Timestamp, purity float64) (GuideSynthesized, error) {
	if !(purity > 0) {
		return GuideSynthesized{}, fmt.Errorf("purity must be > 0")
	}
	if !(purity >= 90) {
		return GuideSynthesized{}, fmt.Errorf("purity must be >= 90")
	}
	return GuideSynthesized{
		design: design,
		synthesizedAt: synthesizedAt,
		purity: purity,
	}, nil
}

func (t GuideSynthesized) Design() DesignApproved { return t.design }

func (t GuideSynthesized) SynthesizedAt() Timestamp { return t.synthesizedAt }

func (t GuideSynthesized) Purity() float64 { return t.purity }


// --- DeliveryMethod ---
// Shen: (datatype delivery-method)
type DeliveryMethod struct{ v string }

func NewDeliveryMethod(x string) (DeliveryMethod, error) {
	if !(map[string]bool{"electroporation": true, "lipofection": true, "viral-vector": true, "rnp": true, "microinjection": true}[x]) {
		return DeliveryMethod{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return DeliveryMethod{v: x}, nil
}

func (t DeliveryMethod) Val() string { return t.v }


// --- CellType ---
// Shen: (datatype cell-type)
type CellType struct{ v string }

func NewCellType(x string) (CellType, error) {
	if !(!(x == "")) {
		return CellType{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return CellType{v: x}, nil
}

func (t CellType) Val() string { return t.v }


// --- TransfectionEfficiency ---
// Shen: (datatype transfection-efficiency)
type TransfectionEfficiency struct{ v float64 }

func NewTransfectionEfficiency(x float64) (TransfectionEfficiency, error) {
	if !(x >= 0) {
		return TransfectionEfficiency{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	if !(x <= 100) {
		return TransfectionEfficiency{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return TransfectionEfficiency{v: x}, nil
}

func (t TransfectionEfficiency) Val() float64 { return t.v }


// --- CellsTransfected ---
// Shen: (datatype cells-transfected)
type CellsTransfected struct {
	synthesis GuideSynthesized
	method DeliveryMethod
	cellType CellType
	efficiency TransfectionEfficiency
	transfectedAt Timestamp
}

func NewCellsTransfected(synthesis GuideSynthesized, method DeliveryMethod, cellType CellType, efficiency TransfectionEfficiency, transfectedAt Timestamp) CellsTransfected {
	return CellsTransfected{
		synthesis: synthesis,
		method: method,
		cellType: cellType,
		efficiency: efficiency,
		transfectedAt: transfectedAt,
	}
}

func (t CellsTransfected) Synthesis() GuideSynthesized { return t.synthesis }

func (t CellsTransfected) Method() DeliveryMethod { return t.method }

func (t CellsTransfected) CellType() CellType { return t.cellType }

func (t CellsTransfected) Efficiency() TransfectionEfficiency { return t.efficiency }

func (t CellsTransfected) TransfectedAt() Timestamp { return t.transfectedAt }


// --- SelectionMethod ---
// Shen: (datatype selection-method)
type SelectionMethod struct{ v string }

func NewSelectionMethod(x string) (SelectionMethod, error) {
	if !(map[string]bool{"antibiotic-resistance": true, "facs": true, "flow-sorting": true, "puromycin": true}[x]) {
		return SelectionMethod{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return SelectionMethod{v: x}, nil
}

func (t SelectionMethod) Val() string { return t.v }


// --- CellsSelected ---
// Shen: (datatype cells-selected)
type CellsSelected struct {
	transfection CellsTransfected
	selectionType SelectionMethod
	survivalRate float64
}

func NewCellsSelected(transfection CellsTransfected, selectionType SelectionMethod, survivalRate float64) (CellsSelected, error) {
	if !(survivalRate > 0) {
		return CellsSelected{}, fmt.Errorf("survivalRate must be > 0")
	}
	if !(survivalRate <= 100) {
		return CellsSelected{}, fmt.Errorf("survivalRate must be <= 100")
	}
	return CellsSelected{
		transfection: transfection,
		selectionType: selectionType,
		survivalRate: survivalRate,
	}, nil
}

func (t CellsSelected) Transfection() CellsTransfected { return t.transfection }

func (t CellsSelected) SelectionType() SelectionMethod { return t.selectionType }

func (t CellsSelected) SurvivalRate() float64 { return t.survivalRate }


// --- SequencingMethod ---
// Shen: (datatype sequencing-method)
type SequencingMethod struct{ v string }

func NewSequencingMethod(x string) (SequencingMethod, error) {
	if !(map[string]bool{"sanger": true, "ngs": true, "amplicon-seq": true, "whole-genome": true}[x]) {
		return SequencingMethod{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return SequencingMethod{v: x}, nil
}

func (t SequencingMethod) Val() string { return t.v }


// --- OnTargetEfficiency ---
// Shen: (datatype on-target-efficiency)
type OnTargetEfficiency struct{ v float64 }

func NewOnTargetEfficiency(x float64) (OnTargetEfficiency, error) {
	if !(x >= 0) {
		return OnTargetEfficiency{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	if !(x <= 100) {
		return OnTargetEfficiency{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return OnTargetEfficiency{v: x}, nil
}

func (t OnTargetEfficiency) Val() float64 { return t.v }


// --- OnTargetConfirmed ---
// Shen: (datatype on-target-confirmed)
type OnTargetConfirmed struct {
	selected CellsSelected
	seqMethod SequencingMethod
	efficiency OnTargetEfficiency
	sequencedAt Timestamp
}

func NewOnTargetConfirmed(selected CellsSelected, seqMethod SequencingMethod, efficiency OnTargetEfficiency, sequencedAt Timestamp) (OnTargetConfirmed, error) {
	if !(efficiency.Val() > 0) {
		return OnTargetConfirmed{}, fmt.Errorf("efficiency must be > 0")
	}
	return OnTargetConfirmed{
		selected: selected,
		seqMethod: seqMethod,
		efficiency: efficiency,
		sequencedAt: sequencedAt,
	}, nil
}

func (t OnTargetConfirmed) Selected() CellsSelected { return t.selected }

func (t OnTargetConfirmed) SeqMethod() SequencingMethod { return t.seqMethod }

func (t OnTargetConfirmed) Efficiency() OnTargetEfficiency { return t.efficiency }

func (t OnTargetConfirmed) SequencedAt() Timestamp { return t.sequencedAt }


// --- OffTargetSitesChecked ---
// Shen: (datatype off-target-sites-checked)
type OffTargetSitesChecked struct{ v float64 }

func NewOffTargetSitesChecked(x float64) (OffTargetSitesChecked, error) {
	if !(x > 0) {
		return OffTargetSitesChecked{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return OffTargetSitesChecked{v: x}, nil
}

func (t OffTargetSitesChecked) Val() float64 { return t.v }


// --- OffTargetHitsFound ---
// Shen: (datatype off-target-hits-found)
type OffTargetHitsFound struct{ v float64 }

func NewOffTargetHitsFound(x float64) (OffTargetHitsFound, error) {
	if !(x >= 0) {
		return OffTargetHitsFound{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return OffTargetHitsFound{v: x}, nil
}

func (t OffTargetHitsFound) Val() float64 { return t.v }


// --- OffTargetValidated ---
// Shen: (datatype off-target-validated)
type OffTargetValidated struct {
	onTarget OnTargetConfirmed
	sitesChecked OffTargetSitesChecked
	hitsFound OffTargetHitsFound
	seqMethod SequencingMethod
	validatedAt Timestamp
}

func NewOffTargetValidated(onTarget OnTargetConfirmed, sitesChecked OffTargetSitesChecked, hitsFound OffTargetHitsFound, seqMethod SequencingMethod, validatedAt Timestamp) OffTargetValidated {
	return OffTargetValidated{
		onTarget: onTarget,
		sitesChecked: sitesChecked,
		hitsFound: hitsFound,
		seqMethod: seqMethod,
		validatedAt: validatedAt,
	}
}

func (t OffTargetValidated) OnTarget() OnTargetConfirmed { return t.onTarget }

func (t OffTargetValidated) SitesChecked() OffTargetSitesChecked { return t.sitesChecked }

func (t OffTargetValidated) HitsFound() OffTargetHitsFound { return t.hitsFound }

func (t OffTargetValidated) SeqMethod() SequencingMethod { return t.seqMethod }

func (t OffTargetValidated) ValidatedAt() Timestamp { return t.validatedAt }


// --- OffTargetAcceptable ---
// Shen: (datatype off-target-acceptable)
type OffTargetAcceptable struct {
	validation OffTargetValidated
	maxAcceptable float64
}

func NewOffTargetAcceptable(validation OffTargetValidated, maxAcceptable float64) (OffTargetAcceptable, error) {
	if !(maxAcceptable >= 0) {
		return OffTargetAcceptable{}, fmt.Errorf("maxAcceptable must be >= 0")
	}
	if !(validation.seqMethod.Val() <= maxAcceptable) {
		return OffTargetAcceptable{}, fmt.Errorf("validation.seqMethod must be <= maxAcceptable")
	}
	return OffTargetAcceptable{
		validation: validation,
		maxAcceptable: maxAcceptable,
	}, nil
}

func (t OffTargetAcceptable) Validation() OffTargetValidated { return t.validation }

func (t OffTargetAcceptable) MaxAcceptable() float64 { return t.maxAcceptable }


// --- ValidatedEdit ---
// Shen: (datatype validated-edit)
type ValidatedEdit struct {
	onTarget OnTargetConfirmed
	offTarget OffTargetAcceptable
}

func NewValidatedEdit(onTarget OnTargetConfirmed, offTarget OffTargetAcceptable) ValidatedEdit {
	return ValidatedEdit{
		onTarget: onTarget,
		offTarget: offTarget,
	}
}

func (t ValidatedEdit) OnTarget() OnTargetConfirmed { return t.onTarget }

func (t ValidatedEdit) OffTarget() OffTargetAcceptable { return t.offTarget }


// --- BiosafetyLevel ---
// Shen: (datatype biosafety-level)
type BiosafetyLevel struct{ v string }

func NewBiosafetyLevel(x string) (BiosafetyLevel, error) {
	if !(map[string]bool{"bsl-1": true, "bsl-2": true, "bsl-3": true, "bsl-4": true}[x]) {
		return BiosafetyLevel{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return BiosafetyLevel{v: x}, nil
}

func (t BiosafetyLevel) Val() string { return t.v }


// --- IrbApproval ---
// Shen: (datatype irb-approval)
type IrbApproval struct {
	protocolId string
	approvedAt Timestamp
	expiresAt Timestamp
}

func NewIrbApproval(protocolId string, approvedAt Timestamp, expiresAt Timestamp) (IrbApproval, error) {
	if !(!(protocolId == "")) {
		return IrbApproval{}, fmt.Errorf("not: protocolId must equal \"\"")
	}
	if !(expiresAt.Val() > approvedAt.Val()) {
		return IrbApproval{}, fmt.Errorf("expiresAt must be > approvedAt")
	}
	return IrbApproval{
		protocolId: protocolId,
		approvedAt: approvedAt,
		expiresAt: expiresAt,
	}, nil
}

func (t IrbApproval) ProtocolId() string { return t.protocolId }

func (t IrbApproval) ApprovedAt() Timestamp { return t.approvedAt }

func (t IrbApproval) ExpiresAt() Timestamp { return t.expiresAt }


// --- IrbCurrent ---
// Shen: (datatype irb-current)
type IrbCurrent struct {
	approval IrbApproval
	now Timestamp
}

func NewIrbCurrent(approval IrbApproval, now Timestamp) (IrbCurrent, error) {
	if !(/* TODO: (> (head (tail (tail Approval))) Now) */ true) {
		return IrbCurrent{}, fmt.Errorf("could not resolve comparison")
	}
	return IrbCurrent{
		approval: approval,
		now: now,
	}, nil
}

func (t IrbCurrent) Approval() IrbApproval { return t.approval }

func (t IrbCurrent) Now() Timestamp { return t.now }


// --- SomaticOnly ---
// Shen: (datatype somatic-only)
type SomaticOnly struct {
	cellType CellType
	isGermline bool
}

func NewSomaticOnly(cellType CellType, isGermline bool) (SomaticOnly, error) {
	if !(isGermline == false) {
		return SomaticOnly{}, fmt.Errorf("isGermline must equal false")
	}
	return SomaticOnly{
		cellType: cellType,
		isGermline: isGermline,
	}, nil
}

func (t SomaticOnly) CellType() CellType { return t.cellType }

func (t SomaticOnly) IsGermline() bool { return t.isGermline }


// --- ClinicalGradeEdit ---
// Shen: (datatype clinical-grade-edit)
type ClinicalGradeEdit struct {
	edit ValidatedEdit
	biosafety BiosafetyLevel
	irb IrbCurrent
	somatic SomaticOnly
}

func NewClinicalGradeEdit(edit ValidatedEdit, biosafety BiosafetyLevel, irb IrbCurrent, somatic SomaticOnly) ClinicalGradeEdit {
	return ClinicalGradeEdit{
		edit: edit,
		biosafety: biosafety,
		irb: irb,
		somatic: somatic,
	}
}

func (t ClinicalGradeEdit) Edit() ValidatedEdit { return t.edit }

func (t ClinicalGradeEdit) Biosafety() BiosafetyLevel { return t.biosafety }

func (t ClinicalGradeEdit) Irb() IrbCurrent { return t.irb }

func (t ClinicalGradeEdit) Somatic() SomaticOnly { return t.somatic }


// --- GuidesNonInterfering ---
// Shen: (datatype guides-non-interfering)
type GuidesNonInterfering struct {
	guideA GuideRna
	guideB GuideRna
	interference float64
	maxInterference float64
}

func NewGuidesNonInterfering(guideA GuideRna, guideB GuideRna, interference float64, maxInterference float64) (GuidesNonInterfering, error) {
	if !(interference >= 0) {
		return GuidesNonInterfering{}, fmt.Errorf("interference must be >= 0")
	}
	if !(interference <= maxInterference) {
		return GuidesNonInterfering{}, fmt.Errorf("interference must be <= maxInterference")
	}
	if !(maxInterference > 0) {
		return GuidesNonInterfering{}, fmt.Errorf("maxInterference must be > 0")
	}
	return GuidesNonInterfering{
		guideA: guideA,
		guideB: guideB,
		interference: interference,
		maxInterference: maxInterference,
	}, nil
}

func (t GuidesNonInterfering) GuideA() GuideRna { return t.guideA }

func (t GuidesNonInterfering) GuideB() GuideRna { return t.guideB }

func (t GuidesNonInterfering) Interference() float64 { return t.interference }

func (t GuidesNonInterfering) MaxInterference() float64 { return t.maxInterference }


// --- MultiplexSafe ---
// Shen: (datatype multiplex-safe)
type MultiplexSafe struct {
	editCount float64
	allPairsCleared bool
}

func NewMultiplexSafe(editCount float64, allPairsCleared bool) (MultiplexSafe, error) {
	if !(editCount > 1) {
		return MultiplexSafe{}, fmt.Errorf("editCount must be > 1")
	}
	if !(allPairsCleared == true) {
		return MultiplexSafe{}, fmt.Errorf("allPairsCleared must equal true")
	}
	return MultiplexSafe{
		editCount: editCount,
		allPairsCleared: allPairsCleared,
	}, nil
}

func (t MultiplexSafe) EditCount() float64 { return t.editCount }

func (t MultiplexSafe) AllPairsCleared() bool { return t.allPairsCleared }


