package report

// roundtrip_test.go pins the canonical schema (this package) against
// the wire-format expectations cmd/sb's discharge.go reads. The two
// modules are intentionally decoupled (separate go.mod files), so
// the JSON shape is the contract. This test catches silent drift
// between the writer (this package) and the reader (cmd/sb) by
// asserting the serialised bytes match a checked-in fixture that
// represents the documented schema.

import (
	"encoding/json"
	"strings"
	"testing"
	"time"
)

// canonicalRoundTrip exercises every required field of every
// documented shape and confirms each one survives marshal/unmarshal
// at the documented JSON key.
func TestCanonicalRoundTrip(t *testing.T) {
	commit := "abc123"
	dirty := false
	seedLabel := "deterministic-default"

	r := &Report{
		SchemaVersion: 1,
		GeneratedAt:   time.Date(2026, 5, 5, 22, 30, 0, 0, time.UTC).Format(time.RFC3339),
		Spec: SpecInfo{
			Files: []SpecFile{{Path: "specs/core.shen", SHA256: "deadbeef"}},
			RuleCount: 1,
		},
		Impl: ImplInfo{
			GitCommit:       &commit,
			GitDirty:        &dirty,
			TargetLanguages: []string{"go"},
		},
		Tools: ToolsInfo{
			SBVersion:            "0.3.0",
			ShenDeriveVersion:    "0.3.0",
			ShengenVersion:       "",
			ShenRuntime:          nil,
			ShenRuntimeAvailable: false,
		},
		Rules: []Rule{{
			Name:                   "amount",
			Kind:                   "constrained",
			SpecFile:               "specs/core.shen",
			SpecExcerpt:            "(datatype amount …)",
			HumanDescription:       "An Amount is non-negative.",
			HumanDescriptionSource: HumanDescriptionAutoGenerated,
			Premises: []Premise{{
				ID:             "amount.field-x",
				Expression:     "X : number",
				Discharge:      DischargeStatic,
				DischargeBasis: BasisGuardTypeAtBoundary,
				Rationale:      "X is typed number.",
				CodeReferences: []string{"internal/shenguard/guards_gen.go:26"},
				SamplesPassed:  0,
				SamplesFailed:  0,
				SampleSeed:     nil,
			}, {
				ID:             "amount.verified-x-0",
				Expression:     "(>= X 0) : verified",
				Discharge:      DischargeRuntimeSampled,
				DischargeBasis: BasisShenDeriveSampled,
				Rationale:      "shen-derive sampled 35 cases; predicate held.",
				SamplesPassed:  35,
				SamplesFailed:  0,
				SampleSeed:     &seedLabel,
			}},
			Status:                StatusDischarged,
			DischargedSinceCommit: &commit,
			CounterExamples:       []CounterExample{},
		}},
		Summary: Summary{
			RuleCount: 1, RulesDischarged: 1,
			PremisesTotal: 2, PremisesStatic: 1, PremisesRuntimeSampled: 1,
		},
		Signature: nil,
	}

	bytes1, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	// Round-trip.
	var r2 Report
	if err := json.Unmarshal(bytes1, &r2); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	bytes2, err := json.MarshalIndent(&r2, "", "  ")
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	if string(bytes1) != string(bytes2) {
		t.Fatalf("round-trip drifted:\nfirst:\n%s\nsecond:\n%s", string(bytes1), string(bytes2))
	}

	// Pin specific required keys present in the wire format.
	out := string(bytes1)
	required := []string{
		`"schema_version": 1`,
		`"generated_at"`,
		`"spec":`,
		`"files":`,
		`"sha256":`,
		`"impl":`,
		`"git_commit":`,
		`"git_dirty":`,
		`"target_languages":`,
		`"tools":`,
		`"shen_runtime": null`,
		`"shen_runtime_available":`,
		`"rules":`,
		`"name":`,
		`"kind":`,
		`"human_description":`,
		`"human_description_source":`,
		`"premises":`,
		`"discharge":`,
		`"discharge_basis":`,
		`"samples_passed":`,
		`"samples_failed":`,
		`"sample_seed":`,
		`"status":`,
		`"discharged_since_commit":`,
		`"counter_examples": []`,
		`"summary":`,
		`"signature": null`,
	}
	for _, want := range required {
		if !strings.Contains(out, want) {
			t.Errorf("missing required key/value %q in:\n%s", want, out)
		}
	}
}

// TestSamplesPassedFailedInvariant pins the "passed + failed = total
// sampled count" invariant that drives the audit Markdown's sample
// math. Drift here would let a downstream reader trust an
// inconsistent count.
func TestSamplesPassedFailedInvariant(t *testing.T) {
	const total = 35
	cases := []struct {
		passed, failed int
	}{
		{total, 0},
		{total - 1, 1},
		{0, total},
	}
	for _, c := range cases {
		r := Rule{Premises: []Premise{{
			Discharge:     DischargeRuntimeSampled,
			SamplesPassed: c.passed,
			SamplesFailed: c.failed,
		}}}
		got := r.Premises[0].SamplesPassed + r.Premises[0].SamplesFailed
		if got != total {
			t.Errorf("invariant broken: passed=%d failed=%d sum=%d, want %d", c.passed, c.failed, got, total)
		}
	}
}
