// Package report defines the discharge-report schema and the
// classifier/emitter that produces it from a parsed Shen spec and a
// shen-derive verification harness.
//
// The discharge report is a structured artifact written on every
// gate run that distinguishes how each premise of each Shen rule was
// discharged: statically (via guard types), via runtime sampling
// (shen-derive's spec-equivalence pool), or unproven. It feeds two
// readers: the agent loop (terse Markdown via `sb context`) and a
// human auditor (long-form Markdown via `sb audit-report`).
//
// Schema is locked at SchemaVersion=1. Evolution must be additive.
// See thoughts/shared/research/2026-05-05-discharge-report-schema.md
// for the rationale.
package report

// SchemaVersion is the discharge report schema version. v0 of the
// feature emits version 1; future additive fields keep the same
// version. Renaming or removing fields requires a bump.
const SchemaVersion = 1

// Report is the top-level structure. Marshals to JSON in the field
// order declared here. JSON consumers should ignore fields they don't
// recognise so that additive changes don't break them.
type Report struct {
	SchemaVersion int        `json:"schema_version"`
	GeneratedAt   string     `json:"generated_at"`
	Spec          SpecInfo   `json:"spec"`
	Impl          ImplInfo   `json:"impl"`
	Tools         ToolsInfo  `json:"tools"`
	Rules         []Rule     `json:"rules"`
	Summary       Summary    `json:"summary"`
	Signature     *Signature `json:"signature"` // null in v0; reserved
}

// SpecInfo identifies the spec file(s) the report covers. v0 supports
// a single spec but the slice shape is reserved for multi-spec
// projects.
type SpecInfo struct {
	Files     []SpecFile `json:"files"`
	RuleCount int        `json:"rule_count"`
}

// SpecFile records one spec file's path (repo-relative) and its
// SHA-256 hash. Hashes let stored reports be tied to exact spec bytes.
type SpecFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// ImplInfo describes the implementation under verification. git_commit
// may be null when the project is not in a git repo.
type ImplInfo struct {
	GitCommit       *string  `json:"git_commit"`
	GitDirty        *bool    `json:"git_dirty"`
	TargetLanguages []string `json:"target_languages"`
}

// ToolsInfo records which tools produced this report. Useful to
// reproduce a historical run with the same toolchain.
type ToolsInfo struct {
	SBVersion            string  `json:"sb_version"`
	ShenDeriveVersion    string  `json:"shen_derive_version"`
	ShengenVersion       string  `json:"shengen_version"`
	ShenRuntime          *string `json:"shen_runtime"`
	ShenRuntimeAvailable bool    `json:"shen_runtime_available"`
}

// Rule is one Shen (datatype …) or (define …) block, with its
// per-premise discharge classification and any counter-examples.
type Rule struct {
	Name                    string           `json:"name"`
	Kind                    string           `json:"kind"`
	SpecFile                string           `json:"spec_file"`
	SpecExcerpt             string           `json:"spec_excerpt"`
	HumanDescription        string           `json:"human_description"`
	HumanDescriptionSource  string           `json:"human_description_source"`
	Premises                []Premise        `json:"premises"`
	Status                  string           `json:"status"`
	DischargedSinceCommit   *string          `json:"discharged_since_commit"`
	CounterExamples         []CounterExample `json:"counter_examples"`
}

// Status values for a rule.
const (
	StatusDischarged = "discharged"
	StatusViolated   = "violated"
	StatusUnproven   = "unproven"
)

// HumanDescriptionSource values.
const (
	HumanDescriptionFromDoc           = ":doc"
	HumanDescriptionAutoGenerated     = "auto-generated"
)

// Premise is one obligation of a rule and how it's discharged.
type Premise struct {
	ID             string   `json:"id"`
	Expression     string   `json:"expression"`
	Discharge      string   `json:"discharge"`
	DischargeBasis string   `json:"discharge_basis"`
	Rationale      string   `json:"rationale"`
	CodeReferences []string `json:"code_references,omitempty"`
	SamplesPassed  int      `json:"samples_passed"`
	SamplesFailed  int      `json:"samples_failed"`
	SampleSeed     *string  `json:"sample_seed"`
}

// Discharge values.
const (
	DischargeStatic         = "static"
	DischargeRuntimeSampled = "runtime-sample"
	DischargeUnproven       = "unproven"
)

// DischargeBasis values used in v0.
const (
	BasisGuardTypeAtBoundary     = "guard-type-at-boundary"
	BasisGuardConstructorValidates = "guard-constructor-validates"
	BasisShenDeriveSampled         = "shen-derive-sampled"
	BasisNotDischarged             = "not-discharged"
)

// CounterExample is a concrete witness of a rule violation.
type CounterExample struct {
	CaseID           string            `json:"case_id"`
	Input            map[string]string `json:"input"`
	SpecOutput       string            `json:"spec_output"`
	ImplOutput       string            `json:"impl_output"`
	ImplFunction     string            `json:"impl_function"`
	ImplFile         string            `json:"impl_file,omitempty"`
	ImplLineHint     *int              `json:"impl_line_hint"`
	FirstSeenCommit  *string           `json:"first_seen_commit"`
	Rationale        string            `json:"rationale"`
}

// Summary rolls up rule and premise counts for the whole report.
// Fields are always present; counts may be zero.
type Summary struct {
	RuleCount              int `json:"rule_count"`
	RulesDischarged        int `json:"rules_discharged"`
	RulesViolated          int `json:"rules_violated"`
	RulesUnproven          int `json:"rules_unproven"`
	PremisesTotal          int `json:"premises_total"`
	PremisesStatic         int `json:"premises_static"`
	PremisesRuntimeSampled int `json:"premises_runtime_sampled"`
	PremisesUnproven       int `json:"premises_unproven"`
}

// Signature is the placeholder for a cryptographic signature over
// the report's canonical bytes. Always null in v0.
type Signature struct {
	Algorithm string `json:"algorithm"`
	KeyID     string `json:"key_id"`
	Value     string `json:"value"`
}
