// Code generated by shen-derive. DO NOT EDIT.

package derived

// AnyNegative is derived by shen-derive.
func AnyNegative(_arg1 []int) bool {
	_xs2 := _arg1
	_acc3 := false
	for _i4 := len(_xs2) - 1; _i4 >= 0; _i4-- {
		x := _xs2[_i4]
		if (x < 0) {
			_acc3 = true
		}
	}
	return _acc3
}
