// Code generated by shen-derive. DO NOT EDIT.

package derived

// IdentityBools is derived by shen-derive.
func IdentityBools(_arg1 []bool) []bool {
	_xs2 := _arg1
	_result3 := make([]bool, len(_xs2))
	for _i4, _x5 := range _xs2 {
		_result3[_i4] = func() bool { if _x5 { return _x5 }; return false }()
	}
	return _result3
}
