// Code generated by shen-derive. DO NOT EDIT.

package derived

// MapIncThenSquare is derived by shen-derive.
func MapIncThenSquare(_arg1 []int) []int {
	_xs2 := _arg1
	_result3 := make([]int, len(_xs2))
	for _i4, _x5 := range _xs2 {
		_result3[_i4] = func(x int) int { return (x * x) }((_x5 + 1))
	}
	return _result3
}
