// Code generated by shen-derive. DO NOT EDIT.

package derived

// NonNegFlags is derived by shen-derive.
func NonNegFlags(_arg1 []int) []bool {
	_xs2 := _arg1
	_acc3 := []bool{}
	for _i4 := len(_xs2) - 1; _i4 >= 0; _i4-- {
		x := _xs2[_i4]
		_acc3 = append([]bool{(x >= 0)}, _acc3...)
	}
	return _acc3
}
