// Code generated by shen-derive. DO NOT EDIT.

package derived

// PaymentProcessable is derived by shen-derive.
func PaymentProcessable(b0 int, txs []int) bool {
	_xs1 := txs
	_acc2 := struct{ Fst int; Snd bool }{b0, (b0 >= 0)}
	for _, _x3 := range _xs1 {
		_acc2 = func() struct{ Fst int; Snd bool } { _v4 := func(tx int) int { return (_acc2.Fst - tx) }(_x3); return struct{ Fst int; Snd bool }{_v4, (_acc2.Snd && (_v4 >= 0))} }()
	}
	return _acc2.Snd
}
