// Code generated by shen-derive. DO NOT EDIT.

package derived

// RunningSum is derived by shen-derive.
func RunningSum(_arg1 []int) []int {
	_xs2 := _arg1
	_acc3 := 0
	_result4 := make([]int, 0, len(_xs2)+1)
	_result4 = append(_result4, _acc3)
	for _, _x5 := range _xs2 {
		_acc3 = (_acc3 + _x5)
		_result4 = append(_result4, _acc3)
	}
	return _result4
}
