// Code generated by shen-derive. DO NOT EDIT.

package derived

// Squares is derived by shen-derive.
func Squares(_arg1 []int) []int {
	_xs2 := _arg1
	_result3 := make([]int, len(_xs2))
	for _i4, _x5 := range _xs2 {
		_result3[_i4] = (_x5 * _x5)
	}
	return _result3
}
