// Code generated by shen-derive. DO NOT EDIT.
// Regenerate with: shen-derive verify <spec.shen> --func processable
// Path cover: paths_total=10 paths_feasible=9 paths_dead=1
// Path cover solver: z3 (list unroll depth 4, 9 path sample(s) below)
//
// This file checks that Processable matches the Shen spec
// by evaluating the spec on sampled inputs and comparing outputs.

package derived_test

import (
	"testing"
	"context"
	shenguard "ralph-shen-agent/internal/shenguard"
	derived "ralph-shen-agent/internal/derived"
)

func mustAccountId(x string) shenguard.AccountId { return shenguard.NewAccountId(x) }

func mustAmount(x float64) shenguard.Amount { v, err := shenguard.NewAmount(context.Background(), x); if err != nil { panic(err) }; return v }

func mustTransaction(a0 shenguard.Amount, a1 shenguard.AccountId, a2 shenguard.AccountId) shenguard.Transaction { return shenguard.NewTransaction(a0, a1, a2) }

func TestSpec_Processable(t *testing.T) {
	cases := []struct {
		name string
		b0 shenguard.Amount
		txs []shenguard.Transaction
		want bool
	}{
		{
			name: "case_00",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{},
			want: true,
		},
		{
			name: "case_01",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_02",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice"))},
			want: false,
		},
		{
			name: "case_03",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_04",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(2.5), mustAccountId(""), mustAccountId(""))},
			want: false,
		},
		{
			name: "case_05",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(100), mustAccountId("alice"), mustAccountId("alice"))},
			want: false,
		},
		{
			name: "case_06",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice")), mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_07",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{},
			want: true,
		},
		{
			name: "case_08",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_09",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice"))},
			want: true,
		},
		{
			name: "case_10",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_11",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(2.5), mustAccountId(""), mustAccountId(""))},
			want: false,
		},
		{
			name: "case_12",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(100), mustAccountId("alice"), mustAccountId("alice"))},
			want: false,
		},
		{
			name: "case_13",
			b0: mustAmount(1),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice")), mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_14",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{},
			want: true,
		},
		{
			name: "case_15",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_16",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice"))},
			want: true,
		},
		{
			name: "case_17",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: true,
		},
		{
			name: "case_18",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(2.5), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_19",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(100), mustAccountId("alice"), mustAccountId("alice"))},
			want: false,
		},
		{
			name: "case_20",
			b0: mustAmount(5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice")), mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_21",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{},
			want: true,
		},
		{
			name: "case_22",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_23",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice"))},
			want: true,
		},
		{
			name: "case_24",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_25",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(2.5), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_26",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(100), mustAccountId("alice"), mustAccountId("alice"))},
			want: false,
		},
		{
			name: "case_27",
			b0: mustAmount(2.5),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice")), mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: false,
		},
		{
			name: "case_28",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{},
			want: true,
		},
		{
			name: "case_29",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_30",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice"))},
			want: true,
		},
		{
			name: "case_31",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: true,
		},
		{
			name: "case_32",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(2.5), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			name: "case_33",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(100), mustAccountId("alice"), mustAccountId("alice"))},
			want: true,
		},
		{
			name: "case_34",
			b0: mustAmount(100),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(1), mustAccountId("alice"), mustAccountId("alice")), mustTransaction(mustAmount(5), mustAccountId("bob"), mustAccountId("bob"))},
			want: true,
		},
		{
			// provenance: path:0
			name: "path_0",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{},
			want: true,
		},
		{
			// provenance: path:2
			name: "path_2",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			// provenance: path:3
			name: "path_3",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId(""), mustAccountId(""))},
			want: false,
		},
		{
			// provenance: path:4
			name: "path_4",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			// provenance: path:5
			name: "path_5",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: false,
		},
		{
			// provenance: path:6
			name: "path_6",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			// provenance: path:7
			name: "path_7",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: false,
		},
		{
			// provenance: path:8
			name: "path_8",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: true,
		},
		{
			// provenance: path:9
			name: "path_9",
			b0: mustAmount(0),
			txs: []shenguard.Transaction{mustTransaction(mustAmount(1), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId("")), mustTransaction(mustAmount(0), mustAccountId(""), mustAccountId(""))},
			want: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := derived.Processable(tc.b0, tc.txs)
			if got != tc.want {
				t.Fatalf("%s: spec says %v, impl returned %v", tc.name, tc.want, got)
			}
		})
	}
}
