// Code generated by shengen from demo/data-pipeline/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- SchemaVersion ---
// Shen: (datatype schema-version)
type SchemaVersion struct {
	major float64
	minor float64
}

func NewSchemaVersion(major float64, minor float64) (SchemaVersion, error) {
	if !(major >= 0) {
		return SchemaVersion{}, fmt.Errorf("major must be >= 0")
	}
	if !(minor >= 0) {
		return SchemaVersion{}, fmt.Errorf("minor must be >= 0")
	}
	return SchemaVersion{
		major: major,
		minor: minor,
	}, nil
}

func (t SchemaVersion) Major() float64 { return t.major }

func (t SchemaVersion) Minor() float64 { return t.minor }


// --- SchemaCompatible ---
// Shen: (datatype schema-compatible)
type SchemaCompatible struct {
	source SchemaVersion
	target SchemaVersion
}

func NewSchemaCompatible(source SchemaVersion, target SchemaVersion) (SchemaCompatible, error) {
	if !(source.major == target.major) {
		return SchemaCompatible{}, fmt.Errorf("source.major must equal target.major")
	}
	if !(/* TODO: (<= (head (tail Source)) (head (tail Target))) */ true) {
		return SchemaCompatible{}, fmt.Errorf("could not resolve comparison")
	}
	return SchemaCompatible{
		source: source,
		target: target,
	}, nil
}

func (t SchemaCompatible) Source() SchemaVersion { return t.source }

func (t SchemaCompatible) Target() SchemaVersion { return t.target }


// --- RecordId ---
// Shen: (datatype record-id)
type RecordId struct{ v string }

func NewRecordId(x string) (RecordId, error) {
	if !(!(x == "")) {
		return RecordId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return RecordId{v: x}, nil
}

func (t RecordId) Val() string { return t.v }


// --- SchemaName ---
// Shen: (datatype schema-name)
type SchemaName struct{ v string }

func NewSchemaName(x string) (SchemaName, error) {
	if !(!(x == "")) {
		return SchemaName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return SchemaName{v: x}, nil
}

func (t SchemaName) Val() string { return t.v }


// --- TypedRecord ---
// Shen: (datatype typed-record)
type TypedRecord struct {
	id RecordId
	schema SchemaName
	version SchemaVersion
}

func NewTypedRecord(id RecordId, schema SchemaName, version SchemaVersion) TypedRecord {
	return TypedRecord{
		id: id,
		schema: schema,
		version: version,
	}
}

func (t TypedRecord) Id() RecordId { return t.id }

func (t TypedRecord) Schema() SchemaName { return t.schema }

func (t TypedRecord) Version() SchemaVersion { return t.version }


// --- StageName ---
// Shen: (datatype stage-name)
type StageName struct{ v string }

func NewStageName(x string) (StageName, error) {
	if !(!(x == "")) {
		return StageName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return StageName{v: x}, nil
}

func (t StageName) Val() string { return t.v }


// --- StageContract ---
// Shen: (datatype stage-contract)
type StageContract struct {
	name StageName
	inputSchema SchemaName
	inputVersion SchemaVersion
	outputSchema SchemaName
	outputVersion SchemaVersion
}

func NewStageContract(name StageName, inputSchema SchemaName, inputVersion SchemaVersion, outputSchema SchemaName, outputVersion SchemaVersion) StageContract {
	return StageContract{
		name: name,
		inputSchema: inputSchema,
		inputVersion: inputVersion,
		outputSchema: outputSchema,
		outputVersion: outputVersion,
	}
}

func (t StageContract) Name() StageName { return t.name }

func (t StageContract) InputSchema() SchemaName { return t.inputSchema }

func (t StageContract) InputVersion() SchemaVersion { return t.inputVersion }

func (t StageContract) OutputSchema() SchemaName { return t.outputSchema }

func (t StageContract) OutputVersion() SchemaVersion { return t.outputVersion }


// --- StageInputValid ---
// Shen: (datatype stage-input-valid)
type StageInputValid struct {
	record TypedRecord
	stage StageContract
	compat SchemaCompatible
}

func NewStageInputValid(record TypedRecord, stage StageContract, compat SchemaCompatible) StageInputValid {
	return StageInputValid{
		record: record,
		stage: stage,
		compat: compat,
	}
}

func (t StageInputValid) Record() TypedRecord { return t.record }

func (t StageInputValid) Stage() StageContract { return t.stage }

func (t StageInputValid) Compat() SchemaCompatible { return t.compat }


// --- StageComposable ---
// Shen: (datatype stage-composable)
type StageComposable struct {
	stageA StageContract
	stageB StageContract
	compat SchemaCompatible
}

func NewStageComposable(stageA StageContract, stageB StageContract, compat SchemaCompatible) StageComposable {
	return StageComposable{
		stageA: stageA,
		stageB: stageB,
		compat: compat,
	}
}

func (t StageComposable) StageA() StageContract { return t.stageA }

func (t StageComposable) StageB() StageContract { return t.stageB }

func (t StageComposable) Compat() SchemaCompatible { return t.compat }


// --- CheckpointId ---
// Shen: (datatype checkpoint-id)
type CheckpointId struct{ v string }

func NewCheckpointId(x string) (CheckpointId, error) {
	if !(!(x == "")) {
		return CheckpointId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return CheckpointId{v: x}, nil
}

func (t CheckpointId) Val() string { return t.v }


// --- Offset ---
// Shen: (datatype offset)
type Offset struct{ v float64 }

func NewOffset(x float64) (Offset, error) {
	if !(x >= 0) {
		return Offset{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return Offset{v: x}, nil
}

func (t Offset) Val() float64 { return t.v }


// --- Checkpoint ---
// Shen: (datatype checkpoint)
type Checkpoint struct {
	id CheckpointId
	stage StageName
	offset Offset
	timestamp float64
}

func NewCheckpoint(id CheckpointId, stage StageName, offset Offset, timestamp float64) (Checkpoint, error) {
	if !(timestamp > 0) {
		return Checkpoint{}, fmt.Errorf("timestamp must be > 0")
	}
	return Checkpoint{
		id: id,
		stage: stage,
		offset: offset,
		timestamp: timestamp,
	}, nil
}

func (t Checkpoint) Id() CheckpointId { return t.id }

func (t Checkpoint) Stage() StageName { return t.stage }

func (t Checkpoint) Offset() Offset { return t.offset }

func (t Checkpoint) Timestamp() float64 { return t.timestamp }


// --- ResumeValid ---
// Shen: (datatype resume-valid)
type ResumeValid struct {
	newOffset Offset
	lastCheckpoint Checkpoint
}

func NewResumeValid(newOffset Offset, lastCheckpoint Checkpoint) (ResumeValid, error) {
	if !(newOffset.Val() > lastCheckpoint.offset.Val()) {
		return ResumeValid{}, fmt.Errorf("newOffset must be > lastCheckpoint.offset")
	}
	return ResumeValid{
		newOffset: newOffset,
		lastCheckpoint: lastCheckpoint,
	}, nil
}

func (t ResumeValid) NewOffset() Offset { return t.newOffset }

func (t ResumeValid) LastCheckpoint() Checkpoint { return t.lastCheckpoint }


// --- DlqEntry ---
// Shen: (datatype dlq-entry)
type DlqEntry struct {
	record TypedRecord
	stage StageName
	errorMsg string
	timestamp float64
}

func NewDlqEntry(record TypedRecord, stage StageName, errorMsg string, timestamp float64) (DlqEntry, error) {
	if !(timestamp > 0) {
		return DlqEntry{}, fmt.Errorf("timestamp must be > 0")
	}
	if !(!(errorMsg == "")) {
		return DlqEntry{}, fmt.Errorf("not: errorMsg must equal \"\"")
	}
	return DlqEntry{
		record: record,
		stage: stage,
		errorMsg: errorMsg,
		timestamp: timestamp,
	}, nil
}

func (t DlqEntry) Record() TypedRecord { return t.record }

func (t DlqEntry) Stage() StageName { return t.stage }

func (t DlqEntry) ErrorMsg() string { return t.errorMsg }

func (t DlqEntry) Timestamp() float64 { return t.timestamp }


