// Code generated by shen-derive. DO NOT EDIT.

package derived

// EqualZeroFlags is derived by shen-derive.
func EqualZeroFlags(_arg1 []int) []bool {
	_xs2 := _arg1
	_result3 := make([]bool, len(_xs2))
	for _i4, _x5 := range _xs2 {
		_result3[_i4] = (_x5 == 0)
	}
	return _result3
}
