// Code generated by shen-derive. DO NOT EDIT.

package derived

// FilterAfterMap is derived by shen-derive.
func FilterAfterMap(xs []int) []int {
	_xs1 := xs
	var _result2 []int
	for _, _x3 := range _xs1 {
		_mapped4 := (_x3 - 1)
		if (_mapped4 >= 0) {
			_result2 = append(_result2, _mapped4)
		}
	}
	return _result2
}
