// Code generated by shen-derive. DO NOT EDIT.

package derived

// MapAfterFilter is derived by shen-derive.
func MapAfterFilter(xs []int) []int {
	_xs1 := xs
	var _result2 []int
	for _, _x3 := range _xs1 {
		if (_x3 > 0) {
			_result2 = append(_result2, (_x3 + 1))
		}
	}
	return _result2
}
