// Code generated by shen-derive. DO NOT EDIT.

package derived

// SafeUnderLimit is derived by shen-derive.
func SafeUnderLimit(limit int, xs []int) bool {
	_xs1 := xs
	_acc2 := true
	for _i3 := len(_xs1) - 1; _i3 >= 0; _i3-- {
		x := _xs1[_i3]
		if !((x <= limit)) {
			_acc2 = false
		}
	}
	return _acc2
}
