// Code generated by shengen from demo/email_crud/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- EmailAddr ---
// Shen: (datatype email-addr)
type EmailAddr struct{ v string }

func NewEmailAddr(x string) EmailAddr { return EmailAddr{v: x} }

func (t EmailAddr) Val() string { return t.v }

func (t EmailAddr) String() string { return t.v }


// --- UserId ---
// Shen: (datatype user-id)
type UserId struct{ v string }

func NewUserId(x string) UserId { return UserId{v: x} }

func (t UserId) Val() string { return t.v }

func (t UserId) String() string { return t.v }


// --- AgeDecade ---
// Shen: (datatype age-decade)
type AgeDecade struct{ v float64 }

func NewAgeDecade(x float64) (AgeDecade, error) {
	if !(x >= 10) {
		return AgeDecade{}, fmt.Errorf("x must be >= 10: %v", x)
	}
	if !(x <= 100) {
		return AgeDecade{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	if !(0 == int(x) % 10) {
		return AgeDecade{}, fmt.Errorf("0 must equal int(x) %% 10: %v", x)
	}
	return AgeDecade{v: x}, nil
}

func (t AgeDecade) Val() float64 { return t.v }


// --- UsState ---
// Shen: (datatype us-state)
type UsState struct{ v string }

func NewUsState(x string) (UsState, error) {
	if !(2 == len(x)) {
		return UsState{}, fmt.Errorf("2 must equal len(x): %v", x)
	}
	return UsState{v: x}, nil
}

func (t UsState) Val() string { return t.v }


// --- Demographics ---
// Shen: (datatype demographics)
type Demographics struct {
	age AgeDecade
	state UsState
}

func NewDemographics(age AgeDecade, state UsState) Demographics {
	return Demographics{
		age: age,
		state: state,
	}
}

func (t Demographics) Age() AgeDecade { return t.age }

func (t Demographics) State() UsState { return t.state }


// --- KnownProfile ---
// Shen: (datatype known-profile)
type KnownProfile struct {
	id UserId
	email EmailAddr
	demo Demographics
}

func NewKnownProfile(id UserId, email EmailAddr, demo Demographics) KnownProfile {
	return KnownProfile{
		id: id,
		email: email,
		demo: demo,
	}
}

func (t KnownProfile) Id() UserId { return t.id }

func (t KnownProfile) Email() EmailAddr { return t.email }

func (t KnownProfile) Demo() Demographics { return t.demo }


// --- UnknownProfile ---
// Shen: (datatype unknown-profile)
type UnknownProfile struct {
	id UserId
	email EmailAddr
}

func NewUnknownProfile(id UserId, email EmailAddr) UnknownProfile {
	return UnknownProfile{
		id: id,
		email: email,
	}
}

func (t UnknownProfile) Id() UserId { return t.id }

func (t UnknownProfile) Email() EmailAddr { return t.email }


// --- CopyContent ---
// Shen: (datatype copy-content)
type CopyContent struct {
	body string
	demo Demographics
}

func NewCopyContent(body string, demo Demographics) CopyContent {
	return CopyContent{
		body: body,
		demo: demo,
	}
}

func (t CopyContent) Body() string { return t.body }

func (t CopyContent) Demo() Demographics { return t.demo }


// --- EmailId ---
// Shen: (datatype email-id)
type EmailId struct{ v string }

func NewEmailId(x string) EmailId { return EmailId{v: x} }

func (t EmailId) Val() string { return t.v }

func (t EmailId) String() string { return t.v }


// --- CampaignEmail ---
// Shen: (datatype campaign-email)
type CampaignEmail struct {
	id EmailId
	recipient EmailAddr
	subject string
	ctaUrl string
}

func NewCampaignEmail(id EmailId, recipient EmailAddr, subject string, ctaUrl string) CampaignEmail {
	return CampaignEmail{
		id: id,
		recipient: recipient,
		subject: subject,
		ctaUrl: ctaUrl,
	}
}

func (t CampaignEmail) Id() EmailId { return t.id }

func (t CampaignEmail) Recipient() EmailAddr { return t.recipient }

func (t CampaignEmail) Subject() string { return t.subject }

func (t CampaignEmail) CtaUrl() string { return t.ctaUrl }


// --- CopyDelivery ---
// Shen: (datatype copy-delivery)
type CopyDelivery struct {
	profile KnownProfile
	copy CopyContent
}

func NewCopyDelivery(profile KnownProfile, copy CopyContent) (CopyDelivery, error) {
	if !(profile.demo == copy.demo) {
		return CopyDelivery{}, fmt.Errorf("profile.demo must equal copy.demo")
	}
	return CopyDelivery{
		profile: profile,
		copy: copy,
	}, nil
}

func (t CopyDelivery) Profile() KnownProfile { return t.profile }

func (t CopyDelivery) Copy() CopyContent { return t.copy }


// --- PromptRequired ---
// Shen: (datatype prompt-required)
type PromptRequired = UnknownProfile


// --- ProfileUpgrade ---
// Shen: (datatype profile-upgrade)
type ProfileUpgrade struct {
	old UnknownProfile
	demo Demographics
}

func NewProfileUpgrade(old UnknownProfile, demo Demographics) ProfileUpgrade {
	return ProfileUpgrade{
		old: old,
		demo: demo,
	}
}

func (t ProfileUpgrade) Old() UnknownProfile { return t.old }

func (t ProfileUpgrade) Demo() Demographics { return t.demo }


// --- SafeCopyView ---
// Shen: (datatype safe-copy-view)
type SafeCopyView = CopyDelivery


// --- SafeCopyViewFromPrompt ---
// Shen: (datatype safe-copy-view-from-prompt)
type SafeCopyViewFromPrompt struct {
	upgrade ProfileUpgrade
	copy CopyContent
}

func NewSafeCopyViewFromPrompt(upgrade ProfileUpgrade, copy CopyContent) SafeCopyViewFromPrompt {
	return SafeCopyViewFromPrompt{
		upgrade: upgrade,
		copy: copy,
	}
}

func (t SafeCopyViewFromPrompt) Upgrade() ProfileUpgrade { return t.upgrade }

func (t SafeCopyViewFromPrompt) Copy() CopyContent { return t.copy }


