package main

// audit_elixir.go — `sb audit`: the tcb-audit gate.
//
// For lang = "elixir" the audit runs in-process:
//
//  1. drift: shengen-ex --check (guards, tracer, Ash checks match the spec);
//  2. isolation: every .ex file next to the generated guards is itself
//     generated, and no hand-written module under lib/ defines modules in
//     the generated namespace (the tracer exempts that namespace);
//  3. forgery surface the compile tracer cannot see: raw `__struct__` maps
//     in hand-written lib/ code;
//  4. wiring: mix.exs loads the tracer and lists it in elixirc_options.
//
// Other languages keep their shell audit ([commands] audit, default
// ./bin/shenguard-audit.sh), which `sb audit` simply runs.

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const shengenExHeader = "# Code generated by shengen-ex"

func cmdAudit(args []string) {
	cfg, err := LoadConfig()
	if err != nil {
		fmt.Fprintf(os.Stderr, "sb audit: %v\n", err)
		os.Exit(1)
	}
	if cfg.Lang != "elixir" {
		bin, rest := SplitCommand(cfg.Audit)
		cmd := exec.Command(bin, append(rest, args...)...)
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			os.Exit(1)
		}
		return
	}
	problems := auditElixir(cfg)
	if len(problems) > 0 {
		fmt.Fprintf(os.Stderr, "FAIL: tcb audit found %d problem(s):\n", len(problems))
		for _, p := range problems {
			fmt.Fprintf(os.Stderr, "  - %s\n", p)
		}
		os.Exit(1)
	}
	fmt.Fprintln(os.Stderr, "PASS: generated guards match the spec, the guard namespace holds only generated code, and the compile tracer is wired")
}

var structMapRe = regexp.MustCompile(`__struct__\s*(:|=>)|:__struct__\b`)

func auditElixir(cfg *Config) []string {
	var problems []string

	// 1. drift
	if err := runShengenEx(cfg, cfg.Spec, false, false, true); err != nil {
		problems = append(problems, "generated Elixir drifted from "+cfg.Spec+"; run `sb gen`")
	}

	generated := map[string]bool{}
	for _, p := range []string{cfg.Output, cfg.Elixir.TracerOut, cfg.Elixir.AshOut} {
		if p != "" {
			abs, _ := filepath.Abs(p)
			generated[abs] = true
		}
	}

	// 2a. the guard directory holds only generated files
	guardDir := filepath.Dir(cfg.Output)
	entries, _ := os.ReadDir(guardDir)
	for _, e := range entries {
		if e.IsDir() || !(strings.HasSuffix(e.Name(), ".ex") || strings.HasSuffix(e.Name(), ".exs")) {
			continue
		}
		path := filepath.Join(guardDir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil || !bytes.HasPrefix(data, []byte(shengenExHeader)) {
			problems = append(problems, fmt.Sprintf("%s is not generated by shengen-ex; the guard directory must contain only generated code", path))
		}
	}

	// 2b/3. hand-written lib/ code
	nsDecl := regexp.MustCompile(`defmodule\s+` + regexp.QuoteMeta(cfg.Pkg) + `(\.|\s)`)
	filepath.WalkDir("lib", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !(strings.HasSuffix(path, ".ex") || strings.HasSuffix(path, ".exs")) {
			return nil
		}
		abs, _ := filepath.Abs(path)
		data, rerr := os.ReadFile(path)
		if rerr != nil || generated[abs] || bytes.HasPrefix(data, []byte(shengenExHeader)) {
			return nil
		}
		if loc := nsDecl.FindIndex(data); loc != nil {
			problems = append(problems, fmt.Sprintf("%s:%d defines a module in the generated namespace %s (the tracer exempts it)", path, lineOf(data, loc[0]), cfg.Pkg))
		}
		for _, loc := range structMapRe.FindAllIndex(data, -1) {
			problems = append(problems, fmt.Sprintf("%s:%d builds or rewrites a raw __struct__ map (could forge a guard; the compile tracer cannot see it)", path, lineOf(data, loc[0])))
		}
		return nil
	})

	// 4. tracer wiring
	if cfg.Elixir.TracerOut != "" {
		mix, err := os.ReadFile("mix.exs")
		tracerMod := cfg.Pkg + ".GuardTracer"
		switch {
		case err != nil:
			problems = append(problems, "mix.exs not found")
		case !bytes.Contains(mix, []byte(filepath.ToSlash(cfg.Elixir.TracerOut))):
			problems = append(problems, fmt.Sprintf("mix.exs does not load %s (add Code.require_file(%q, __DIR__))", cfg.Elixir.TracerOut, cfg.Elixir.TracerOut))
		case !bytes.Contains(mix, []byte("tracers:")) || !bytes.Contains(mix, []byte(tracerMod)):
			problems = append(problems, fmt.Sprintf("mix.exs does not enable the tracer (elixirc_options: [tracers: [%s]])", tracerMod))
		}
	}
	return problems
}

func lineOf(data []byte, off int) int { return bytes.Count(data[:off], []byte("\n")) + 1 }
