// Code generated by shen-derive. DO NOT EDIT.
// Regenerate with: shen-derive verify <spec.shen> --func same-user?
//
// This file checks that SameUser matches the Shen spec
// by evaluating the spec on sampled inputs and comparing outputs.

package derived_test

import (
	"testing"
	shenguard "multi-tenant-api/internal/shenguard"
	derived "multi-tenant-api/internal/derived"
)

func mustUserId(x string) shenguard.UserId { return shenguard.NewUserId(x) }

func TestSpec_SameUser(t *testing.T) {
	cases := []struct {
		name string
		a shenguard.UserId
		b shenguard.UserId
		want bool
	}{
		{
			name: "case_00",
			a: mustUserId(""),
			b: mustUserId(""),
			want: true,
		},
		{
			name: "case_01",
			a: mustUserId(""),
			b: mustUserId("alice"),
			want: false,
		},
		{
			name: "case_02",
			a: mustUserId(""),
			b: mustUserId("bob"),
			want: false,
		},
		{
			name: "case_03",
			a: mustUserId("alice"),
			b: mustUserId(""),
			want: false,
		},
		{
			name: "case_04",
			a: mustUserId("alice"),
			b: mustUserId("alice"),
			want: true,
		},
		{
			name: "case_05",
			a: mustUserId("alice"),
			b: mustUserId("bob"),
			want: false,
		},
		{
			name: "case_06",
			a: mustUserId("bob"),
			b: mustUserId(""),
			want: false,
		},
		{
			name: "case_07",
			a: mustUserId("bob"),
			b: mustUserId("alice"),
			want: false,
		},
		{
			name: "case_08",
			a: mustUserId("bob"),
			b: mustUserId("bob"),
			want: true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := derived.SameUser(tc.a, tc.b)
			if got != tc.want {
				t.Fatalf("%s: spec says %v, impl returned %v", tc.name, tc.want, got)
			}
		})
	}
}
