// Code generated by shengen from specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
	"context"
	"errors"
	"github.com/pyrex41/Shen-Backpressure/shen-derive/runtime/evalhost"
)

// errRuntimeCheckRejected is returned when a runtime check
// reports the predicate is false (ok == false, err == nil).
var errRuntimeCheckRejected = errors.New("runtime check rejected")

// --- GDP brands ---
//
// Brand is the constraint for the phantom brand parameter that every
// proof type in this package carries. Any type may serve as a brand,
// including a type declared inside the function that mints the value:
//
//	type reqBrand struct{}
//	tx := NewTransaction[reqBrand](amt, from, to)
//
// A brand declared that way cannot be named by any other scope, so a
// proof about this transaction cannot be handed a different one.
type Brand interface{}

// witness is the mint mark every generated value carries. Its zero
// value is NOT minted, which is what makes the empty literal
// `T{}` — legal Go from any package, since it names no field —
// detectable. Every accessor and every consuming constructor calls
// mustBeMinted, so a forged or dropped-error value panics the first
// time anything reads it. The panic is a runtime member of the TCB;
// see docs/TRUST-MODEL.md.
type witness struct{ minted bool }

// mint marks a value as having come out of its own constructor.
func mint() witness { return witness{minted: true} }

// mustBeMinted panics unless this value came from a constructor.
func (w witness) mustBeMinted(typeName string) {
	if !w.minted {
		panic("shenguard: forged " + typeName + " value: not produced by New" + typeName + " (zero value, empty literal, or a dropped constructor error)")
	}
}

// --- AccountId ---
// Shen: (datatype account-id)
type AccountId struct {
	valid witness
	v string
}

func NewAccountId(x string) AccountId { return AccountId{valid: mint(), v: x} }

func (t AccountId) Val() string { t.valid.mustBeMinted("AccountId"); return t.v }

func (t AccountId) String() string { t.valid.mustBeMinted("AccountId"); return t.v }


// --- Amount ---
// Shen: (datatype amount)
type Amount struct {
	valid witness
	v float64
}

func NewAmount(ctx context.Context, x float64) (Amount, error) {
	ok, err := evalhost.Check(ctx, "(>= X 0)", []string{"X"}, x)
	if err != nil {
		return Amount{}, fmt.Errorf("evalhost rejected amount: %w", err)
	}
	if !ok {
		return Amount{}, fmt.Errorf("evalhost rejected amount: %w", errRuntimeCheckRejected)
	}
	return Amount{valid: mint(), v: x}, nil
}

func (t Amount) Val() float64 { t.valid.mustBeMinted("Amount"); return t.v }


// --- Transaction ---
// Shen: (datatype transaction)
type Transaction[B Brand] struct {
	valid witness
	amount Amount
	from AccountId
	to AccountId
}

func NewTransaction[B Brand](amount Amount, from AccountId, to AccountId) Transaction[B] {
	amount.valid.mustBeMinted("Amount")
	from.valid.mustBeMinted("AccountId")
	to.valid.mustBeMinted("AccountId")
	return Transaction[B]{
		valid: mint(),
		amount: amount,
		from: from,
		to: to,
	}
}

func (t Transaction[B]) Amount() Amount { t.valid.mustBeMinted("Transaction"); return t.amount }

func (t Transaction[B]) From() AccountId { t.valid.mustBeMinted("Transaction"); return t.from }

func (t Transaction[B]) To() AccountId { t.valid.mustBeMinted("Transaction"); return t.to }


// --- BalanceChecked ---
// Shen: (datatype balance-invariant)
type BalanceChecked[B Brand] struct {
	valid witness
	bal float64
	tx Transaction[B]
}

func NewBalanceChecked[B Brand](bal float64, tx Transaction[B]) (BalanceChecked[B], error) {
	tx.valid.mustBeMinted("Transaction")
	if !(bal >= tx.amount.Val()) {
		return BalanceChecked[B]{}, fmt.Errorf("bal must be >= tx.amount")
	}
	return BalanceChecked[B]{
		valid: mint(),
		bal: bal,
		tx: tx,
	}, nil
}

func (t BalanceChecked[B]) Bal() float64 { t.valid.mustBeMinted("BalanceChecked"); return t.bal }

func (t BalanceChecked[B]) Tx() Transaction[B] { t.valid.mustBeMinted("BalanceChecked"); return t.tx }


// --- AccountState ---
// Shen: (datatype account-state)
type AccountState struct {
	valid witness
	id AccountId
	balance Amount
}

func NewAccountState(id AccountId, balance Amount) AccountState {
	id.valid.mustBeMinted("AccountId")
	balance.valid.mustBeMinted("Amount")
	return AccountState{
		valid: mint(),
		id: id,
		balance: balance,
	}
}

func (t AccountState) Id() AccountId { t.valid.mustBeMinted("AccountState"); return t.id }

func (t AccountState) Balance() Amount { t.valid.mustBeMinted("AccountState"); return t.balance }


// --- SafeTransfer ---
// Shen: (datatype safe-transfer)
type SafeTransfer[B Brand] struct {
	valid witness
	tx Transaction[B]
	check BalanceChecked[B]
}

func NewSafeTransfer[B Brand](tx Transaction[B], check BalanceChecked[B]) SafeTransfer[B] {
	tx.valid.mustBeMinted("Transaction")
	check.valid.mustBeMinted("BalanceChecked")
	return SafeTransfer[B]{
		valid: mint(),
		tx: tx,
		check: check,
	}
}

func (t SafeTransfer[B]) Tx() Transaction[B] { t.valid.mustBeMinted("SafeTransfer"); return t.tx }

func (t SafeTransfer[B]) Check() BalanceChecked[B] { t.valid.mustBeMinted("SafeTransfer"); return t.check }


