// Code generated by shengen from demo/payment/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- AccountId ---
// Shen: (datatype account-id)
type AccountId struct{ v string }

func NewAccountId(x string) AccountId { return AccountId{v: x} }

func (t AccountId) Val() string { return t.v }

func (t AccountId) String() string { return t.v }


// --- Amount ---
// Shen: (datatype amount)
type Amount struct{ v float64 }

func NewAmount(x float64) (Amount, error) {
	if !(x >= 0) {
		return Amount{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return Amount{v: x}, nil
}

func (t Amount) Val() float64 { return t.v }


// --- Transaction ---
// Shen: (datatype transaction)
type Transaction struct {
	amount Amount
	from AccountId
	to AccountId
}

func NewTransaction(amount Amount, from AccountId, to AccountId) Transaction {
	return Transaction{
		amount: amount,
		from: from,
		to: to,
	}
}

func (t Transaction) Amount() Amount { return t.amount }

func (t Transaction) From() AccountId { return t.from }

func (t Transaction) To() AccountId { return t.to }


// --- BalanceChecked ---
// Shen: (datatype balance-invariant)
type BalanceChecked struct {
	bal float64
	tx Transaction
}

func NewBalanceChecked(bal float64, tx Transaction) (BalanceChecked, error) {
	if !(bal >= tx.amount.Val()) {
		return BalanceChecked{}, fmt.Errorf("bal must be >= tx.amount")
	}
	return BalanceChecked{
		bal: bal,
		tx: tx,
	}, nil
}

func (t BalanceChecked) Bal() float64 { return t.bal }

func (t BalanceChecked) Tx() Transaction { return t.tx }


// --- AccountState ---
// Shen: (datatype account-state)
type AccountState struct {
	id AccountId
	balance Amount
}

func NewAccountState(id AccountId, balance Amount) AccountState {
	return AccountState{
		id: id,
		balance: balance,
	}
}

func (t AccountState) Id() AccountId { return t.id }

func (t AccountState) Balance() Amount { return t.balance }


// --- SafeTransfer ---
// Shen: (datatype safe-transfer)
type SafeTransfer struct {
	tx Transaction
	check BalanceChecked
}

func NewSafeTransfer(tx Transaction, check BalanceChecked) SafeTransfer {
	return SafeTransfer{
		tx: tx,
		check: check,
	}
}

func (t SafeTransfer) Tx() Transaction { return t.tx }

func (t SafeTransfer) Check() BalanceChecked { return t.check }


