// Code generated by shengen from demo/k8s-infra/specs/core.shen. DO NOT EDIT.
//
// These types enforce Shen sequent-calculus invariants at the Go level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

package shenguard

import (
	"fmt"
)

// --- Namespace ---
// Shen: (datatype namespace)
type Namespace struct{ v string }

func NewNamespace(x string) (Namespace, error) {
	if !(!(x == "")) {
		return Namespace{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return Namespace{v: x}, nil
}

func (t Namespace) Val() string { return t.v }


// --- ClusterName ---
// Shen: (datatype cluster-name)
type ClusterName struct{ v string }

func NewClusterName(x string) (ClusterName, error) {
	if !(!(x == "")) {
		return ClusterName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ClusterName{v: x}, nil
}

func (t ClusterName) Val() string { return t.v }


// --- ResourceName ---
// Shen: (datatype resource-name)
type ResourceName struct{ v string }

func NewResourceName(x string) (ResourceName, error) {
	if !(!(x == "")) {
		return ResourceName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ResourceName{v: x}, nil
}

func (t ResourceName) Val() string { return t.v }


// --- ApiVersion ---
// Shen: (datatype api-version)
type ApiVersion struct{ v string }

func NewApiVersion(x string) (ApiVersion, error) {
	if !(!(x == "")) {
		return ApiVersion{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ApiVersion{v: x}, nil
}

func (t ApiVersion) Val() string { return t.v }


// --- ResourceKind ---
// Shen: (datatype resource-kind)
type ResourceKind struct{ v string }

func NewResourceKind(x string) (ResourceKind, error) {
	if !(!(x == "")) {
		return ResourceKind{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ResourceKind{v: x}, nil
}

func (t ResourceKind) Val() string { return t.v }


// --- K8sTimestamp ---
// Shen: (datatype k8s-timestamp)
type K8sTimestamp struct{ v float64 }

func NewK8sTimestamp(x float64) (K8sTimestamp, error) {
	if !(x > 0) {
		return K8sTimestamp{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return K8sTimestamp{v: x}, nil
}

func (t K8sTimestamp) Val() float64 { return t.v }


// --- GitRepoUrl ---
// Shen: (datatype git-repo-url)
type GitRepoUrl struct{ v string }

func NewGitRepoUrl(x string) (GitRepoUrl, error) {
	if !(!(x == "")) {
		return GitRepoUrl{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return GitRepoUrl{v: x}, nil
}

func (t GitRepoUrl) Val() string { return t.v }


// --- GitRevision ---
// Shen: (datatype git-revision)
type GitRevision struct{ v string }

func NewGitRevision(x string) (GitRevision, error) {
	if !(!(x == "")) {
		return GitRevision{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return GitRevision{v: x}, nil
}

func (t GitRevision) Val() string { return t.v }


// --- GitPath ---
// Shen: (datatype git-path)
type GitPath struct{ v string }

func NewGitPath(x string) (GitPath, error) {
	if !(!(x == "")) {
		return GitPath{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return GitPath{v: x}, nil
}

func (t GitPath) Val() string { return t.v }


// --- SourceBinding ---
// Shen: (datatype source-binding)
type SourceBinding struct {
	repo GitRepoUrl
	path GitPath
	revision GitRevision
	manifestCount float64
}

func NewSourceBinding(repo GitRepoUrl, path GitPath, revision GitRevision, manifestCount float64) (SourceBinding, error) {
	if !(manifestCount > 0) {
		return SourceBinding{}, fmt.Errorf("manifestCount must be > 0")
	}
	return SourceBinding{
		repo: repo,
		path: path,
		revision: revision,
		manifestCount: manifestCount,
	}, nil
}

func (t SourceBinding) Repo() GitRepoUrl { return t.repo }

func (t SourceBinding) Path() GitPath { return t.path }

func (t SourceBinding) Revision() GitRevision { return t.revision }

func (t SourceBinding) ManifestCount() float64 { return t.manifestCount }


// --- SyncWave ---
// Shen: (datatype sync-wave)
type SyncWave struct{ v float64 }

func NewSyncWave(x float64) SyncWave { return SyncWave{v: x} }

func (t SyncWave) Val() float64 { return t.v }


// --- WaveOrdered ---
// Shen: (datatype wave-ordered)
type WaveOrdered struct {
	dependencyWave SyncWave
	dependentWave SyncWave
}

func NewWaveOrdered(dependencyWave SyncWave, dependentWave SyncWave) (WaveOrdered, error) {
	if !(dependencyWave.Val() < dependentWave.Val()) {
		return WaveOrdered{}, fmt.Errorf("dependencyWave must be < dependentWave")
	}
	return WaveOrdered{
		dependencyWave: dependencyWave,
		dependentWave: dependentWave,
	}, nil
}

func (t WaveOrdered) DependencyWave() SyncWave { return t.dependencyWave }

func (t WaveOrdered) DependentWave() SyncWave { return t.dependentWave }


// --- CrdBeforeCr ---
// Shen: (datatype crd-before-cr)
type CrdBeforeCr struct {
	crdWave SyncWave
	crWave SyncWave
	crdKind ResourceKind
}

func NewCrdBeforeCr(crdWave SyncWave, crWave SyncWave, crdKind ResourceKind) (CrdBeforeCr, error) {
	if !(crdWave.Val() < crWave.Val()) {
		return CrdBeforeCr{}, fmt.Errorf("crdWave must be < crWave")
	}
	return CrdBeforeCr{
		crdWave: crdWave,
		crWave: crWave,
		crdKind: crdKind,
	}, nil
}

func (t CrdBeforeCr) CrdWave() SyncWave { return t.crdWave }

func (t CrdBeforeCr) CrWave() SyncWave { return t.crWave }

func (t CrdBeforeCr) CrdKind() ResourceKind { return t.crdKind }


// --- FieldPath ---
// Shen: (datatype field-path)
type FieldPath struct{ v string }

func NewFieldPath(x string) (FieldPath, error) {
	if !(!(x == "")) {
		return FieldPath{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return FieldPath{v: x}, nil
}

func (t FieldPath) Val() string { return t.v }


// --- OperatorMutation ---
// Shen: (datatype operator-mutation)
type OperatorMutation struct {
	operator ResourceName
	field FieldPath
}

func NewOperatorMutation(operator ResourceName, field FieldPath) OperatorMutation {
	return OperatorMutation{
		operator: operator,
		field: field,
	}
}

func (t OperatorMutation) Operator() ResourceName { return t.operator }

func (t OperatorMutation) Field() FieldPath { return t.field }


// --- IgnoreRule ---
// Shen: (datatype ignore-rule)
type IgnoreRule = FieldPath


// --- DriftCovered ---
// Shen: (datatype drift-covered)
type DriftCovered struct {
	mutation OperatorMutation
	rule IgnoreRule
}

func NewDriftCovered(mutation OperatorMutation, rule IgnoreRule) DriftCovered {
	return DriftCovered{
		mutation: mutation,
		rule: rule,
	}
}

func (t DriftCovered) Mutation() OperatorMutation { return t.mutation }

func (t DriftCovered) Rule() IgnoreRule { return t.rule }


// --- HealthStatus ---
// Shen: (datatype health-status)
type HealthStatus struct{ v string }

func NewHealthStatus(x string) (HealthStatus, error) {
	if !(map[string]bool{"healthy": true, "progressing": true, "degraded": true, "suspended": true, "missing": true, "unknown": true}[x]) {
		return HealthStatus{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return HealthStatus{v: x}, nil
}

func (t HealthStatus) Val() string { return t.v }


// --- SyncStatus ---
// Shen: (datatype sync-status)
type SyncStatus struct{ v string }

func NewSyncStatus(x string) (SyncStatus, error) {
	if !(map[string]bool{"synced": true, "out-of-sync": true, "unknown": true}[x]) {
		return SyncStatus{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return SyncStatus{v: x}, nil
}

func (t SyncStatus) Val() string { return t.v }


// --- AppState ---
// Shen: (datatype app-state)
type AppState struct {
	name ResourceName
	source SourceBinding
	health HealthStatus
	sync SyncStatus
}

func NewAppState(name ResourceName, source SourceBinding, health HealthStatus, sync SyncStatus) AppState {
	return AppState{
		name: name,
		source: source,
		health: health,
		sync: sync,
	}
}

func (t AppState) Name() ResourceName { return t.name }

func (t AppState) Source() SourceBinding { return t.source }

func (t AppState) Health() HealthStatus { return t.health }

func (t AppState) Sync() SyncStatus { return t.sync }


// --- AppPromotable ---
// Shen: (datatype app-promotable)
type AppPromotable = AppState


// --- StepId ---
// Shen: (datatype step-id)
type StepId struct{ v string }

func NewStepId(x string) (StepId, error) {
	if !(!(x == "")) {
		return StepId{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return StepId{v: x}, nil
}

func (t StepId) Val() string { return t.v }


// --- TopoOrder ---
// Shen: (datatype topo-order)
type TopoOrder struct{ v float64 }

func NewTopoOrder(x float64) (TopoOrder, error) {
	if !(x >= 0) {
		return TopoOrder{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	return TopoOrder{v: x}, nil
}

func (t TopoOrder) Val() float64 { return t.v }


// --- DagEdge ---
// Shen: (datatype dag-edge)
type DagEdge struct {
	from StepId
	to StepId
	fromOrder TopoOrder
	toOrder TopoOrder
}

func NewDagEdge(from StepId, to StepId, fromOrder TopoOrder, toOrder TopoOrder) (DagEdge, error) {
	if !(fromOrder.Val() < toOrder.Val()) {
		return DagEdge{}, fmt.Errorf("fromOrder must be < toOrder")
	}
	return DagEdge{
		from: from,
		to: to,
		fromOrder: fromOrder,
		toOrder: toOrder,
	}, nil
}

func (t DagEdge) From() StepId { return t.from }

func (t DagEdge) To() StepId { return t.to }

func (t DagEdge) FromOrder() TopoOrder { return t.fromOrder }

func (t DagEdge) ToOrder() TopoOrder { return t.toOrder }


// --- ParamType ---
// Shen: (datatype param-type)
type ParamType struct{ v string }

func NewParamType(x string) (ParamType, error) {
	if !(map[string]bool{"string": true, "number": true, "boolean": true, "json": true}[x]) {
		return ParamType{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return ParamType{v: x}, nil
}

func (t ParamType) Val() string { return t.v }


// --- ParamDecl ---
// Shen: (datatype param-decl)
type ParamDecl struct {
	name string
	type_ ParamType
}

func NewParamDecl(name string, type_ ParamType) (ParamDecl, error) {
	if !(!(name == "")) {
		return ParamDecl{}, fmt.Errorf("not: name must equal \"\"")
	}
	return ParamDecl{
		name: name,
		type_: type_,
	}, nil
}

func (t ParamDecl) Name() string { return t.name }

func (t ParamDecl) Type() ParamType { return t.type_ }


// --- ParamTypeMatch ---
// Shen: (datatype param-type-match)
type ParamTypeMatch struct {
	outputParam ParamDecl
	inputParam ParamDecl
}

func NewParamTypeMatch(outputParam ParamDecl, inputParam ParamDecl) (ParamTypeMatch, error) {
	if !(outputParam.type_ == inputParam.type_) {
		return ParamTypeMatch{}, fmt.Errorf("outputParam.type_ must equal inputParam.type_")
	}
	return ParamTypeMatch{
		outputParam: outputParam,
		inputParam: inputParam,
	}, nil
}

func (t ParamTypeMatch) OutputParam() ParamDecl { return t.outputParam }

func (t ParamTypeMatch) InputParam() ParamDecl { return t.inputParam }


// --- ArtifactName ---
// Shen: (datatype artifact-name)
type ArtifactName struct{ v string }

func NewArtifactName(x string) (ArtifactName, error) {
	if !(!(x == "")) {
		return ArtifactName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return ArtifactName{v: x}, nil
}

func (t ArtifactName) Val() string { return t.v }


// --- ArtifactOutput ---
// Shen: (datatype artifact-output)
type ArtifactOutput struct {
	step StepId
	name ArtifactName
}

func NewArtifactOutput(step StepId, name ArtifactName) ArtifactOutput {
	return ArtifactOutput{
		step: step,
		name: name,
	}
}

func (t ArtifactOutput) Step() StepId { return t.step }

func (t ArtifactOutput) Name() ArtifactName { return t.name }


// --- ArtifactInput ---
// Shen: (datatype artifact-input)
type ArtifactInput struct {
	step StepId
	name ArtifactName
}

func NewArtifactInput(step StepId, name ArtifactName) ArtifactInput {
	return ArtifactInput{
		step: step,
		name: name,
	}
}

func (t ArtifactInput) Step() StepId { return t.step }

func (t ArtifactInput) Name() ArtifactName { return t.name }


// --- ArtifactSatisfied ---
// Shen: (datatype artifact-satisfied)
type ArtifactSatisfied struct {
	input ArtifactInput
	output ArtifactOutput
	dependencyProof DagEdge
}

func NewArtifactSatisfied(input ArtifactInput, output ArtifactOutput, dependencyProof DagEdge) ArtifactSatisfied {
	return ArtifactSatisfied{
		input: input,
		output: output,
		dependencyProof: dependencyProof,
	}
}

func (t ArtifactSatisfied) Input() ArtifactInput { return t.input }

func (t ArtifactSatisfied) Output() ArtifactOutput { return t.output }

func (t ArtifactSatisfied) DependencyProof() DagEdge { return t.dependencyProof }


// --- RetryPolicy ---
// Shen: (datatype retry-policy)
type RetryPolicy struct {
	limit float64
	backoffMs float64
	factor float64
	maxBackoffMs float64
}

func NewRetryPolicy(limit float64, backoffMs float64, factor float64, maxBackoffMs float64) (RetryPolicy, error) {
	if !(limit > 0) {
		return RetryPolicy{}, fmt.Errorf("limit must be > 0")
	}
	if !(backoffMs > 0) {
		return RetryPolicy{}, fmt.Errorf("backoffMs must be > 0")
	}
	if !(factor > 0) {
		return RetryPolicy{}, fmt.Errorf("factor must be > 0")
	}
	if !(maxBackoffMs > 0) {
		return RetryPolicy{}, fmt.Errorf("maxBackoffMs must be > 0")
	}
	return RetryPolicy{
		limit: limit,
		backoffMs: backoffMs,
		factor: factor,
		maxBackoffMs: maxBackoffMs,
	}, nil
}

func (t RetryPolicy) Limit() float64 { return t.limit }

func (t RetryPolicy) BackoffMs() float64 { return t.backoffMs }

func (t RetryPolicy) Factor() float64 { return t.factor }

func (t RetryPolicy) MaxBackoffMs() float64 { return t.maxBackoffMs }


// --- DeadlineMs ---
// Shen: (datatype deadline-ms)
type DeadlineMs struct{ v float64 }

func NewDeadlineMs(x float64) (DeadlineMs, error) {
	if !(x > 0) {
		return DeadlineMs{}, fmt.Errorf("x must be > 0: %v", x)
	}
	return DeadlineMs{v: x}, nil
}

func (t DeadlineMs) Val() float64 { return t.v }


// --- RetryWithinDeadline ---
// Shen: (datatype retry-within-deadline)
type RetryWithinDeadline struct {
	policy RetryPolicy
	deadline DeadlineMs
	worstCaseMs float64
}

func NewRetryWithinDeadline(policy RetryPolicy, deadline DeadlineMs, worstCaseMs float64) (RetryWithinDeadline, error) {
	if !(worstCaseMs > 0) {
		return RetryWithinDeadline{}, fmt.Errorf("worstCaseMs must be > 0")
	}
	if !(worstCaseMs <= deadline.Val()) {
		return RetryWithinDeadline{}, fmt.Errorf("worstCaseMs must be <= deadline")
	}
	return RetryWithinDeadline{
		policy: policy,
		deadline: deadline,
		worstCaseMs: worstCaseMs,
	}, nil
}

func (t RetryWithinDeadline) Policy() RetryPolicy { return t.policy }

func (t RetryWithinDeadline) Deadline() DeadlineMs { return t.deadline }

func (t RetryWithinDeadline) WorstCaseMs() float64 { return t.worstCaseMs }


// --- CanaryWeight ---
// Shen: (datatype canary-weight)
type CanaryWeight struct{ v float64 }

func NewCanaryWeight(x float64) (CanaryWeight, error) {
	if !(x >= 0) {
		return CanaryWeight{}, fmt.Errorf("x must be >= 0: %v", x)
	}
	if !(x <= 100) {
		return CanaryWeight{}, fmt.Errorf("x must be <= 100: %v", x)
	}
	return CanaryWeight{v: x}, nil
}

func (t CanaryWeight) Val() float64 { return t.v }


// --- WeightMonotonic ---
// Shen: (datatype weight-monotonic)
type WeightMonotonic struct {
	prevWeight CanaryWeight
	nextWeight CanaryWeight
}

func NewWeightMonotonic(prevWeight CanaryWeight, nextWeight CanaryWeight) (WeightMonotonic, error) {
	if !(nextWeight.Val() >= prevWeight.Val()) {
		return WeightMonotonic{}, fmt.Errorf("nextWeight must be >= prevWeight")
	}
	return WeightMonotonic{
		prevWeight: prevWeight,
		nextWeight: nextWeight,
	}, nil
}

func (t WeightMonotonic) PrevWeight() CanaryWeight { return t.prevWeight }

func (t WeightMonotonic) NextWeight() CanaryWeight { return t.nextWeight }


// --- MetricSource ---
// Shen: (datatype metric-source)
type MetricSource struct{ v string }

func NewMetricSource(x string) (MetricSource, error) {
	if !(map[string]bool{"prometheus": true, "datadog": true, "cloudwatch": true, "newrelic": true, "web": true}[x]) {
		return MetricSource{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return MetricSource{v: x}, nil
}

func (t MetricSource) Val() string { return t.v }


// --- MetricQuery ---
// Shen: (datatype metric-query)
type MetricQuery struct {
	source MetricSource
	query string
}

func NewMetricQuery(source MetricSource, query string) (MetricQuery, error) {
	if !(!(query == "")) {
		return MetricQuery{}, fmt.Errorf("not: query must equal \"\"")
	}
	return MetricQuery{
		source: source,
		query: query,
	}, nil
}

func (t MetricQuery) Source() MetricSource { return t.source }

func (t MetricQuery) Query() string { return t.query }


// --- AnalysisReachable ---
// Shen: (datatype analysis-reachable)
type AnalysisReachable struct {
	query MetricQuery
	sampleCount float64
}

func NewAnalysisReachable(query MetricQuery, sampleCount float64) (AnalysisReachable, error) {
	if !(sampleCount > 0) {
		return AnalysisReachable{}, fmt.Errorf("sampleCount must be > 0")
	}
	return AnalysisReachable{
		query: query,
		sampleCount: sampleCount,
	}, nil
}

func (t AnalysisReachable) Query() MetricQuery { return t.query }

func (t AnalysisReachable) SampleCount() float64 { return t.sampleCount }


// --- IngressType ---
// Shen: (datatype ingress-type)
type IngressType struct{ v string }

func NewIngressType(x string) (IngressType, error) {
	if !(map[string]bool{"nginx": true, "istio": true, "traefik": true, "alb": true, "contour": true, "ambassador": true}[x]) {
		return IngressType{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return IngressType{v: x}, nil
}

func (t IngressType) Val() string { return t.v }


// --- TrafficSplitCapable ---
// Shen: (datatype traffic-split-capable)
type TrafficSplitCapable struct {
	ingress IngressType
	supportsWeightedRouting bool
}

func NewTrafficSplitCapable(ingress IngressType, supportsWeightedRouting bool) (TrafficSplitCapable, error) {
	if !(supportsWeightedRouting == true) {
		return TrafficSplitCapable{}, fmt.Errorf("supportsWeightedRouting must equal true")
	}
	return TrafficSplitCapable{
		ingress: ingress,
		supportsWeightedRouting: supportsWeightedRouting,
	}, nil
}

func (t TrafficSplitCapable) Ingress() IngressType { return t.ingress }

func (t TrafficSplitCapable) SupportsWeightedRouting() bool { return t.supportsWeightedRouting }


// --- RolloutTerminalState ---
// Shen: (datatype rollout-terminal-state)
type RolloutTerminalState struct{ v string }

func NewRolloutTerminalState(x string) (RolloutTerminalState, error) {
	if !(map[string]bool{"completed": true, "aborted": true, "degraded": true}[x]) {
		return RolloutTerminalState{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return RolloutTerminalState{v: x}, nil
}

func (t RolloutTerminalState) Val() string { return t.v }


// --- StepWithFallback ---
// Shen: (datatype step-with-fallback)
type StepWithFallback struct {
	weight CanaryWeight
	analysis AnalysisReachable
	onFailure RolloutTerminalState
}

func NewStepWithFallback(weight CanaryWeight, analysis AnalysisReachable, onFailure RolloutTerminalState) StepWithFallback {
	return StepWithFallback{
		weight: weight,
		analysis: analysis,
		onFailure: onFailure,
	}
}

func (t StepWithFallback) Weight() CanaryWeight { return t.weight }

func (t StepWithFallback) Analysis() AnalysisReachable { return t.analysis }

func (t StepWithFallback) OnFailure() RolloutTerminalState { return t.onFailure }


// --- SafeRollout ---
// Shen: (datatype safe-rollout)
type SafeRollout struct {
	backendCapable TrafficSplitCapable
	steps float64
	allStepsHaveFallback bool
}

func NewSafeRollout(backendCapable TrafficSplitCapable, steps float64, allStepsHaveFallback bool) (SafeRollout, error) {
	if !(steps > 0) {
		return SafeRollout{}, fmt.Errorf("steps must be > 0")
	}
	if !(allStepsHaveFallback == true) {
		return SafeRollout{}, fmt.Errorf("allStepsHaveFallback must equal true")
	}
	return SafeRollout{
		backendCapable: backendCapable,
		steps: steps,
		allStepsHaveFallback: allStepsHaveFallback,
	}, nil
}

func (t SafeRollout) BackendCapable() TrafficSplitCapable { return t.backendCapable }

func (t SafeRollout) Steps() float64 { return t.steps }

func (t SafeRollout) AllStepsHaveFallback() bool { return t.allStepsHaveFallback }


// --- ProviderName ---
// Shen: (datatype provider-name)
type ProviderName struct{ v string }

func NewProviderName(x string) (ProviderName, error) {
	if !(map[string]bool{"aws": true, "gcp": true, "azure": true}[x]) {
		return ProviderName{}, fmt.Errorf("x must be in the valid set: %v", x)
	}
	return ProviderName{v: x}, nil
}

func (t ProviderName) Val() string { return t.v }


// --- ProviderConfig ---
// Shen: (datatype provider-config)
type ProviderConfig struct {
	name ResourceName
	provider ProviderName
}

func NewProviderConfig(name ResourceName, provider ProviderName) ProviderConfig {
	return ProviderConfig{
		name: name,
		provider: provider,
	}
}

func (t ProviderConfig) Name() ResourceName { return t.name }

func (t ProviderConfig) Provider() ProviderName { return t.provider }


// --- CredentialValid ---
// Shen: (datatype credential-valid)
type CredentialValid struct {
	config ProviderConfig
	expiresAt float64
	now float64
}

func NewCredentialValid(config ProviderConfig, expiresAt float64, now float64) (CredentialValid, error) {
	if !(expiresAt > now) {
		return CredentialValid{}, fmt.Errorf("expiresAt must be > now")
	}
	return CredentialValid{
		config: config,
		expiresAt: expiresAt,
		now: now,
	}, nil
}

func (t CredentialValid) Config() ProviderConfig { return t.config }

func (t CredentialValid) ExpiresAt() float64 { return t.expiresAt }

func (t CredentialValid) Now() float64 { return t.now }


// --- XrdName ---
// Shen: (datatype xrd-name)
type XrdName struct{ v string }

func NewXrdName(x string) (XrdName, error) {
	if !(!(x == "")) {
		return XrdName{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return XrdName{v: x}, nil
}

func (t XrdName) Val() string { return t.v }


// --- XrdVersion ---
// Shen: (datatype xrd-version)
type XrdVersion struct {
	major float64
	minor float64
}

func NewXrdVersion(major float64, minor float64) (XrdVersion, error) {
	if !(major >= 0) {
		return XrdVersion{}, fmt.Errorf("major must be >= 0")
	}
	if !(minor >= 0) {
		return XrdVersion{}, fmt.Errorf("minor must be >= 0")
	}
	return XrdVersion{
		major: major,
		minor: minor,
	}, nil
}

func (t XrdVersion) Major() float64 { return t.major }

func (t XrdVersion) Minor() float64 { return t.minor }


// --- PatchSourcePath ---
// Shen: (datatype patch-source-path)
type PatchSourcePath struct{ v string }

func NewPatchSourcePath(x string) (PatchSourcePath, error) {
	if !(!(x == "")) {
		return PatchSourcePath{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return PatchSourcePath{v: x}, nil
}

func (t PatchSourcePath) Val() string { return t.v }


// --- PatchTargetPath ---
// Shen: (datatype patch-target-path)
type PatchTargetPath struct{ v string }

func NewPatchTargetPath(x string) (PatchTargetPath, error) {
	if !(!(x == "")) {
		return PatchTargetPath{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return PatchTargetPath{v: x}, nil
}

func (t PatchTargetPath) Val() string { return t.v }


// --- PatchSourceValid ---
// Shen: (datatype patch-source-valid)
type PatchSourceValid struct {
	path PatchSourcePath
	xrd XrdName
	pathExists bool
}

func NewPatchSourceValid(path PatchSourcePath, xrd XrdName, pathExists bool) (PatchSourceValid, error) {
	if !(pathExists == true) {
		return PatchSourceValid{}, fmt.Errorf("pathExists must equal true")
	}
	return PatchSourceValid{
		path: path,
		xrd: xrd,
		pathExists: pathExists,
	}, nil
}

func (t PatchSourceValid) Path() PatchSourcePath { return t.path }

func (t PatchSourceValid) Xrd() XrdName { return t.xrd }

func (t PatchSourceValid) PathExists() bool { return t.pathExists }


// --- PatchTargetValid ---
// Shen: (datatype patch-target-valid)
type PatchTargetValid struct {
	path PatchTargetPath
	resourceKind ResourceKind
	pathExists bool
}

func NewPatchTargetValid(path PatchTargetPath, resourceKind ResourceKind, pathExists bool) (PatchTargetValid, error) {
	if !(pathExists == true) {
		return PatchTargetValid{}, fmt.Errorf("pathExists must equal true")
	}
	return PatchTargetValid{
		path: path,
		resourceKind: resourceKind,
		pathExists: pathExists,
	}, nil
}

func (t PatchTargetValid) Path() PatchTargetPath { return t.path }

func (t PatchTargetValid) ResourceKind() ResourceKind { return t.resourceKind }

func (t PatchTargetValid) PathExists() bool { return t.pathExists }


// --- PatchValid ---
// Shen: (datatype patch-valid)
type PatchValid struct {
	source PatchSourceValid
	target PatchTargetValid
}

func NewPatchValid(source PatchSourceValid, target PatchTargetValid) PatchValid {
	return PatchValid{
		source: source,
		target: target,
	}
}

func (t PatchValid) Source() PatchSourceValid { return t.source }

func (t PatchValid) Target() PatchTargetValid { return t.target }


// --- ManagedResource ---
// Shen: (datatype managed-resource)
type ManagedResource struct {
	name ResourceName
	kind ResourceKind
	provider ProviderConfig
}

func NewManagedResource(name ResourceName, kind ResourceKind, provider ProviderConfig) ManagedResource {
	return ManagedResource{
		name: name,
		kind: kind,
		provider: provider,
	}
}

func (t ManagedResource) Name() ResourceName { return t.name }

func (t ManagedResource) Kind() ResourceKind { return t.kind }

func (t ManagedResource) Provider() ProviderConfig { return t.provider }


// --- MrDependency ---
// Shen: (datatype mr-dependency)
type MrDependency struct {
	dependent ManagedResource
	dependency ManagedResource
	dependencyReady bool
}

func NewMrDependency(dependent ManagedResource, dependency ManagedResource, dependencyReady bool) (MrDependency, error) {
	if !(dependencyReady == true) {
		return MrDependency{}, fmt.Errorf("dependencyReady must equal true")
	}
	return MrDependency{
		dependent: dependent,
		dependency: dependency,
		dependencyReady: dependencyReady,
	}, nil
}

func (t MrDependency) Dependent() ManagedResource { return t.dependent }

func (t MrDependency) Dependency() ManagedResource { return t.dependency }

func (t MrDependency) DependencyReady() bool { return t.dependencyReady }


// --- XrdCompatible ---
// Shen: (datatype xrd-compatible)
type XrdCompatible struct {
	oldVersion XrdVersion
	newVersion XrdVersion
	noRemovedFields bool
	noNewRequiredFields bool
}

func NewXrdCompatible(oldVersion XrdVersion, newVersion XrdVersion, noRemovedFields bool, noNewRequiredFields bool) (XrdCompatible, error) {
	if !(noRemovedFields == true) {
		return XrdCompatible{}, fmt.Errorf("noRemovedFields must equal true")
	}
	if !(noNewRequiredFields == true) {
		return XrdCompatible{}, fmt.Errorf("noNewRequiredFields must equal true")
	}
	if !(oldVersion.major == newVersion.major) {
		return XrdCompatible{}, fmt.Errorf("oldVersion.major must equal newVersion.major")
	}
	return XrdCompatible{
		oldVersion: oldVersion,
		newVersion: newVersion,
		noRemovedFields: noRemovedFields,
		noNewRequiredFields: noNewRequiredFields,
	}, nil
}

func (t XrdCompatible) OldVersion() XrdVersion { return t.oldVersion }

func (t XrdCompatible) NewVersion() XrdVersion { return t.newVersion }

func (t XrdCompatible) NoRemovedFields() bool { return t.noRemovedFields }

func (t XrdCompatible) NoNewRequiredFields() bool { return t.noNewRequiredFields }


// --- ResourceComplete ---
// Shen: (datatype resource-complete)
type ResourceComplete struct {
	resource ManagedResource
	requiredFields float64
	populatedFields float64
}

func NewResourceComplete(resource ManagedResource, requiredFields float64, populatedFields float64) (ResourceComplete, error) {
	if !(requiredFields > 0) {
		return ResourceComplete{}, fmt.Errorf("requiredFields must be > 0")
	}
	if !(populatedFields == requiredFields) {
		return ResourceComplete{}, fmt.Errorf("populatedFields must equal requiredFields")
	}
	return ResourceComplete{
		resource: resource,
		requiredFields: requiredFields,
		populatedFields: populatedFields,
	}, nil
}

func (t ResourceComplete) Resource() ManagedResource { return t.resource }

func (t ResourceComplete) RequiredFields() float64 { return t.requiredFields }

func (t ResourceComplete) PopulatedFields() float64 { return t.populatedFields }


// --- MrCredentialed ---
// Shen: (datatype mr-credentialed)
type MrCredentialed struct {
	resource ManagedResource
	credential CredentialValid
}

func NewMrCredentialed(resource ManagedResource, credential CredentialValid) MrCredentialed {
	return MrCredentialed{
		resource: resource,
		credential: credential,
	}
}

func (t MrCredentialed) Resource() ManagedResource { return t.resource }

func (t MrCredentialed) Credential() CredentialValid { return t.credential }


// --- GitopsDeployReady ---
// Shen: (datatype gitops-deploy-ready)
type GitopsDeployReady struct {
	app AppPromotable
	rollout SafeRollout
}

func NewGitopsDeployReady(app AppPromotable, rollout SafeRollout) GitopsDeployReady {
	return GitopsDeployReady{
		app: app,
		rollout: rollout,
	}
}

func (t GitopsDeployReady) App() AppPromotable { return t.app }

func (t GitopsDeployReady) Rollout() SafeRollout { return t.rollout }


// --- InfraProvisioned ---
// Shen: (datatype infra-provisioned)
type InfraProvisioned struct {
	resource ResourceComplete
	credential MrCredentialed
}

func NewInfraProvisioned(resource ResourceComplete, credential MrCredentialed) InfraProvisioned {
	return InfraProvisioned{
		resource: resource,
		credential: credential,
	}
}

func (t InfraProvisioned) Resource() ResourceComplete { return t.resource }

func (t InfraProvisioned) Credential() MrCredentialed { return t.credential }


// --- PlatformReady ---
// Shen: (datatype platform-ready)
type PlatformReady struct {
	infra InfraProvisioned
	deploy GitopsDeployReady
}

func NewPlatformReady(infra InfraProvisioned, deploy GitopsDeployReady) PlatformReady {
	return PlatformReady{
		infra: infra,
		deploy: deploy,
	}
}

func (t PlatformReady) Infra() InfraProvisioned { return t.infra }

func (t PlatformReady) Deploy() GitopsDeployReady { return t.deploy }


// --- DesiredResource ---
// Shen: (datatype desired-resource)
type DesiredResource struct {
	name ResourceName
	kind ResourceKind
	ready bool
}

func NewDesiredResource(name ResourceName, kind ResourceKind, ready bool) DesiredResource {
	return DesiredResource{
		name: name,
		kind: kind,
		ready: ready,
	}
}

func (t DesiredResource) Name() ResourceName { return t.name }

func (t DesiredResource) Kind() ResourceKind { return t.kind }

func (t DesiredResource) Ready() bool { return t.ready }


// --- PatchedResource ---
// Shen: (datatype patched-resource)
type PatchedResource struct {
	resource DesiredResource
	patchesApplied float64
	patchesValid float64
}

func NewPatchedResource(resource DesiredResource, patchesApplied float64, patchesValid float64) (PatchedResource, error) {
	if !(patchesApplied > 0) {
		return PatchedResource{}, fmt.Errorf("patchesApplied must be > 0")
	}
	if !(patchesValid == patchesApplied) {
		return PatchedResource{}, fmt.Errorf("patchesValid must equal patchesApplied")
	}
	return PatchedResource{
		resource: resource,
		patchesApplied: patchesApplied,
		patchesValid: patchesValid,
	}, nil
}

func (t PatchedResource) Resource() DesiredResource { return t.resource }

func (t PatchedResource) PatchesApplied() float64 { return t.patchesApplied }

func (t PatchedResource) PatchesValid() float64 { return t.patchesValid }


// --- FunctionResponseValid ---
// Shen: (datatype function-response-valid)
type FunctionResponseValid struct {
	resourceCount float64
	allPatched bool
}

func NewFunctionResponseValid(resourceCount float64, allPatched bool) (FunctionResponseValid, error) {
	if !(resourceCount > 0) {
		return FunctionResponseValid{}, fmt.Errorf("resourceCount must be > 0")
	}
	if !(allPatched == true) {
		return FunctionResponseValid{}, fmt.Errorf("allPatched must equal true")
	}
	return FunctionResponseValid{
		resourceCount: resourceCount,
		allPatched: allPatched,
	}, nil
}

func (t FunctionResponseValid) ResourceCount() float64 { return t.resourceCount }

func (t FunctionResponseValid) AllPatched() bool { return t.allPatched }


// --- EncryptionEnabled ---
// Shen: (datatype encryption-enabled)
type EncryptionEnabled struct {
	resource ManagedResource
	algorithm string
}

func NewEncryptionEnabled(resource ManagedResource, algorithm string) (EncryptionEnabled, error) {
	if !(!(algorithm == "")) {
		return EncryptionEnabled{}, fmt.Errorf("not: algorithm must equal \"\"")
	}
	return EncryptionEnabled{
		resource: resource,
		algorithm: algorithm,
	}, nil
}

func (t EncryptionEnabled) Resource() ManagedResource { return t.resource }

func (t EncryptionEnabled) Algorithm() string { return t.algorithm }


// --- PrivateNetwork ---
// Shen: (datatype private-network)
type PrivateNetwork struct {
	resource ManagedResource
	subnetType string
	publicAccess bool
}

func NewPrivateNetwork(resource ManagedResource, subnetType string, publicAccess bool) (PrivateNetwork, error) {
	if !(publicAccess == false) {
		return PrivateNetwork{}, fmt.Errorf("publicAccess must equal false")
	}
	if !(!(subnetType == "")) {
		return PrivateNetwork{}, fmt.Errorf("not: subnetType must equal \"\"")
	}
	return PrivateNetwork{
		resource: resource,
		subnetType: subnetType,
		publicAccess: publicAccess,
	}, nil
}

func (t PrivateNetwork) Resource() ManagedResource { return t.resource }

func (t PrivateNetwork) SubnetType() string { return t.subnetType }

func (t PrivateNetwork) PublicAccess() bool { return t.publicAccess }


// --- CostTagged ---
// Shen: (datatype cost-tagged)
type CostTagged struct {
	resource ManagedResource
	team string
	environment string
}

func NewCostTagged(resource ManagedResource, team string, environment string) (CostTagged, error) {
	if !(!(team == "")) {
		return CostTagged{}, fmt.Errorf("not: team must equal \"\"")
	}
	if !(!(environment == "")) {
		return CostTagged{}, fmt.Errorf("not: environment must equal \"\"")
	}
	return CostTagged{
		resource: resource,
		team: team,
		environment: environment,
	}, nil
}

func (t CostTagged) Resource() ManagedResource { return t.resource }

func (t CostTagged) Team() string { return t.team }

func (t CostTagged) Environment() string { return t.environment }


// --- PolicyCompliant ---
// Shen: (datatype policy-compliant)
type PolicyCompliant struct {
	encrypted EncryptionEnabled
	private PrivateNetwork
	tagged CostTagged
}

func NewPolicyCompliant(encrypted EncryptionEnabled, private PrivateNetwork, tagged CostTagged) PolicyCompliant {
	return PolicyCompliant{
		encrypted: encrypted,
		private: private,
		tagged: tagged,
	}
}

func (t PolicyCompliant) Encrypted() EncryptionEnabled { return t.encrypted }

func (t PolicyCompliant) Private() PrivateNetwork { return t.private }

func (t PolicyCompliant) Tagged() CostTagged { return t.tagged }


// --- SecureDbClaim ---
// Shen: (datatype secure-db-claim)
type SecureDbClaim struct {
	resource ResourceComplete
	policy PolicyCompliant
	credential MrCredentialed
}

func NewSecureDbClaim(resource ResourceComplete, policy PolicyCompliant, credential MrCredentialed) SecureDbClaim {
	return SecureDbClaim{
		resource: resource,
		policy: policy,
		credential: credential,
	}
}

func (t SecureDbClaim) Resource() ResourceComplete { return t.resource }

func (t SecureDbClaim) Policy() PolicyCompliant { return t.policy }

func (t SecureDbClaim) Credential() MrCredentialed { return t.credential }


// --- ManifestSet ---
// Shen: (datatype manifest-set)
type ManifestSet struct {
	source SourceBinding
	resourceCount float64
}

func NewManifestSet(source SourceBinding, resourceCount float64) (ManifestSet, error) {
	if !(resourceCount > 0) {
		return ManifestSet{}, fmt.Errorf("resourceCount must be > 0")
	}
	return ManifestSet{
		source: source,
		resourceCount: resourceCount,
	}, nil
}

func (t ManifestSet) Source() SourceBinding { return t.source }

func (t ManifestSet) ResourceCount() float64 { return t.resourceCount }


// --- WavesValid ---
// Shen: (datatype waves-valid)
type WavesValid struct {
	manifests ManifestSet
	waveCount float64
	allOrdered bool
}

func NewWavesValid(manifests ManifestSet, waveCount float64, allOrdered bool) (WavesValid, error) {
	if !(waveCount > 0) {
		return WavesValid{}, fmt.Errorf("waveCount must be > 0")
	}
	if !(allOrdered == true) {
		return WavesValid{}, fmt.Errorf("allOrdered must equal true")
	}
	return WavesValid{
		manifests: manifests,
		waveCount: waveCount,
		allOrdered: allOrdered,
	}, nil
}

func (t WavesValid) Manifests() ManifestSet { return t.manifests }

func (t WavesValid) WaveCount() float64 { return t.waveCount }

func (t WavesValid) AllOrdered() bool { return t.allOrdered }


// --- CrdsOrdered ---
// Shen: (datatype crds-ordered)
type CrdsOrdered struct {
	manifests ManifestSet
	crdCount float64
	allPrecede bool
}

func NewCrdsOrdered(manifests ManifestSet, crdCount float64, allPrecede bool) (CrdsOrdered, error) {
	if !(crdCount >= 0) {
		return CrdsOrdered{}, fmt.Errorf("crdCount must be >= 0")
	}
	if !(allPrecede == true) {
		return CrdsOrdered{}, fmt.Errorf("allPrecede must equal true")
	}
	return CrdsOrdered{
		manifests: manifests,
		crdCount: crdCount,
		allPrecede: allPrecede,
	}, nil
}

func (t CrdsOrdered) Manifests() ManifestSet { return t.manifests }

func (t CrdsOrdered) CrdCount() float64 { return t.crdCount }

func (t CrdsOrdered) AllPrecede() bool { return t.allPrecede }


// --- PresyncCleared ---
// Shen: (datatype presync-cleared)
type PresyncCleared struct {
	waves WavesValid
	crds CrdsOrdered
}

func NewPresyncCleared(waves WavesValid, crds CrdsOrdered) PresyncCleared {
	return PresyncCleared{
		waves: waves,
		crds: crds,
	}
}

func (t PresyncCleared) Waves() WavesValid { return t.waves }

func (t PresyncCleared) Crds() CrdsOrdered { return t.crds }


// --- ClaimSubmitted ---
// Shen: (datatype claim-submitted)
type ClaimSubmitted struct {
	kind ResourceKind
	name ResourceName
	namespace Namespace
}

func NewClaimSubmitted(kind ResourceKind, name ResourceName, namespace Namespace) ClaimSubmitted {
	return ClaimSubmitted{
		kind: kind,
		name: name,
		namespace: namespace,
	}
}

func (t ClaimSubmitted) Kind() ResourceKind { return t.kind }

func (t ClaimSubmitted) Name() ResourceName { return t.name }

func (t ClaimSubmitted) Namespace() Namespace { return t.namespace }


// --- AdmissionAllowed ---
// Shen: (datatype admission-allowed)
type AdmissionAllowed struct {
	claim ClaimSubmitted
	schemaValid bool
	policyValid bool
	credentialValid bool
}

func NewAdmissionAllowed(claim ClaimSubmitted, schemaValid bool, policyValid bool, credentialValid bool) (AdmissionAllowed, error) {
	if !(schemaValid == true) {
		return AdmissionAllowed{}, fmt.Errorf("schemaValid must equal true")
	}
	if !(policyValid == true) {
		return AdmissionAllowed{}, fmt.Errorf("policyValid must equal true")
	}
	if !(credentialValid == true) {
		return AdmissionAllowed{}, fmt.Errorf("credentialValid must equal true")
	}
	return AdmissionAllowed{
		claim: claim,
		schemaValid: schemaValid,
		policyValid: policyValid,
		credentialValid: credentialValid,
	}, nil
}

func (t AdmissionAllowed) Claim() ClaimSubmitted { return t.claim }

func (t AdmissionAllowed) SchemaValid() bool { return t.schemaValid }

func (t AdmissionAllowed) PolicyValid() bool { return t.policyValid }

func (t AdmissionAllowed) CredentialValid() bool { return t.credentialValid }


// --- PrSha ---
// Shen: (datatype pr-sha)
type PrSha struct{ v string }

func NewPrSha(x string) (PrSha, error) {
	if !(!(x == "")) {
		return PrSha{}, fmt.Errorf("not: x must equal \"\": %v", x)
	}
	return PrSha{v: x}, nil
}

func (t PrSha) Val() string { return t.v }


// --- CiGatePassed ---
// Shen: (datatype ci-gate-passed)
type CiGatePassed struct {
	sha PrSha
	shenTcPassed bool
	guardsCompiled bool
	testsPassed bool
}

func NewCiGatePassed(sha PrSha, shenTcPassed bool, guardsCompiled bool, testsPassed bool) (CiGatePassed, error) {
	if !(shenTcPassed == true) {
		return CiGatePassed{}, fmt.Errorf("shenTcPassed must equal true")
	}
	if !(guardsCompiled == true) {
		return CiGatePassed{}, fmt.Errorf("guardsCompiled must equal true")
	}
	if !(testsPassed == true) {
		return CiGatePassed{}, fmt.Errorf("testsPassed must equal true")
	}
	return CiGatePassed{
		sha: sha,
		shenTcPassed: shenTcPassed,
		guardsCompiled: guardsCompiled,
		testsPassed: testsPassed,
	}, nil
}

func (t CiGatePassed) Sha() PrSha { return t.sha }

func (t CiGatePassed) ShenTcPassed() bool { return t.shenTcPassed }

func (t CiGatePassed) GuardsCompiled() bool { return t.guardsCompiled }

func (t CiGatePassed) TestsPassed() bool { return t.testsPassed }


// --- MergeReady ---
// Shen: (datatype merge-ready)
type MergeReady struct {
	ciGate CiGatePassed
	presync PresyncCleared
}

func NewMergeReady(ciGate CiGatePassed, presync PresyncCleared) MergeReady {
	return MergeReady{
		ciGate: ciGate,
		presync: presync,
	}
}

func (t MergeReady) CiGate() CiGatePassed { return t.ciGate }

func (t MergeReady) Presync() PresyncCleared { return t.presync }


