// Code generated by shengen-ts from examples/payment/specs/core.shen. DO NOT EDIT.
//
// Reference output of the TypeScript emitter with GDP brands (W1):
//
//   node --experimental-strip-types cmd/shengen-ts/shengen.ts \
//     examples/payment/specs/core.shen --brands
//
// Read it next to internal/shenguard/guards_gen.go, the Go output for
// the same spec. Both bind a proof to its subject the same way:
// BalanceChecked<B> is evidence about Transaction<B>, and
// SafeTransfer.createOrThrow will not take a mismatched pair.
//
// Two caveats specific to this file:
//
//  - The spec's `amount` premise is annotated `:runtime-via :eval`
//    (profile B, docs/RUNTIME-VIA.md). The Go emitter calls the
//    embedded Shen evaluator host for it. TypeScript has no such host
//    yet, so the premise is discharged by the inlined predicate
//    instead — the same proposition, a different discharger. That gap
//    is why this is a reference file and not a gated artifact.
//  - This example's application code is Go; nothing imports this file.
//    It is committed so the TypeScript lowering of brands is reviewable
//    next to the Go one.
//
// These types enforce Shen sequent-calculus invariants at the TypeScript level.
// Constructors are the ONLY way to create these types — bypassing them
// is a violation of the formal spec.

// --- GDP brands ---
//
// Brand is the constraint for the phantom brand parameter that every
// proof class in this module carries. Any type may serve as a brand;
// the idiom is a `unique symbol` declared in the scope that mints the
// value, which no other scope can name:
//
//   declare const reqBrand: unique symbol;
//   const tx = Transaction.createOrThrow<typeof reqBrand>(amt, from, to);
//
// A proof about that transaction cannot then be handed a different one.
export type Brand = unknown;

// The mint mark. A class's private constructor already stops `new`
// from outside this module, but it does not stop a structural forgery:
// `Object.create(TenantAccess.prototype)`, a JSON round-trip, or a
// cast through `unknown` all produce an object of the proof type that
// no constructor ever checked. Every accessor calls mustBeMinted, so
// such a value throws the first time anything reads it. The throw is a
// runtime member of the TCB; see docs/TRUST-MODEL.md.
const MINTED: unique symbol = Symbol("shenguard.minted");
type Witness = typeof MINTED;
function mint(): Witness {
  return MINTED;
}
function mustBeMinted(w: Witness | undefined, typeName: string): void {
  if (w !== MINTED) {
    throw new Error(
      `shenguard: forged ${typeName} value: not produced by ${typeName}.createOrThrow ` +
        `(structural cast, Object.create, or a deserialized object)`
    );
  }
}

// --- AccountId ---
// Shen: (datatype account-id)
export class AccountId {
  private readonly _witness: Witness = mint();
  private readonly _v: string;
  private constructor(v: string) { this._v = v; }
  static createOrThrow(x: string): AccountId { return new AccountId(x); }
  static tryCreate(x: string): AccountId | Error {
    try { return AccountId.createOrThrow(x); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  val(): string { mustBeMinted(this._witness, "AccountId"); return this._v; }
  toString(): string { mustBeMinted(this._witness, "AccountId"); return this._v; }
}
export function mustAccountId(x: string): AccountId {
  return AccountId.createOrThrow(x);
}

// --- Amount ---
// Shen: (datatype amount)
export class Amount {
  private readonly _witness: Witness = mint();
  private readonly _v: number;
  private constructor(v: number) { this._v = v; }
  static createOrThrow(x: number): Amount {
    if (!(x >= 0)) throw new Error(`x must be >= 0: ${x}`);
    return new Amount(x);
  }
  static tryCreate(x: number): Amount | Error {
    try { return Amount.createOrThrow(x); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  val(): number { mustBeMinted(this._witness, "Amount"); return this._v; }
}
export function mustAmount(x: number): Amount {
  return Amount.createOrThrow(x);
}

// --- Transaction ---
// Shen: (datatype transaction)
export class Transaction<B extends Brand> {
  private readonly _witness: Witness = mint();
  /** Phantom brand marker — never read; makes B invariant. */
  declare private readonly _brandB: (b: B) => B;
  private readonly _amount: Amount;
  private readonly _from: AccountId;
  private readonly _to: AccountId;
  private constructor(amount: Amount, from: AccountId, to: AccountId) {
    this._amount = amount;
    this._from = from;
    this._to = to;
  }
  static createOrThrow<B extends Brand>(amount: Amount, from: AccountId, to: AccountId): Transaction<B> {
    mustBeMinted((amount as unknown as { _witness?: Witness })._witness, "Amount");
    mustBeMinted((from as unknown as { _witness?: Witness })._witness, "AccountId");
    mustBeMinted((to as unknown as { _witness?: Witness })._witness, "AccountId");
    return new Transaction<B>(amount, from, to);
  }
  static tryCreate<B extends Brand>(amount: Amount, from: AccountId, to: AccountId): Transaction<B> | Error {
    try { return Transaction.createOrThrow<B>(amount, from, to); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  amount(): Amount { mustBeMinted(this._witness, "Transaction"); return this._amount; }
  from(): AccountId { mustBeMinted(this._witness, "Transaction"); return this._from; }
  to(): AccountId { mustBeMinted(this._witness, "Transaction"); return this._to; }
}
export function mustTransaction<B extends Brand>(amount: Amount, from: AccountId, to: AccountId): Transaction<B> {
  return Transaction.createOrThrow<B>(amount, from, to);
}

// --- BalanceChecked ---
// Shen: (datatype balance-invariant)
export class BalanceChecked<B extends Brand> {
  private readonly _witness: Witness = mint();
  /** Phantom brand marker — never read; makes B invariant. */
  declare private readonly _brandB: (b: B) => B;
  private readonly _bal: number;
  private readonly _tx: Transaction<B>;
  private constructor(bal: number, tx: Transaction<B>) {
    this._bal = bal;
    this._tx = tx;
  }
  static createOrThrow<B extends Brand>(bal: number, tx: Transaction<B>): BalanceChecked<B> {
    mustBeMinted((tx as unknown as { _witness?: Witness })._witness, "Transaction");
    if (!(bal >= tx.amount().val())) throw new Error(`bal must be >= tx.amount()`);
    return new BalanceChecked<B>(bal, tx);
  }
  static tryCreate<B extends Brand>(bal: number, tx: Transaction<B>): BalanceChecked<B> | Error {
    try { return BalanceChecked.createOrThrow<B>(bal, tx); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  bal(): number { mustBeMinted(this._witness, "BalanceChecked"); return this._bal; }
  tx(): Transaction<B> { mustBeMinted(this._witness, "BalanceChecked"); return this._tx; }
}
export function mustBalanceChecked<B extends Brand>(bal: number, tx: Transaction<B>): BalanceChecked<B> {
  return BalanceChecked.createOrThrow<B>(bal, tx);
}

// --- AccountState ---
// Shen: (datatype account-state)
export class AccountState {
  private readonly _witness: Witness = mint();
  private readonly _id: AccountId;
  private readonly _balance: Amount;
  private constructor(id: AccountId, balance: Amount) {
    this._id = id;
    this._balance = balance;
  }
  static createOrThrow(id: AccountId, balance: Amount): AccountState {
    mustBeMinted((id as unknown as { _witness?: Witness })._witness, "AccountId");
    mustBeMinted((balance as unknown as { _witness?: Witness })._witness, "Amount");
    return new AccountState(id, balance);
  }
  static tryCreate(id: AccountId, balance: Amount): AccountState | Error {
    try { return AccountState.createOrThrow(id, balance); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  id(): AccountId { mustBeMinted(this._witness, "AccountState"); return this._id; }
  balance(): Amount { mustBeMinted(this._witness, "AccountState"); return this._balance; }
}
export function mustAccountState(id: AccountId, balance: Amount): AccountState {
  return AccountState.createOrThrow(id, balance);
}

// --- SafeTransfer ---
// Shen: (datatype safe-transfer)
export class SafeTransfer<B extends Brand> {
  private readonly _witness: Witness = mint();
  /** Phantom brand marker — never read; makes B invariant. */
  declare private readonly _brandB: (b: B) => B;
  private readonly _tx: Transaction<B>;
  private readonly _check: BalanceChecked<B>;
  private constructor(tx: Transaction<B>, check: BalanceChecked<B>) {
    this._tx = tx;
    this._check = check;
  }
  static createOrThrow<B extends Brand>(tx: Transaction<B>, check: BalanceChecked<B>): SafeTransfer<B> {
    mustBeMinted((tx as unknown as { _witness?: Witness })._witness, "Transaction");
    mustBeMinted((check as unknown as { _witness?: Witness })._witness, "BalanceChecked");
    return new SafeTransfer<B>(tx, check);
  }
  static tryCreate<B extends Brand>(tx: Transaction<B>, check: BalanceChecked<B>): SafeTransfer<B> | Error {
    try { return SafeTransfer.createOrThrow<B>(tx, check); }
    catch (e) { return e instanceof Error ? e : new Error(String(e)); }
  }
  tx(): Transaction<B> { mustBeMinted(this._witness, "SafeTransfer"); return this._tx; }
  check(): BalanceChecked<B> { mustBeMinted(this._witness, "SafeTransfer"); return this._check; }
}
export function mustSafeTransfer<B extends Brand>(tx: Transaction<B>, check: BalanceChecked<B>): SafeTransfer<B> {
  return SafeTransfer.createOrThrow<B>(tx, check);
}

// --- helpers derived from (define …) blocks ---
// __val defensively projects a wrapped value. On primitives it is the
// identity, because Shen specs occasionally apply `val` to already-
// unwrapped accumulators (e.g. scanl seeded with `(val B0)`).
function __val(x: any): any {
  return (x && typeof x.val === "function") ? x.val() : x;
}
// scanl: left-scan matching Shen semantics. Emits intermediate
// accumulator values, returning [init, f(init, l[0]), f(f(init, l[0]), l[1]), …].
function __scanl<A, T>(f: (a: A) => (t: T) => A, init: A, list: T[]): A[] {
  const out: A[] = [init];
  let acc: A = init;
  for (const x of list) { acc = f(acc)(x); out.push(acc); }
  return out;
}

// processable is generated from Shen define processable
export function processable<B extends Brand>(b0: Amount, txs: Transaction<B>[]): boolean {
  return __scanl((b: any) => (tx: any) => (__val(b) - __val(tx.amount())), __val(b0), txs).reduceRight((acc: any, x: any) => ((x: any) => (acc: any) => ((__val(x) >= 0) && acc))(x)(acc), true);
}

